### ISSUE TITLE
Warning: findDOMNode is deprecated in StrictMode...

### ISSUE THREAD

**Issue by Ginioo** [react-grid-layout/react-grid-layout#1091]
Hi,

I got these deprecation warnings.
It seems that we can replace `ReactDOM.findDOMNode` with `React.createRef`.

DraggableCore
```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DraggableCore which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node...
```

WidthProvider
```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of WidthProvider which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node...
```

**Comment by Semigradsky** [comment]
Still alive issue

**Comment by dan-nadler** [comment]
I just ran into this as well

**Comment by fullstackdb** [comment]
This issue still exists.

In documentation we've some information about `innerRef`:
```
// Ref for getting a reference for the grid's wrapping div.
// You can use this instead of a regular ref and the deprecated `ReactDOM.findDOMNode()`` function.
innerRef: ?React.Ref<"div">
```

However, covering `GridLayout` into `div` and passing its ref to `GridLayout.innerRef` not solving an issue.

Are there any recipes to solve `findDOMNode is deprecated in StrictMode` issue?

**Comment by Semigradsky** [comment]
@STRML could you reopen please? It was closed by bot.

**Comment by STRML** [comment]
Yes, this is still an issue as GridItem uses `findDOMNode`.

**Comment by Semigradsky** [comment]
@STRML Hi! Looks like issue was closed again because `stale` label is on issue.

**Comment by mnemanja** [comment]
@STRML any suggestion on how to solve this?

**Comment by matthew-davies-hrp** [comment]
@STRML this is still an issue, is there a reason why it's closed?

**Comment by daviesgeek** [comment]
This is still on my list of things to revisit but I just haven’t had the time to do so

**Comment by KareemMamdouh** [comment]
any update?

**Comment by ViktoriyaBurdey** [comment]
still here

**Comment by yipei1028** [comment]
Hi @ViktoriyaBurdey,

Seems @STRML  already solved in this pull request:
https://github.com/react-grid-layout/react-grid-layout/pull/1425

Take a look into it. And upgrade to v1.2.3

Cheers,
Yi-Pei
