### ISSUE TITLE
Does not always load correct width on refresh

### ISSUE THREAD

**Issue by seanaguinaga** [react-grid-layout/react-grid-layout#1338]
Please only submit bugs to this tracker. If you have a feature request, please implement it. This is free software and the author is busy with other projects.

Please use the [CodeSandbox Template](https://codesandbox.io/s/5wy3rz5z1x?module=%2Fsrc%2FShowcaseLayout.js) to demonstrate your bug. It is much easier for us to help you if you do.

I am using react-grid-layout with IonicReact and it does no behave consistently

See Video:

https://ttprivatenew.s3.amazonaws.com/pulse/sean-preconceptiontest/attachments/15306477/TinyTake21-11-2020-02-36-29.mp4

If you haven't seen this behavior before, should I create a codesandbox with this particular set up?

**Comment by seanaguinaga** [comment]
https://ttprivatenew.s3.amazonaws.com/pulse/sean-preconceptiontest/attachments/15310481/TinyTake22-11-2020-08-38-08.mp4

It's like it doesn't get the width initially?

It will resize correctly when I adjust the window after mount.

How can I make sure it gets the initial size right?

The WidthProvider doesn't seem to work here?

Neither does setting a width manually?

**Comment by seanaguinaga** [comment]
![image](https://user-images.githubusercontent.com/15254340/99911066-c9fe1f80-2ca6-11eb-925e-ffedb0a1058c.png)

onWidthChange on Refresh logs 0 as current width

then behaves properly on resize

![image](https://user-images.githubusercontent.com/15254340/99911077-e306d080-2ca6-11eb-9537-22e61f46f867.png)

**Comment by gph5003** [comment]
I am experiencing the same issue with the width provider being 0 until the window is resized. I've been trying to get this to work for my job for weeks. Let me know if you come up with anything and i'll do the same.

**Comment by seanaguinaga** [comment]
@gph5003  

**"This allows you to easily replace WidthProvider with your own Provider HOC if you need more sophisticated logic.

WidthProvider accepts a single prop, measureBeforeMount. If true, WidthProvider will measure the container's width before mounting children. Use this if you'd like to completely eliminate any resizing animation on application/component mount.

Have a more complicated layout? WidthProvider is very simple and only listens to window 'resize' events. If you need more power and flexibility, try the [SizeMe ](https://github.com/ctrlplusb/react-sizeme)React HOC as an alternative to WidthProvider."**

https://github.com/ctrlplusb/react-sizeme

I am going to try using this?

**Comment by seanaguinaga** [comment]
```
  return allSlots.docs.length > 0 ? (
    <SizeMe>
      {({ size }) => (
        <Responsive
          style={{
            border: "1px solid red",
          }}
          width={size.width as number}
          breakpoints={breakpoints}
          className="layout"
          cols={{ lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 }}
          rowHeight={50}
          compactType={"vertical"}
          isResizable={false}
          isDraggable={false}
          preventCollision={true}
          onResizeStop={(_, oldItem, newItem) =>
            handleDragging({ oldItem, newItem })
          }
          onLayoutChange={(currentLayout) => {
            setCurrentLayout(currentLayout);
          }}
          onDrop={(newLayout, layoutItem, event) => {
            handleDrop({ newLayout, layoutItem });
          }}
          onDragStop={(_, oldItem, newItem) =>
            handleDragging({ oldItem, newItem })
          }
          isDroppable={true}
          onBreakpointChange={(newBreakpoint: typeof currentBreakpoint) => {
            console.log(newBreakpoint);
            setCurrentBreakpoint(newBreakpoint);
          }}
          onWidthChange={(containerWidth) => {
            console.log(containerWidth);
            onWidthChange(containerWidth);
          }}
        >
          {currentBreakpoint && children}
        </Responsive>
      )}
    </SizeMe>
  ) : (
    <ErrorBoundary>
      {!code && <IonProgressBar type="indeterminate" />}
      <Suspense fallback={null}>
        {ref && <LazyTextFile text={code} setText={setCode} storageRef={ref} />}
      </Suspense>
    </ErrorBoundary>
  );
```

@gph5003  I got this to work?

Let me know!

**Comment by seanaguinaga** [comment]
@gph5003 can you figure out how to turn ({size}) into a debounced value?

It re-renders every change but it could probably happen less?

**Comment by gph5003** [comment]
Hmm SizeMe doesn’t seem to fix my issues. I’ll have to keep trying.

**Comment by drixie** [comment]
@seanaguinaga Just so you know, your tinytake videos were not playing for me. Perhaps you should share a codesandbox?

**Comment by WaqqarSuleman** [comment]
> https://ttprivatenew.s3.amazonaws.com/pulse/sean-preconceptiontest/attachments/15310481/TinyTake22-11-2020-08-38-08.mp4
> 
> It's like it doesn't get the width initially?
> 
> It will resize correctly when I adjust the window after mount.
> 
> How can I make sure it gets the initial size right?
> 
> The WidthProvider doesn't seem to work here?
> 
> Neither does setting a width manually?

I am facing the same issue while using this inside of React Bootstrap modal, any solution?

**Comment by anhba817** [comment]
I also get the same issue. And using react-sizeme work for me:
```
import RGL from "react-grid-layout";
import { SizeMe } from "react-sizeme";
.....
render() {
    return (
      <SizeMe>
        {({ size }) => (
          <RGL
            cols={12}
            rowHeight={30}
            onLayoutChange={this.onLayoutChange}
            width={size.width}
          >
            {this.props.children}
          </RGL>
        )}
      </SizeMe>
    );
  }
```

**Comment by WaqqarSuleman** [comment]
> I also get the same issue. And using react-sizeme work for me:
> 
> ```
> import RGL from "react-grid-layout";
> import { SizeMe } from "react-sizeme";
> .....
> render() {
>     return (
>       <SizeMe>
>         {({ size }) => (
>           <RGL
>             cols={12}
>             rowHeight={30}
>             onLayoutChange={this.onLayoutChange}
>             width={size.width}
>           >
>             {this.props.children}
>           </RGL>
>         )}
>       </SizeMe>
>     );
>   }
> ```

I fixed my issue by disabling the Modal animation.

**Comment by JamesRamm** [comment]
As others have noted, it is up to the application code to provide a width. You can do this before mount, or you could use this recipe to have it resize right after mounting:

```js
import { useState, useCallback } from 'react';

/**
* Hook to get the width of a container
*/
export default function useSize() {
   const [rect, setRect] = useState(null);
   const resizer = new ResizeObserver(entries => {
      entries && setRect(entries[0].contentRect);
   });
   const ref = useCallback(node => {
      if (node !== null) {
         resizer.observe(node);
         setRect(node.getBoundingClientRect());
      }
   }, []);
   return [rect, ref];
}
```

To use it, I put the grid in a flexbox div which will expand to the full width/height (or however you want to control your flexbox). 
I start off by providing the grid some default width, which gets corrected to the exact width of the flexbox, e.g

```js

function MyGrid({ initialWidth, children, ...rest }) {

   const [rect, ref] = useSize();
   const width = rect ? rect.width : initialWidth;
   return (
      <MyFlexBox ref={ref}>
            <Responsive {...rest} width={width}>
                 {children}
            </Responsive>
      <MyFlexBox >
   )
}


```

**Comment by Lueton** [comment]
> As others have noted, it is up to the application code to provide a width. You can do this before mount, or you could use this recipe to have it resize right after mounting:
> 
> ```js
> import { useState, useCallback } from 'react';
> 
> /**
> * Hook to get the width of a container
> */
> export default function useSize() {
>    const [rect, setRect] = useState(null);
>    const resizer = new ResizeObserver(entries => {
>       entries && setRect(entries[0].contentRect);
>    });
>    const ref = useCallback(node => {
>       if (node !== null) {
>          resizer.observe(node);
>          setRect(node.getBoundingClientRect());
>       }
>    }, []);
>    return [rect, ref];
> }
> ```
> 
> To use it, I put the grid in a flexbox div which will expand to the full width/height (or however you want to control your flexbox). I start off by providing the grid some default width, which gets corrected to the exact width of the flexbox, e.g
> 
> ```js
> function MyGrid({ initialWidth, children, ...rest }) {
> 
>    const [rect, ref] = useSize();
>    const width = rect ? rect.width : initialWidth;
>    return (
>       <MyFlexBox ref={ref}>
>             <Responsive {...rest} width={width}>
>                  {children}
>             </Responsive>
>       <MyFlexBox >
>    )
> }
> ```

Thanks for the solution! It works, but it seems like there is a problem with the `useSize` hook. I always get an error when unmounting my page with the grid:

`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.`

There error points at this line:
```js
entries && setRect(entries[0].contentRect);
``` 
However I fixed it by using following code:

```js
function useSize() {
  const [rect, setRect] = useState(null);

  const resizer = useMemo(() => new ResizeObserver(entries => {
    entries && setRect(entries[0].contentRect);
  }), []);

  const ref = useCallback(node => {
    if (node !== null) {
      resizer.observe(node);
      setRect(node.getBoundingClientRect());
    }
  }, [resizer]);

  useEffect(() => {
    return () => resizer.disconnect();
  }, [resizer]);

  return [rect, ref];
}
```
