### ISSUE TITLE
Items not compacting properly in responsive mode, weird glitch when dragging items

### ISSUE THREAD

**Issue by drixie** [react-grid-layout/react-grid-layout#1376]
See codesandbox - https://codesandbox.io/s/hardcore-dew-0bzip?file=/src/App.js

First issue - When the breakpoint is set to md or lg, Box "a" does not fill up the space adjacent to "e" and below "b" as expected. What can I do to make this work? It would also be nice to have to boxes display in accordance to how they are structure (e.g. "a" should be displayed first, followed by b, and c... in a left to right order). 

Second issue - Whenever, i try to drag items, and the item being dragged overlaps existing items, there is shaking effect during which the structure of all the items is temporarily disrupted until the drop has been made. How do I fix this issue? It is not nice from a UX perspective.

**Comment by drixie** [comment]
Issue #1 seems to be a long running issue - https://github.com/STRML/react-grid-layout/issues/66

The only solution I have found so far is to declare the initial layout and account for all the [x, y, w, h] values. That said, I am not sure how well it will hold when users drag things around in ways you never thought possible. 

Issue #2 happens only in horizontal compaction. Does not occur when vertical compaction is set

**Comment by drixie** [comment]
Detailed discussion on issue #1 from 2018 - https://github.com/STRML/react-grid-layout/issues/784

Any takers on solving this in 2021? 😄

**Comment by s4m3** [comment]
@drixie thanks for digging up the latest discussions on that. My main concern is issue 2 right now. Will have a look into the code today, to see what is causing this.

**Comment by s4m3** [comment]
@drixie just an FYI: I did work on it for a couple of hours and was able to isolate one of the issues, but then more pressing issues came up, so this is put on hold. Will get back to it over the week however.

**Comment by s4m3** [comment]
@drixie I opened a Pull Request that solves the second issue, but I am not sure what the response time is here with the owner. Meaning how long it takes until he looks at these Pull Requests. I see a lot of stale Pull Requests as well. I guess we can only be patient...

**Comment by drixie** [comment]
@s4m3 Thanks a lot for the prompt action on this. Let's hope the owner reviews your PR soon. If we don't get a response in two weeks, do you mind setting up an alternate repo / npm package so I can test?

**Comment by s4m3** [comment]
@drixie you can checkout this one locally and try it standalone:
https://github.com/s4m3/react-grid-layout/tree/bugfix/horizontal-compact-mode-issues
