### ISSUE TITLE
Cannot enable dragging dynamically

### ISSUE THREAD

**Issue by GasimGasimzada** [react-grid-layout/react-grid-layout#1391]
I have a very simple code:

```tsx
const EditableGridLayout = props => {
  const [drag, setDrag] = useState(false);

  return (
    <>
      <ResponsiveGridLayout {...props} isDraggable={drag}>
        ...
      </ResponsiveGridLayout>
      <button onClick={() => setDrag(drag => !drag)}>Toggle DnD</button>
    </>
  );
}
```

However, the item does not become draggable. I went into React DevTools and the `GridItem` component receives the correct `isDraggable` prop; however, in `DraggableCore` component, the prop `disabled` is `true`.

Weirdly, when I changed the `disabled` prop manually from DevTools for one grid item, the dragging started working for all items.

How can enable dragging dynamically?

CodeSandbox: https://codesandbox.io/s/serene-dubinsky-16q9r

EDIT: It looks like it is not working because I am "decorating" the responsive grid.

**Comment by JamesRamm** [comment]
@GasimGasimzada 
Set the `isDraggable` property on each item - it overrides the global `isDraggable` property:

https://codesandbox.io/s/patient-star-7bsy7
