### ISSUE TITLE
Dynamic `droppingItem` prop or expose `onDragOver`

### ISSUE THREAD

**Issue by JamesRamm** [react-grid-layout/react-grid-layout#1394]
Hi

I am using RGL with drag and drop to drag items from a sidebar onto the grid. Each item has it's own minW/minH which is carried in the drag data (`dataTransfer`). This works great but I would like to make the `droppingItem` overlay also respect the minimum size. 

The only way I can see to do this would be possibly to expose the onDragOver event, or rather, accept a function prop which will be called at the start of the `onDragOver` handler in ReactGridLayout, so that we may dynamically update `droppingItem`.
Or `droppingItem` could be that function - e.g. at the start of `onDragOver` if `droppingItem` is a function, call it with the event and expect to receive the `droppingItem` object as the return value.

I am happy to propose a patch, but was wondering if some kind of control like this is already possible?

**Comment by JamesRamm** [comment]
No response on this? I don't consider it stale, just that no one seems to be maintaining this project...

**Comment by sonmansu** [comment]
Did you find any solution? same problem with me.

**Comment by B33fb0n3** [comment]
Dynamic configuration is possible, but you **can't access** the data, that you entered while setting the data:
```tsx
e.dataTransfer.setData("text/plain", "data"); // or stringified data string
```
Am I just blind or is there no option to get this data inside the ``onDropDragOver``-Event to determine the size of the element?
