### ISSUE TITLE
Can we adjust react grid layout in which column width will be adjusted as 'n' column wide?

### ISSUE THREAD

**Issue by PriyankaBhise** [react-grid-layout/react-grid-layout#1399]
Adjust the grid settings so that they are only three "Columns" wide. This is meaning that a single widget can take up a 1/3 of the grid, 2/3 of the grid or 3/3 of the grid with. This means when you adjust the width of the widget it should snap to one of these 3 options.
![react](https://user-images.githubusercontent.com/47520963/107489474-a7e1b280-6bae-11eb-8d2e-6ccb2771bb83.png)

**Comment by JamesRamm** [comment]
@PriyankaBhise 
I think this is already the case? Unless I misunderstand you. You can provide the `cols` property to the `Grid` or `Responsive` components in order to set the number of columns. If resize is enabled (true by default), it will automatically snap to a column when you resize a component

**Comment by PriyankaBhise** [comment]
My cols value is ,cols={{ lg: 32, md: 32, sm: 10, xs: 6, xxs: 4 }} , I want only 1/3, 2/3, 3/3 widgets on a column,
![cols](https://user-images.githubusercontent.com/47520963/109923729-3694ab80-7ce5-11eb-9626-55c2cc2aa60b.png) 
suppose total cols width is 33, If I want,
1/3 of widgets then total widget size will be 33
2/3 then 1st widget can be 11 and 2nd can be 22 or 1st can 22 and 2nd can 11
3/3 then all 3 widgets will be of size 11 each.
As in diagram. I want widgets with config 2/3, and 2nd widget is of size 22,and 1st if of 8 and there is some remaining space with size 3. So, I want the first widget get snapped with the size 11 automatically even if I resize it to  7 or 8. and if try to increase the size of 2nd widget (which is 22 now) then 2nd widget should occupy whole column space with size 33, and 1st widget should be moved to next column.

**Comment by PriyankaBhise** [comment]
> @JamesRamm My cols value is ,cols={{ lg: 32, md: 32, sm: 10, xs: 6, xxs: 4 }} , I want only 1/3, 2/3, 3/3 widgets on a column,
> ![cols](https://user-images.githubusercontent.com/47520963/109923729-3694ab80-7ce5-11eb-9626-55c2cc2aa60b.png)
> suppose total cols width is 33, If I want,
> 1/3 of widgets then total widget size will be 33
> 2/3 then 1st widget can be 11 and 2nd can be 22 or 1st can 22 and 2nd can 11
> 3/3 then all 3 widgets will be of size 11 each.
> As in diagram. I want widgets with config 2/3, and 2nd widget is of size 22,and 1st if of 8 and there is some remaining space with size 3. So, I want the first widget get snapped with the size 11 automatically even if I resize it to 7 or 8. and if try to increase the size of 2nd widget (which is 22 now) then 2nd widget should occupy whole column space with size 33, and 1st widget should be moved to next column.
