### ISSUE TITLE
Change of height/h not picked up

### ISSUE THREAD

**Issue by gavbrennan** [react-grid-layout/react-grid-layout#1400]
I have a situation where grid components resize themselves based on input, like a form expanding for additional choices or a variable amount of data being loaded and displayed. My code updates the "h" property of the layout object but this does not seem to have the desired effect - The exact behavior is one grid component sitting partially over another, where the grid clearly thinks the component is still the size before it was changed.   Adding a new component or removing an existing one from the grid seems to trigger a fix to the issue.

So in essence, changing the "h" property of the grid layout in-flight does not always immediately take effect.  Is there a work around for this?

**Comment by JamesRamm** [comment]
Hi @gavbrennan 
Can you give a minimal code example? You can use the editable demo as a starting point: https://codesandbox.io/s/5wy3rz5z1x?module=%2Fsrc%2FShowcaseLayout.js

**Comment by gavbrennan** [comment]
Hi James,

Have updated that demo - please let me know if you see any obvious mistakes!

Best,
Gavin

**Comment by lord-enzo** [comment]
I have the exact same problem... @gavbrennan, have you found a solution to your problem?

**Comment by gavbrennan** [comment]
Not as yet - I was hoping the code example (https://codesandbox.io/s/morning-fog-7oqoq) would get some attention but I guess not.  I've tried to force changing of all component keys on an update of height/width from within a component, but that failed miserably.  So still stuck!

**Comment by gavbrennan** [comment]
@JamesRamm - did you have chance to a look at https://codesandbox.io/s/morning-fog-7oqoq  ?

**Comment by JamesRamm** [comment]
@gavbrennan 
I'll need to check as I'm in my phone, but at first glance it looks like you are mutating the layouts array in place, which can be a problem for Reacts' diffing algorithm, you really need an immutable update here

**Comment by gavbrennan** [comment]
Thanks - that solved it.  Specifically, when adjusting the height on a component I created a new instance of the GridLayout.Layout object, copying all other properties across and inserting the new height.  It now behaves as expected, with objects dynamically updating their own height and the grid adjusting accordingly.

**Comment by priyankapyt** [comment]
hi @gavbrennan I'm also stuck with same issue but unable to figure out how did you create a new instance of GridLayout?
It would be really helpful if you can share some snippet for the same.

**Comment by rogerfar** [comment]
@priyankapyt This had me scratching my head a bit too, turns out if you use data-grid it doesn't look like you can easily change the parameters, but if you use the `layout` prop then it works. Just make sure to always return a new ref.
