### ISSUE TITLE
onDragStart fired when draggable container is merely clicked, but not onDragStop

### ISSUE THREAD

**Issue by MZanggl** [react-grid-layout/react-grid-layout#1401]
Example: https://codesandbox.io/s/angry-pond-dj3tl?file=/src/ShowcaseLayout.js:1829-1937

If you just click (not drag) on the draggable container you see the log from `onDragStart` in the console, but not from `onDragStop`.

Expected: Either none of the events, or both should be fired, so you can programmatically catch both beginning and end of drag drop.

This bug was introduced with this PR: https://github.com/STRML/react-grid-layout/pull/1023

Workaround: Use `onDrag` instead of `onDragStart`

**Comment by djmisterjon** [comment]
true, , but onDrag are not a work around !
