### ISSUE TITLE
Alternative for the grid layout

### ISSUE THREAD

**Issue by FernandoGOT** [react-grid-layout/react-grid-layout#1402]
Hi everyone, I'm implementing a background grid, [like the one from azure](https://youtu.be/p-Dy4rSQAQo?t=14), in my dashboard and perceived a "problem", so I'm posting here to see if anyone else has the same problem se we can work on it

### Problem 

 This list work with columns to define the cards width, normally this is not a problem, but because of this approach we can't define the dashboard layout with more precision for multiple screen sizes.

 You can open the dashboard in a ultrawide monitor and see how it stretch the cards from the dashboard, we can make some code to update the number of columns, but even so we couldn't see it to match so many resolutions.

### Solution

 My solution is to change the lib so the developer can use the columns or set the default width, like he can do with the height, with this we can have these advantages:

1. Cards with better design, we can garante the exact size of the cards and their variants
2. More space in wide screens, since the cards aren't going to stretch the user get more space for more cards

Anyone have already made something like this, can point where to change to implement it or is interested in helping with the implementation?

**Comment by JamesRamm** [comment]
Hi @FernandoGOT 
Not sure I fully understand your problem, but by using the [responsive grid ](https://github.com/react-grid-layout/react-grid-layout#responsive-usage) you can provide both the breakpoints and the number of columns for each breakpoint. You can also provide a separate layout for each breakpoint, giving you complete control of the layout & size of individual items for each size of device you define...
Does that help?
