### ISSUE TITLE
Error when trying to use getBreakpointFromWidth

### ISSUE THREAD

**Issue by SupeDeDupe** [react-grid-layout/react-grid-layout#1403]
I'm trying to use getBreakpointFromWidth from [this recipe](https://github.com/STRML/react-grid-layout/wiki/Users-recipes#access-the-current-breakpoint-in-responsive-mode), but I get "Unexpected token (5:12)" error:

![image](https://user-images.githubusercontent.com/17673146/108249711-63609480-7123-11eb-9d47-7298badfe9e8.png)

(^ a reference to the [responsiveUtils file](https://github.com/STRML/react-grid-layout/blob/245cd21f3b484e5b535d380410e2d5ea74e99f99/lib/responsiveUtils.js#L72))

This is essentially what's going on in my related code:
```
import { getBreakpointFromWidth } from 'react-grid-layout/lib/responsiveUtils.js'

type BreakpointsType = {
    readonly lg: number;
    readonly md: number;
    readonly sm: number;
    readonly xs: number;
    readonly xxs: number;
}
const BREAKPOINTS: BreakpointsType = {
  lg: 1200,
  md: 1024,
  sm: 768,
  xs: 480,
  xxs: 0
};

const myFunction = (screenWidth: number): String => {
// ... stuff
console.log(
    "current breakpoint:",
    getBreakpointFromWidth(BREAKPOINTS, screenWidth)
  );
// ... other stuff
}
```

I tried upgrading from  "react-grid-layout": "^0.18.2" to "react-grid-layout": "^1.2.0," upgrading typescript, npm installing, but none of it seemed to resolve the issue... Am I doing something wrong? Please help? 

Thanks!

**Comment by JamesRamm** [comment]
RGL uses [flow ](https://flow.org/) so you cannot import raw code directly from `lib` without also enabling flow in your own build chain. 
You must import from the distribution. From the index file (https://github.com/react-grid-layout/react-grid-layout/blob/master/index.js) it looks like you could:

```js
import { Responsive } from 'react-grid-layout';

Responsive.utils.getBreakpointFromWidth( ... )
```
