### ISSUE TITLE
Resizing items in the current demo does not appear to work.

### ISSUE THREAD

**Issue by Antti-Kaikkonen** [react-grid-layout/react-grid-layout#1407]
When trying to resize a grid element in the [current demo](https://react-grid-layout.github.io/react-grid-layout/examples/0-showcase.html) it returns back to the original size after the left mouse button is released.

In the [old demo](http://strml.github.io/react-grid-layout/examples/0-showcase.html) resizing works properly. 

I'm trying to use this library but struggling to get resizing to work without a working example. If I use an old version (0.18.3) then resizing works, but with 1.0.0 and newer it doesn't.

**Comment by STRML** [comment]
Looks like I introduced a new bug - sorry! Use 1.2.0 in the meantime, I'll
deprecate and publish a fix shortly.

**Comment by Antti-Kaikkonen** [comment]
> Looks like I introduced a new bug - sorry! Use 1.2.0 in the meantime, I'll deprecate and publish a fix shortly.
Thanks for the quick response. I already tried that version and it didn't work. It is possible that I did something wrong so I will try again when there is a working demo.

**Comment by choxi** [comment]
@STRML in case it helps, it looks like it was broken in this commit: https://github.com/react-grid-layout/react-grid-layout/commit/8a3ec09455b4e6175ed71b34b18b77114de846d4. I think the resizing logic was depending on the layout item being mutated. 

1.2.0 still works for me though.

**Comment by STRML** [comment]
Yep, thanks. `1.2.2` fixes this.

**Comment by Antti-Kaikkonen** [comment]
Thanks for the quick fix. I tested it and it is working now.
