### ISSUE TITLE
Drag from outside not working in controlled component. 

### ISSUE THREAD

**Issue by ImAbdullahJan** [react-grid-layout/react-grid-layout#1414]
I am working on a similar functionality like [Demo 15 - Drag From Outside](https://react-grid-layout.github.io/react-grid-layout/examples/15-drag-from-outside.html). I notice that provided example is an uncontrolled component. 

When I try to implement a similar feature with a controlled component (layout state is controlled when `onLayoutChange` callback trigger). I am getting `undefined` in the `onDrop` callback. 

[Sandbox](https://codesandbox.io/s/busy-edison-2lbfq?file=/src/App.js) is created to demonstrate this issue.  How I can get a drop element position in the grid?

**Comment by colodenn** [comment]
I had the same issue. Try to leave onLayoutChange empty and update your layout onDrop.

**Comment by ImAbdullahJan** [comment]
If I leave `onLayoutChange` empty then I cannot get the current layout after every drag or resize stop.

**Comment by jdbence** [comment]
Something like this probably would work for your sandbox
```
const onLayoutChange = (layout) => {
    if(!layout.find(li => li.i === 'Dropped')){
      setLayoutState(layout);
    }
};
```

**Comment by gonzofish** [comment]
the `i` for me is `'__dropping-elem__'`

**Comment by b0arderman** [comment]
Did anyone solve this issue?  I am having a similar issue.  Also, I am noticing the component drug in from outside isn't changing the layout like it does in the Demo 15 example
