### ISSUE TITLE
Responsive Grid Layout: layouts object replacement

### ISSUE THREAD

**Issue by adagit94** [react-grid-layout/react-grid-layout#1415]
Hi,

after changes in layout item object after that necessary calculations are made, new object with layouts passed into Responsive component isnt correctly replaced after rerender even though lodash cloneDeep method is used, but when converted to string and back to new object as in case of JSON.parse(JSON.stringify(this.layouts)) layouts are updated internaly in component correctly.

**Comment by sscots** [comment]
I was experiencing the same issue and JSON.parse(JSON.stringify(.......)) worked for me also, per @adagit94 suggestion.
