### ISSUE TITLE
Drag and Drop from Sidebar. Different size for draggable sidebar item.

### ISSUE THREAD

**Issue by colodenn** [react-grid-layout/react-grid-layout#1416]
I followed the demo to drag from outside. Now I added a second draggable Item. 
The first Item should produce a green 2x2 tile and the second draggable Item should produce a red 2x2 tile.

How would I do something like this? 

To change the color and size I would use the approach in issue #1405 

But how would I change the color and size of the tile while hovering the new tile into the grid?

![image](https://user-images.githubusercontent.com/43729834/110652442-aa8af400-81bc-11eb-9e56-2f59e604a4d2.png)

**Comment by linus-amg** [comment]
@colodenn I wanted to do something similar and achieved it by creating a `ref` and setting it's `kind` in the `onDragStart` handler of the `draggable` (the items in your toolbar) and reading this `ref` in the `onDropDragOver` and `onDrop` event-handlers of `RGL`.

the draggable
```js
<Button
  unselectable="on"
  draggable
  onDragStart={(e) => {
    draggingKind.current = formElement.kind; // e.g. 'text' or 'frame'
    e.dataTransfer.setData('text/plain', formElement.kind); // ignore this
  }}
>
  Text
</Button>
```

the droparea (RGL)
```js
<ReactGridLayout
  className="layout"
  cols={2048}
  isDroppable
  compactType={null}
  onLayoutChange={handleLayoutChange}
  onDrop={onDrop}
  containerPadding={[0, 0]}
  margin={[0, 0]}
  onDropDragOver={onDropDragOver}
  rowHeight={14}
  width={2048}
  style={{ height: '100%' }}
>
```

somewhere over your component
```js
const dimensionsByKind = {
  frame: { w: 468, h: 32 },
  input: { w: 256, h: 4 }
};
```

the handlers and ref
```js



const draggingKind = useRef(null);

const onDrop = (layout, layoutItem) => {
  if (layoutItem) {
    const dimensions = dimensionsByKind[draggingKind.current];
    layoutItem.i = String(new Date().getTime());
    layoutItem.w = dimensions.w;
    layoutItem.h = dimensions.h;
  }

  setLayout(layout);
};

// returns the dimensions you want while dragging from outside for that specific kind
const onDropDragOver = () => {
  return dimensionsByKind[draggingKind.current];
};
```

**Comment by sagarnanera** [comment]
I am doing the same and I want to set the Drag Image using the `setDragImage` function when the element is hovering over the RGL (react grid layout)  but  the `dataTransfer` event which we are getting in `onDropDragOver` callback doesn't allowing us to do the same.

Any solution for this ?
