### ISSUE TITLE
Warning: Failed prop type: minWidth larger than item width/maxWidth

### ISSUE THREAD

**Issue by SmashPlusUltra** [react-grid-layout/react-grid-layout#1418]
I'm using "react-grid-layout": "^1.2.2", and I get a console warning
Warning: Failed prop type: minWidth larger than item width/maxWidth
    in GridItem (created by ReactGridLayout)
    in ReactGridLayout (created by ResponsiveReactGridLayout)
    in ResponsiveReactGridLayout (created by WidthProvider)
    in WidthProvider (at App.js:97)
    in div (at App.js:87)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:86)
    in div (at SignalRConnector.js:46)
    in Unknown (at App.js:85)
    in Provider (at App.js:84)
    in App (at src/index.js:13)
    in StrictMode (at src/index.js:11)
 index.js:1
Warning: Failed prop type: minHeight larger than item height/maxHeight
    in GridItem (created by ReactGridLayout)
    in ReactGridLayout (created by ResponsiveReactGridLayout)
    in ResponsiveReactGridLayout (created by WidthProvider)
    in WidthProvider (at App.js:97)
    in div (at App.js:87)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:86)
    in div (at SignalRConnector.js:46)
    in Unknown (at App.js:85)
    in Provider (at App.js:84)
    in App (at src/index.js:13)
    in StrictMode (at src/index.js:11)

**Comment by STRML** [comment]
Please open up a discussion instead, this looks like user error.
