### ISSUE TITLE
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DraggableCore which is inside StrictMode

### ISSUE THREAD

**Issue by SmashPlusUltra** [react-grid-layout/react-grid-layout#1419]
I'm using "react-grid-layout": "^1.2.2", and I get a console warning
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DraggableCore which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in span (created by Resizable)
    in DraggableCore (created by Resizable)
    in div (at App.js:100)
    in Resizable (created by GridItem)
    in DraggableCore (created by GridItem)
    in GridItem (created by ReactGridLayout)
    in div (created by ReactGridLayout)
    in ReactGridLayout (created by ResponsiveReactGridLayout)
    in ResponsiveReactGridLayout (created by WidthProvider)
    in WidthProvider (at App.js:97)
    in div (at App.js:87)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:86)
    in div (at SignalRConnector.js:46)
    in Unknown (at App.js:85)
    in Provider (at App.js:84)
    in App (at src/index.js:13)
    in StrictMode (at src/index.js:11)

**Comment by w3ichen** [comment]
It works for me if you downgrade to version 1.2.3. See [here](https://github.com/react-grid-layout/react-grid-layout/issues/1331#issuecomment-800458381).
