### ISSUE TITLE
How to render custom placeholder element 

### ISSUE THREAD

**Issue by JaLe29** [react-grid-layout/react-grid-layout#1426]
Hi community!

Is there any way how to render custom placeholder item during the dragging action?

Basically I would like to render current dragging element as a placeholder instead of "red" rectangle.

Thank you for any help!

**Comment by yipei1028** [comment]
Hi @JaLe29 ,

You can customize your placeholder by adding/restyling the following CSS class:

```
.react-grid-item.react-grid-placeholder {
  background: red;
  opacity: 0.2;
  transition-duration: 100ms;
  z-index: 2;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  -o-user-select: none;
  user-select: none;
}
```

Hope it helps.
Cheers,
Yi-Pei

**Comment by JaLe29** [comment]
He @yipei1028 thank you. Of course I can edit css... but I don't care about placeholder css. I would like to render my custom element. 

Like:
```
<div> THIS IS MY CUSTOM PLACEHOLDER ELEMENT</div>
```

**Comment by STRML** [comment]
We don't have any capability for that at the moment, but you could add a prop as a PR if you wish. Otherwise, you could use CSS pseudo elements to render text.

**Comment by SumanthJP** [comment]
I did this by listening to the drag start event, getting the dom element for the placeholder, and rendering a custom React component inside it using ReactDOM.render. You can check a barebones example here: [Codesandbox Link](https://codesandbox.io/s/rgl-style-placeholder-forked-9j63i?file=/src/index.js)
