### ISSUE TITLE
 @JamesRamm My cols value is ,cols={{ lg: 32, md: 32, sm: 10, xs: 6, xxs: 4 }} , I want only 1/3, 2/3, 3/3 widgets on a column,

### ISSUE THREAD

**Issue by PriyankaBhise** [react-grid-layout/react-grid-layout#1430]
> @JamesRamm My cols value is ,cols={{ lg: 32, md: 32, sm: 10, xs: 6, xxs: 4 }} , I want only 1/3, 2/3, 3/3 widgets on a column,
> ![cols](https://user-images.githubusercontent.com/47520963/109923729-3694ab80-7ce5-11eb-9626-55c2cc2aa60b.png)
> suppose total cols width is 33, If I want,
> 1/3 of widgets then total widget size will be 33
> 2/3 then 1st widget can be 11 and 2nd can be 22 or 1st can 22 and 2nd can 11
> 3/3 then all 3 widgets will be of size 11 each.
> As in diagram. I want widgets with config 2/3, and 2nd widget is of size 22,and 1st if of 8 and there is some remaining space with size 3. So, I want the first widget get snapped with the size 11 automatically even if I resize it to 7 or 8. and if try to increase the size of 2nd widget (which is 22 now) then 2nd widget should occupy whole column space with size 33, and 1st widget should be moved to next column.

_Originally posted by @PriyankaBhise in https://github.com/react-grid-layout/react-grid-layout/issues/1399#issuecomment-801616176_

**Comment by JamesRamm** [comment]
@PriyankaBhise 
This is an application-specific use-case, so you should manage it using the `onResizeStop` callback which you can pass to the RGL Grid component

**Comment by JamesRamm** [comment]
@PriyankaBhise 
Take a look at this demo which implements more complex rules for widget sizes:
https://react-grid-layout.github.io/react-grid-layout/examples/10-dynamic-min-max-wh.html
