### ISSUE TITLE
How to calculate width?

### ISSUE THREAD

**Issue by charl5sgithub** [react-grid-layout/react-grid-layout#1432]
I have seen the entry for height calculation(h * rowHeight + (h - 1) * margin) that works perfect for me. 
How to calculate for width? Is the above formula applicable for width also?
  ```
 margin={[5, 5]}
   rowHeight={85}
```

**Comment by charl5sgithub** [comment]
@torkelo Could you guide me at this item width calculation?
My item size should  be 85 * 85. If I resize, the width should calculate proportionally(w * colWidth+ (w - 1) * margin) similar like height. 
` ScreenSize = 3840px * 2160px; `
The props for ResponsiveGridLayout are
```
        margin={[5, 5]}
        breakpoints={{lg: 1800}}
        cols={{lg: 44}}
        rowHeight={85}
```

If I inspect the element 
```
element.style {
    height: 85px;
    position: absolute;
    transform: translate(0px, 0px);
    width: 84px;
}
```

**Comment by yipei1028** [comment]
Hi @charl5sgithub ,

If I’m not mistaken, there is no configuration for column width, cause width should be responsive while screen size changing which is caused by the variable `containerWidth`.

```
// calculateUtils.js L:13-19
// Helper for generating column width
export function calcGridColWidth(positionParams: PositionParams): number {
  const { margin, containerPadding, containerWidth, cols } = positionParams;
  return (
    (containerWidth - margin[0] * (cols - 1) - containerPadding[0] * 2) / cols
  );
}```

Cheer,
Yi-Pei
