### ISSUE TITLE
Does the <GridLayout/> property 'width' support percentage?

### ISSUE THREAD

**Issue by jjzjx118** [react-grid-layout/react-grid-layout#1435]
I want to know if the <GridLayout/> property 'width' supports percentage?
like:

			<GridLayout
				style={{ backgroundColor: 'green' }}
				className='layout'
				layout={layout}
				cols={12}
				rowHeight={50}
				width={'100%'}
			>
?

**Comment by JamesRamm** [comment]
Hi @jjzjx118 
The width needs to be an absolute pixel value.

You can use `WidthProvider` to calculate the absolute width:
https://github.com/react-grid-layout/react-grid-layout#providing-grid-width
