### ISSUE TITLE
release 1.2.3 breaks custom components

### ISSUE THREAD

**Issue by jegsar** [react-grid-layout/react-grid-layout#1436]
Want to start off by saying that I'm glad to see the recent focus on this project again, I started looking at it about 2 months ago and started implementation again today when I ran into this error today: `<DraggableCore> not mounted on DragStart!`

Seems that custom components broke with version 1.2.3 and are still broken in version 1.2.4.

as an example this works on <=1.2.2 but breaks on 1.2.3 as shown in the example linked.
`const Awesome = (props) => <div {...props}>{props.children}</div>;`

[CodeSandbox with bug](https://codesandbox.io/s/wild-smoke-77xhy?file=/src/ShowcaseLayout.js)

**Comment by STRML** [comment]
Thanks. This has to do with the recent `ref` changes to avoid React-DOM.

The below will fix the issue but this is clearly breaking... considering how to fix it. We may have to go to v2, in which case I want to clean up all the ref/nodeRef nonsense.

```js
const Awesome = React.forwardRef((props, ref) => <div ref={ref} {...props}>{props.children}</div>);
```

**Comment by NickisyourFan** [comment]
Hey STRML! Thanks for the hard work! I am really enjoying how this works. 

I just encountered the same problem and found the same solution as to adding the forwardRef to my functional component - but it seems not to work? I am probably doing this wrong... Would you be willing to take a look at my draggable component to see why the refs are not working?

**Comment by NickisyourFan** [comment]
> Hey STRML! Thanks for the hard work! I am really enjoying how this works.
> 
> I just encountered the same problem and found the same solution as to adding the forwardRef to my functional component - but it seems not to work? I am probably doing this wrong... Would you be willing to take a look at my draggable component to see why the refs are not working?

NEVERMIND -- I was doing the forwardRef correctly. The issue is I was putting the ref on a component of CoreUI. I enclosed the components in a div instead, moved the keys up to the divs, and shes working again!

Thanks again for the hard work!
