### ISSUE TITLE
OnClick does not register correctly when presenting a chrome window in microsoft teams after rgl 17.1

### ISSUE THREAD

**Issue by oscarkilhed** [react-grid-layout/react-grid-layout#1441]
How to reproduce:

1. [CodeSandbox example](https://codesandbox.io/s/sparkling-frost-b5ozq?file=/package.json)
2. Present the chrome window in a microsoft teams call.
3. Click one of the boxes, the on click event does not fire.

![teams-present-issue](https://user-images.githubusercontent.com/468940/113704317-43d5f900-96dc-11eb-9b40-d913b638e8ea.gif)

**Comment by oscarkilhed** [comment]
Seems to have been introduced in #1123

**Comment by STRML** [comment]
That PR mostly got reverted. 

I can't replicate this because I don't use Microsoft Teams. If Teams causes this, it is a bug in Teams, not a bug in RGL.

**Comment by oscarkilhed** [comment]
> That PR mostly got reverted.

https://github.com/react-grid-layout/react-grid-layout/blob/4e97f9e22593d49d65c6cdb24939916319d6ee3e/lib/ReactGridLayout.jsx#L211
This line seems to be part of the cause and it's still here. I'm not exactly sure what's going on yet, but for some reason onDrag is triggered multiple times causing activeDrag, in the state, to not match.

> If Teams causes this, it is a bug in Teams, not a bug in RGL.

There's definitely something weird going on when a browser window is shared with Teams. I'm merely trying to figure out if this is something that can be handled by RGL.

**Comment by risoms** [comment]
This is occurring outside of Microsoft teams. [Grafana](https://github.com/grafana/grafana/issues/25018) is also experiencing the same issue.
