### ISSUE TITLE
Drag from Outside issue in Chromium browsers

### ISSUE THREAD

**Issue by TomasKomprs** [react-grid-layout/react-grid-layout#1442]
Hello,
I have seen similar issues here, but all are closed and not fixed.

Issue is "only" presented in Chrome / Chromium browsers. If you drop item from outside, it sometimes didn't drop.
I have included fix for Firefox and D&D/drop from outside works 100% correct. "Only" in chromium browser is this issue. (Chrome and Brave for example)

We can see this issue in your demo too. So i don't have to reproduce it in codesandbox. Just try it a few times. Drop it in different places, different speed etc.
https://react-grid-layout.github.io/react-grid-layout/examples/15-drag-from-outside.html

I tried figure out what it could be, but so far I don't have any idea. Don't have much time look at this. Can someone check this out, please? I think this is a crucial issue.

I'm running React 17+, react-grid-layout 1.2.4

**Comment by STRML** [comment]
Thanks, fixed in `1.2.6`.
