### ISSUE TITLE
Request for adding tab headers pinned on the side(left, right, bottom) 

### ISSUE THREAD

**Issue by sharmillamuthu** [react-grid-layout/react-grid-layout#1443]
I'm trying to add tab headers pinned on the sides (left, right, bottom) as shown in the image below
![initial modified](https://user-images.githubusercontent.com/53299877/114022342-49c00b80-988f-11eb-8d17-4f68671bf4a6.png)

On Clicking on the headers, the tab should be opened. If there are multiple tab headers listed on the side, the first clicked header should be added to the tabset first then the second clicked should also get added to the tabset without closing the first one.
![onexpanding modified](https://user-images.githubusercontent.com/53299877/114022595-8ee43d80-988f-11eb-8dbe-ce33b11f1840.png)

Is this feature supported or any workaround available

**Comment by STRML** [comment]
No. This library doesn't even do tabs.

I'm sorry, open source is not going to do your client work for you.

**Comment by sharmillamuthu** [comment]
I'm sorry! from the example added in the gif I thought there is a way to add tab.
