### ISSUE TITLE
Passing innerRef to RGL with WidthProvider HOC results in incorrect width

### ISSUE THREAD

**Issue by vldslvmgy** [react-grid-layout/react-grid-layout#1444]
Noticed a bug in 1.2.4 where passing innerRef to the RGL with WidthProvider in place causes the width to shrink and not utilize the full width. Rolling back to 1.2.2 seemed to solve the issue just fine.

Could this be something related to the bug introduced in 1.2.3?

**Comment by jesse-smith-dev** [comment]
> Noticed a bug in 1.2.4 where passing innerRef to the RGL with WidthProvider in place causes the width to shrink and not utilize the full width. Rolling back to 1.2.2 seemed to solve the issue just fine.
> 
> Could this be something related to the bug introduced in 1.2.3?

I'm experiencing the same issue in 1.3.0

**Comment by TrendAlan** [comment]
> > Noticed a bug in 1.2.4 where passing innerRef to the RGL with WidthProvider in place causes the width to shrink and not utilize the full width. Rolling back to 1.2.2 seemed to solve the issue just fine.
> > Could this be something related to the bug introduced in 1.2.3?
> 
> I'm experiencing the same issue in 1.3.0

+1

**Comment by linjjzz** [comment]
+1

**Comment by rnascunha** [comment]
Hi, having same problem here. Anyone?
RGL: 1.4.4
Also reported here #1605
