### ISSUE TITLE
We Can resize only with 1 point, we cant resize to 0.5 or 0.8

### ISSUE THREAD

**Issue by Droid997** [react-grid-layout/react-grid-layout#1445]
Please only submit bugs to this tracker. If you have a feature request, please implement it. This is free software and the author is busy with other projects.

Please use the [CodeSandbox Template](https://codesandbox.io/s/5wy3rz5z1x?module=%2Fsrc%2FShowcaseLayout.js) to demonstrate your bug. It is much easier for us to help you if you do.

**Comment by rishavbharti** [comment]
There is a specific concern regarding the movement behavior observed in the demos, such as the one available at [Basic Example](https://react-grid-layout.github.io/react-grid-layout/examples/1-basic.html). 
During resizing or dragging, the grid item moves by 1 point (width/height ± 1), which results in a slightly larger movement than desired. 
The question arises: What approach should be taken if the requirement is to achieve movements with values less than 1 point? 

@STRML Can you please help here?
