### ISSUE TITLE
Grid item placing outside of container

### ISSUE THREAD

**Issue by TannerHolladay** [react-grid-layout/react-grid-layout#1446]
When I have a short grid item placed above a tall one and move the short one, the tall item moves outside the container.

**Comment by ieltxualganaras** [comment]
have you found any solutions to this? if you use useCSSTransition=false it fixes it for me, but breaks the offsets while draging

**Comment by TannerHolladay** [comment]
@ieltxualganaras I realized after I posted this that the last commit to this repository is a fix to the issue. I'm hoping they will release this fix to npm soon.

**Comment by ieltxualganaras** [comment]
Great! thanks @TannerHolladay

**Comment by ieltxualganaras** [comment]
hey @TannerHolladay have you imported the library styles? that just fix it.. i was being dumb

**Comment by TannerHolladay** [comment]
@ieltxualganaras I imported the react-grid-layout CSS, but not the resizable one since I'm not resizing. Does the resizable one fix it?
