### ISSUE TITLE
Functional component grid items

### ISSUE THREAD

**Issue by bellybailey** [react-grid-layout/react-grid-layout#1447]
Hello, I apologize in advance - I'm still learning react-grid-layout and I'm quite new to react.

I'm trying to create a very basic grid with a few items. I can get it to work when the items are not a separate component. However, when I refactored the items into its own functional component, it stopped working. I tried to use forwardRef but I must be doing it incorrectly (but I'm not getting any error messages). Appreciate any help I can get.

I've created a code sandbox [here](https://codesandbox.io/s/dreamy-ptolemy-6fvlf).

Thanks very much.

**Comment by JamesRamm** [comment]
Hi @bellybailey 
Don't create and pass a ref yourself - RGL will pass a ref to your custom component. I've removed the relevant line for you:
https://codesandbox.io/s/reverent-khayyam-bgzmg

**Comment by tr3ysmith** [comment]
Same issue here

**Comment by jasong689** [comment]
ditto. was not obvious what the issue was until i moved the grid item out of its own component

**Comment by zxhmike** [comment]
I resolved the same issue by adding wrapper divs. See example below. Note that `BarChartCard` and `TextCard` are functional React components. Hope it helps. I tried to do `forwardRef` as well but had no luck.

```
  const layouts = {
    lg: [
      { i: 'card0', x: 0, y: 0, w: 4, h: 2 },
      { i: 'card1', x: 4, y: 0, w: 4, h: 2 },
      { i: 'card2', x: 8, y: 0, w: 4, h: 2 },
    ],
  };

  return (
    <ResponsiveGridLayout
      className="detail-panel"
      layouts={layouts}
      useCSSTransforms={false}
      breakpoints={{ lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0 }}
      cols={{ lg: 12, md: 12, sm: 12, xs: 12, xxs: 12 }}
    >
      <div key="card0">
        <BarChartCard
          title="Local Value"
          record={record}
          subHeader={'As of ' + record.Prior_Knowledge_Date}
          fields={[
            { name: 'Investment_ID', label: 'Investment ID' },
            { name: 'Local_Cost_Value', label: 'Local Cost Value' },
            { name: 'Local_Market_Value', label: 'Local Market Value' },
          ]}
        />
      </div>
      <div key="card1">
        <TextCard
          title="Investment Type"
          text={
            record.Investment_Type
              ? record.Investment_Type
              : 'No Investment Type'
          }
        />
      </div>
      <div key="card2">
        <TextCard
          title="Custodian Account"
          text={
            record.Custodian_Account
              ? record.Custodian_Account
              : 'No Custodian Account'
          }
        />
      </div>
    </ResponsiveGridLayout>
  );
}
```

**Comment by Ducki** [comment]
It baffles me, that there is zero documentation is issues like this. How are people using this in production?

**Comment by STRML** [comment]
Hi. This question has been asked and answered before. If you would like to update the documentation, please open a PR. This is open source, not a commercial product, and I get no benefit out of it and therefore can only get to it rarely.
