### ISSUE TITLE
How to maintain the item aspect ratio?

### ISSUE THREAD

**Issue by andybelous** [react-grid-layout/react-grid-layout#1449]
How to maintain the item aspect ratio?

**Comment by tkornyk** [comment]
> How to maintain the item aspect ratio?Did you find soution for this?

**Comment by andybelous** [comment]
> > How to maintain the item aspect ratio?
> 
> Did you find soution for this?

Unfortunately not.

**Comment by vikas-0** [comment]
I think a possible workaround will be to use resizeHandles='e' instead of 'se'. and with CSS make it look like 'se'. So basically user will be increasing or decreasing width only and height will be calculated on the basis of that with the help of a function on onDragStop callback.

**Comment by andybelous** [comment]
> I think a possible workaround will be to use resizeHandles='e' instead of 'se'. and with CSS make it look like 'se'. So basically user will be increasing or decreasing width only and height will be calculated on the basis of that with the help of a function on onDragStop callback.

DragStop is triggered after drag.

**Comment by vikas-0** [comment]
> > I think a possible workaround will be to use resizeHandles='e' instead of 'se'. and with CSS make it look like 'se'. So basically user will be increasing or decreasing width only and height will be calculated on the basis of that with the help of a function on onDragStop callback.
> 
> DragStop is triggered after drag.

Yeah in this case height will be adjusted once width changes is complete. If you want to have both changes simultaneously perhaps, You have to use ResizeListener.
