### ISSUE TITLE
Drag From Outside RGL Example 15

### ISSUE THREAD

**Issue by vkats** [react-grid-layout/react-grid-layout#1456]
Hello, I implement the method 
onDrop = (layout, layoutItem, _event) => {
        this.setState(prevState => (
            {
            layouts: {
                ...prevState.layouts,
                [prevState.currentBreakpoint]: [
                    ...prevState.layouts[prevState.currentBreakpoint],
                    layoutItem
                ]
            }
            }));
    };
And item always is dropped on the left corner. Please advise what is wrong with my implementation

**Comment by nelsieborja** [comment]
You probably not setting the `i` property of the item correctly.

I am also having an issue with this particular Example - updating the `layouts` state within `onLayoutChange` breaks the dragging functionality:
```
const [layouts, setLayouts] = useState(initialLayouts);
...
<ResponsiveRGL
    onLayoutChange={(_, layouts) => {
        saveToLS(layouts);
        setLayout(layouts);
    }}
    ...
```
