### ISSUE TITLE
it is no longer possible to access the ref of child elements with version 1.2.3 and 1.2.4

### ISSUE THREAD

**Issue by nsrau** [react-grid-layout/react-grid-layout#1457]
as indicated in the title, until version 1.2.2 it was possible to access the ref of child elements. With versions 1.2.3 and 1.2.4,
 it is no longer possible.
Below the link with the sandbox. PS: changing the version of the library you can see that the console has the output.
[CodeSandbox ](https://codesandbox.io/s/gifted-wildflower-qzmhq?file=/src/App.tsx)
![no](https://user-images.githubusercontent.com/8012065/115695532-2fdbf980-a362-11eb-9a35-7b1e4fe3b51b.PNG)
![yes](https://user-images.githubusercontent.com/8012065/115695537-30749000-a362-11eb-9ee7-ad729f7a26a2.PNG)

**Comment by karesztrk** [comment]
Hello @nsrau. You can see the cause of this defect in https://github.com/react-grid-layout/react-grid-layout/issues/1436

**Comment by nsrau** [comment]
I solved it using document.querySelector with data-id
Thanks
