### ISSUE TITLE
onDragStop is not executed when widget is just clicked

### ISSUE THREAD

**Issue by sigalor** [react-grid-layout/react-grid-layout#1459]
In [this demonstration](https://codesandbox.io/s/modest-glitter-zpycd?file=/src/ShowcaseLayout.js) I just added two lines to the grid layout component:

```
onDragStart={() => console.log("start")}
onDragStop={() => console.log("stop")}
```

If I select `react-grid-layout <= 0.16.6` in CodeSandbox, and then simply click at any widget without dragging it, both `start` and `stop` appear in the console. When a newer version is used though, only `start` appears, which is quite problematic when trying to track which widget is currently being dragged.

Related to #1411, but I do want `onDragStart` to fire as soon as the mouse is pressed down on a widget.

**Comment by DavidHenri008** [comment]
Could this be re-opened. I am experiencing the same issue...
