### ISSUE TITLE
当我使用  Children.map的时 i属性被修改掉

### ISSUE THREAD

**Issue by huixu123** [react-grid-layout/react-grid-layout#1460]
{ i: '1', x: 1, y: 0, w: 8, h: 10, c: {} },
    { i: '2', x: 1, y: 12, w: 8, h: 10, c: {} },
    { i: '3', x: 1, y: 24, w: 8, h: 10, c: {} },
    { i: '4', x: 1, y: 36, w: 8, h: 10, c: {} },
    { i: '5', x: 10, y: 0, w: 18, h: 23, c: {} },
    { i: '6', x: 28, y: 24, w: 18, h: 23, c: {} },
    { i: '7', x: 10, y: 24, w: 18, h: 23, c: {} },
    { i: '8', x: 28, y: 0, w: 18, h: 23, c: {} },
` 
          {Children.map(props.children, (item: Object, idx: number) => {
            return (
              <div key={props.layout[idx].i}>
                {/* <Card border={<Border1 />} /> */}
              </div>
            )
          })}
`

这时候通过react开发插件查看 发现 i变成了 ‘1/.0’ 于是导致了i 和key无法匹配

**Comment by thfeng** [comment]
I am suffering from the same issues. You can try to use children.map instead of React.Children.map
