### ISSUE TITLE
`cols` prop having no effect on layout

### ISSUE THREAD

**Issue by clinzy25** [react-grid-layout/react-grid-layout#1464]
I am trying to set up a grid with only 7 columns, and one row: They are generated dynamically like so:

```
import styled from 'styled-components';
import { useTableContext } from '../reducers-contexts/table_context';
import { DayColumn } from './DayColumn';
import moment from 'moment';
import GridLayout from 'react-grid-layout';

export const TasksContainer = () => {
  const { dayColumns, startTime } = useTableContext();

  const layout = [];

  return (
    <Wrapper>
      {dayColumns.map((day, index) => {
        layout.push({
          i: index.toString(),
          x: index,
          y: 0,
          w: 1,
          h: 1,
        });
        return (
          <GridLayout
            className='layout'
            layout={layout}
            cols={7}
          >
            <DayColumn
              key={index.toString()}
              date={moment(startTime + ((index + 1) * 86400000 - 1)).format(
                'l'
              )}
              day={day.id}
            />
          </GridLayout>
        );
      })}
    </Wrapper>
  );
};

const Wrapper = styled.section`
  width: 100%;
  height: 100%;
`;
```
The `cols={7}` attribute is having no effect and is only deisplaying one column like so:
![Screenshot 2021-05-04 094057](https://user-images.githubusercontent.com/74991878/117012377-e2924d00-acbc-11eb-9d58-318ab0dbc1fe.png)

### What I tried:
- Creating the layout with the `data-grid` prop on the DayColumn
- Changing the width of the day column to less than the width of the container, hoping they were just wrapping
- Changing the width of the `Wrapper` at the bottom to less than 100%, hoping they were just wrapping

**Comment by STRML** [comment]
You're generating 7 grid layouts.

**Comment by clinzy25** [comment]
@STRML  How so? the prop is `cols`, doesn't that imply your're controlling columns?

**Comment by STRML** [comment]
You've rendered 7 grids, not 1 grid with 7 items.
