### ISSUE TITLE
Resize Handle - Custom component for ResizeHandle

### ISSUE THREAD

**Issue by dinmaduraimani** [react-grid-layout/react-grid-layout#1465]
I am trying to customize ResizeHandle icon for my widget using "resizeHandle" props

```
<ReactGridLayout
        layout={layout}
        cols={12}
        rowHeight={20}
        width={1360}
        onLayoutChange={onLayoutChange}
        resizeHandle={<ResizeHandleIcon />}
      >
      ```
![image](https://user-images.githubusercontent.com/45810749/117137202-fb872500-adc6-11eb-95f9-431c59be482e.png)

Problem:
* Custom icon displayed in the widget but resize event is not triggered. How Resize event logic handled for custom component?
* Do align SouthEast direction do I need to add css styles for custom component will it not taken care as part of resizeHandles array props?
* Will this custom resizeHandle props not available for ResponsiveGridLayout?

**Comment by dinmaduraimani** [comment]
Any update on this?

**Comment by MarvinAmador7** [comment]
I've been playing around with the resizeHandle prop but no luck so far, I've been able to render the component but when I try to resize it the whole child component is dragged but not resized.

```jsx
import * as React from 'react'
import { FiArrowDownRight } from 'react-icons/fi'
import { forwardRef, Box } from '@chakra-ui/react'

export const ResizableHandler = forwardRef((props, ref) => {
  return (
    <Box
      ref={ref}
      position="absolute"
      bottom={0}
      right={0}
      width="24px"
      height="24px"
      {...props}
    >
      <FiArrowDownRight color="white" size="24" />
    </Box>
  )
})

<GridLayout
      layout={defaultLayout}
      cols={12}
      rowHeight={30}
      width={1200}
      resizeHandle={<ResizableHandler />}
    >
      <SimpleContainer>
    </GridLayout>
```

**Comment by STRML** [comment]
This is the same as the `handle` prop in https://github.com/react-grid-layout/react-resizable. It needs to forward refs down to an actual DOM node, as it is invoked in this way:

https://github.com/react-grid-layout/react-resizable/blob/b1ed42852d6608e65f9ae486f42a82ea8eee8bb1/lib/Resizable.js#L156-L165

**Comment by shaurya-singh2** [comment]
I have used resizeHandle prop for custom handle in ResponsiveGridLayout. I am able to resize using it but it also drags the element along with resizing.
I tried using an onClick and stopPropagation on the custom handle but its not working. @STRML can you give me some pointer on how to stop dragging.

```
<ResponsiveGridLayout
      layouts={layouts}
      cols={cols}
      breakpoints={{ lg: 980, md: 481, sm: 0 }}
      rowHeight={rowHeight}
      onLayoutChange={(layout, layouts) => handleLayoutChange(layout, layouts)}
      compactType="vertical"
      margin={[10, 10]}
      resizeHandles={['s', 'e']}
      resizeHandle={
          // ResizeHandle is a react component
          ResizeHandle
      }
    >
```
ResizeHandle.jsx
```
export default function ResizeHandle(props) {
  return (
    <div
      onClick={e => {
        e.stopPropagation()
      }}
    ></div>
  )
}
```
This is stripped version I have used some styling to show handle in correct place on the basis of axis.

**Comment by STRML** [comment]
You're not passing the prop correctly. You're passing a component constructor when you should be passing a component. 

```jsx
<ResponsiveGridLayout
      // ...
      resizeHandle={<ResizeHandle />}
    >
```

This is in the documentation.

**Comment by STRML** [comment]
See updated docs on resize handles at https://github.com/react-grid-layout/react-resizable#resize-handle.

**Comment by shaurya-singh2** [comment]
I tried changing it to component and forwarding the ref but now resize is not working only dragging works.
```
<ResponsiveGridLayout
      // ...
      resizeHandle={<ResizeHandle />}
    >
```
ResizeHandle.jsx
```
const ResizeHandle = React.forwardRef((props, ref) => {
  return (
    <div
      onClick={e => {
        e.stopPropagation()
      }}
      ref={ref}
    ></div>
  )
})

export default ResizeHandle
```

**Comment by shaurya-singh2** [comment]
In my previous approach adding `className={react-resizable-handle react-resizable-handle-${resizeHandle}}` to the div fixes the issue as provided in https://github.com/react-grid-layout/react-resizable/issues/102#issuecomment-510314763
```
export default function ResizeHandle(resizeHandle) {
  return (
    <div
      className={`react-resizable-handle react-resizable-handle-${resizeHandle}`}
      onClick={e => {
        e.stopPropagation()
      }}
    ></div>
  )
}
```


But this adds the arrows

**Comment by STRML** [comment]
Thanks. I've updated the docs. You need to add `{...props}` to the `<div />` as here. 

https://github.com/react-grid-layout/react-resizable/blob/54d2a4bd62c6f33fef1011dec6c3fe0012cd91de/examples/ExampleLayout.js#L7-L15

**Comment by shaurya-singh2** [comment]
Adding {...props} enables the resizing but it drags along as well.

If I add `className={react-resizable-handle react-resizable-handle-se}` then it works correctly but now I dont have handleAxis in the props to customComponent.
Props contain only onMouseEnd, onMouseUp, onTouchEnd.

How can i get handleAxis in the custom component.

**Comment by mdsadiq** [comment]
any progress ?

**Comment by alon24** [comment]
I do this     
```
const MyHandle = React.forwardRef<HTMLInputElement, { handleAxis?: string }>((props, ref) => {
        const { handleAxis, ...restProps } = props;
        return (
            < div (whatever...)
                ref={ref}
                className={`resizeHandle handle-${handleAxis}`}
                {...restProps}
            />
        );
    });
```

```
 <ReactGridLayout
                    // autoSize={true}
                    onLayoutChange={onLayoutChange}
                    // onBreakpointChange={onBreakpointChange}
                    className="layout"
                    breakpoints={{ lg: 1200, md: 996, sm: 768, xs: 480, xxs: 100 }}
                    cols={{ lg: 4, md: 4, sm: 4, xs: 4, xxs: 4 }}
                    rowHeight={359}
                    resizeHandle={<MyHandle />}
                    draggableCancel={".grid-no-drag"}
                    compactType={"horizontal"}
                    isBounded={true}
                >
```
