### ISSUE TITLE
Setting the attribute `data-grid` doesn't work on Responsive

### ISSUE THREAD

**Issue by mlisthenewcool** [react-grid-layout/react-grid-layout#1475]
The Responsive class can only be set with attribute `layouts`, setting the attribute `data-grid` on children has no effect.

Demo : https://codesandbox.io/s/react-grid-layout-setting-layouts-on-children-05p4o?file=/src/MyReactGridLayout.tsx

**Comment by STRML** [comment]
That's correct, because it would not be possible to identify which layout the `data-grid` property is for. This is by design.
