### ISSUE TITLE
onLayoutChange trigger twice

### ISSUE THREAD

**Issue by yangguansen** [react-grid-layout/react-grid-layout#1480]
** version:  **
1.2.5

** platform: **
Mac google 

** describe: **
When moving the item, drag the item under the placeholder, then release the item, the item will be adsorbed to the placeholder, at this time, onLayoutChange will trigger twice

** codeSandBox **
https://codesandbox.io/s/silly-wozniak-rttgy?file=/src/ShowcaseLayout.js:612-626

** video **
http://jxqdh.91sam.com/bug.mp4

**Comment by GuichiZhao** [comment]
save issue
I need a reliable way to detect layout change in order to save out the new layout to server
What is more, the save button is disabled when no layout change

The random layout change really break the our process

**Comment by beautyfree** [comment]
i have same issue
