### ISSUE TITLE
Grids reszinng are not getting triggered on gridlayout width change

### ISSUE THREAD

**Issue by chandanonline4u** [react-grid-layout/react-grid-layout#1482]
I have a view and it has two panels one for grids and the other is view related filters panel. Be default side panel is collapsed so the grids panel wrapper gets 100% of the width and initially, grids are appearing fine but when you toggle the filter sidebar and grid wrapper width adjust the size of the grid as per wrapper, it still works as per initial wrapper width. I have defined conditional columns counts when the filter panel is on. I have tried responsive layout as well but it is not working as excepted.

Do you have any example of how responsive layout will work when wrapper width will decrease.

**Comment by chandanonline4u** [comment]
The above case has started working on react-sizeme so closing the issue. Thanks

**Comment by zhaoqi-nb** [comment]
哈喽，我也遇到这个问题了，请问怎么用react-sizeme解决呢
