### ISSUE TITLE
Prevent resizing in one direction

### ISSUE THREAD

**Issue by rogerfar** [react-grid-layout/react-grid-layout#1484]
We have the `isResizable` option, but for a specific use case I want to use to limit resizing to only horizontal.

Is it possible to add 2 more flags, something like `isResizableHorizontal` and `isResizableVerical` ?

Or maybe make `isResizable` accept `true`, `false`, `'ew'` or `'ns'`?

**Comment by STRML** [comment]
Set the `maxH` and `minH` equal to the current height of the element, and it won't be resizable vertically.

**Comment by rogerfar** [comment]
Yeah that makes sense, thanks!
