### ISSUE TITLE
Not using `key` property on custom components

### ISSUE THREAD

**Issue by mworzala** [react-grid-layout/react-grid-layout#1488]
The key property seems to only work on built in JSX tags, and not custom components. 

I have created a minimal example of what I mean in [CodeSandbox](https://codesandbox.io/s/mystifying-faraday-jcofh?file=/src/ShowcaseLayout.js).

**Comment by wulforr** [comment]
This issue is known for a while not sure whats the reason though, A simple workaround is to wrap your custom component with a div and use key on the div

**Comment by m93a** [comment]
I think that the reason why it won't work is simply that the `key` property is only meant for React and it shouldn't be expected in `this.props`. If react-grid-layout used a `data-key` property, it would at least be obvious that it only works on HTMLElements and not custom ones. This way I spent over an hour trying to figure out why it wasn't working.
