### ISSUE TITLE
Custom resize handle not working

### ISSUE THREAD

**Issue by mir3z** [react-grid-layout/react-grid-layout#1489]
Affected version: 1.2.5
I've created custom resize handle as described in the docs but it didn't work. Instead of resizing it just moves the box around.

Downgrading to 1.2.4 makes the box is being resized and moved at the same time.

https://codesandbox.io/s/confident-goodall-hjqmm?file=/src/ShowcaseLayout.js

**Comment by STRML** [comment]
See https://codesandbox.io/s/friendly-haibt-wg27w?file=/src/ShowcaseLayout.js.

In short, there are two issues:

1. The child must have the class `.react-resizable-handle` or it will not be ignored by Draggable. I will add this to the docs.
2. `React-resizable <= 3.0.1` did not pass `handleAxis` as a prop to custom components. It does in `3.0.2` and so you can add additional classes/styles as you wish depending on that value.

**Comment by STRML** [comment]
See also https://github.com/react-grid-layout/react-grid-layout/commit/efb22648036ecc534083089fe5a9a27b30758329
