### ISSUE TITLE
Question about responsive layout

### ISSUE THREAD

**Issue by creotiv** [react-grid-layout/react-grid-layout#1493]
I have few blocks which i want to fill the whole screen, so to be able to automatically stretch them by width and height based on some percentage of the screen.

Is it possible?

**Comment by wulforr** [comment]
I am not sure what you want but if you want a block to be 70% of screen then you can make a grid layout with number of columns to 10 this would make it easy to deal with percentages and give the block width of 7 columns

**Comment by creotiv** [comment]
I want the hight of the grid layout to be 100% of the parent element, while
all blocks in  layout resized to fit in.

Kindly yours,
Andrey Nikishaev

Areas         ML/DS/CV/Soft Dev/BizDev/Growth Hacking/Customer Rel/IT
LinkedIn      http://ua.linkedin.com/in/creotiv
GitHub        http://github.com/creotiv
Slideshare  https://www.slideshare.net/anikishaev/
Skype         creotiv.in.ua
Mobile        +380632410666

**Comment by wulforr** [comment]
In rgl height is calculated as (rowheight *  numberOfRows) + (numberOfRows - 1)* marginY
so you have height but you need numberOfRows so you can easily calculate it and accordingly pass the layout.

**Comment by roman-myshchyshyn** [comment]
@wulforr is there any way to remove `(numberOfRows - 1)* marginY` part from the widget height, this part do not make any sense if I need a precise height?

**Comment by junhaolai1996** [comment]
@creotiv Hello I came across your post and would like to do something similar. Was wondering if you have figured something out.

**Comment by creotiv** [comment]
@junhaolai1996 i switched to the react-mosaic-component, it works almost without bugs. The only problems that i had is version compatability
