### ISSUE TITLE
Feature: grow/scroll horizontally instead of default vertical

### ISSUE THREAD

**Issue by nicolaspasqualis** [react-grid-layout/react-grid-layout#1495]
By default I can see that the grid container grows in vertical direction with a fixed width when arranging nodes, is there an option to 
make it grow horizontally and lock the grid's height instead? maybe achievable with css?
Basically having a maximum number of rows instead of cols

Thanks!

**Comment by drkmai** [comment]
Some weeks ago I was wondering if that's possible. I hope anyone can give you some insight about it.

**Comment by nicolaspasqualis** [comment]
Updating the title because it seems not possible curently and could make for a great feature.

**Comment by wyhinton** [comment]
+1 for this feature
