### ISSUE TITLE
Question:  is that possible to drop and element ON an other element ?

### ISSUE THREAD

**Issue by Aarbel** [react-grid-layout/react-grid-layout#1504]
I'm developping a files / folders tree architecture. I would like to provide files dropping in folders feature.

react-grid-layout would be perfect for grid view presentation, is there just any way to drop an element on an other element ? 

Example: 
![image](https://user-images.githubusercontent.com/25119847/123513136-b3300900-d68b-11eb-8ea8-d501f126d294.png)
https://dribbble.com/shots/7555134--File-Management-Exploration?utm_source=Clipboard_Shot&utm_campaign=Kevinduk&utm_content=%F0%9F%93%82%20File%20Management%20Exploration&utm_medium=Social_Share

**Comment by wyhinton** [comment]
Also would like to know this

**Comment by wyhinton** [comment]
From what I gather in #334 it's not possible, I think you'll need to provide another set of draggable droppable wrappers via a library like react-beautiful-dnd.

**Comment by Aarbel** [comment]
It works with https://github.com/clauderic/dnd-kit

**Comment by wyhinton** [comment]
@Aarbel so you basically end up using their drag/drop api on top of the grid-layout components? It does seem like it could be trouble to have two libraries attempting to drag something at the same time.

**Comment by Aarbel** [comment]
I just use dnd kit 

https://5fc05e08a4a65d0021ae0bf2-cbfrwoklyt.chromatic.com/?path=/story/presets-sortable-grid--basic-setup

**Comment by Aarbel** [comment]
But the api isn't as strong as this one. I think having so answers here would be great

**Comment by wyhinton** [comment]
Oh so you switched over to that library entirely?

**Comment by Aarbel** [comment]
I switched for my use case yes, but react-grid-layout has a stronger api to create layouts like dashboards. 
React beautifull dnd is a mess, i highly recommend dnd-kit
