### ISSUE TITLE
Why the north and west resizable handles works in reverse?

### ISSUE THREAD

**Issue by qwe12e** [react-grid-layout/react-grid-layout#1519]
In the float mode I'm expecting to resize in all direction but when i try to resize left it grows or shrinks from the right side. Same with the north side. I didn't find anything about this in the docs. Should i try to implement custom handles?

**Comment by TanYJie** [comment]
+1

**Comment by ddolcimascolo** [comment]
Yeah, this surprised me when I first started to use RGL too :) I ended up keeping the default south east handle only, like they do in Kibana

**Comment by alon24** [comment]
+1 any update?

**Comment by DominikScholz** [comment]
+1

**Comment by DominikScholz** [comment]
Interestingly, I think this should be actually solved by this PR https://github.com/react-grid-layout/react-resizable/pull/136.

**Comment by dsalgador** [comment]
Not Stale. The same as @[qwe12e](https://github.com/qwe12e) is happening to me, no resize to left or north directions as expected

**Comment by AntonioGally** [comment]
Same problem here, any solution?

**Comment by Ichicoro** [comment]
Any solution?

**Comment by Foraminiferatrv** [comment]
Why is it closed? Is there a solution?

**Comment by timoisalive** [comment]
Looking for solution too... How does it work on the demo page (https://react-grid-layout.github.io/react-grid-layout/examples/0-showcase.html)?

**Comment by sid2u** [comment]
> Looking for solution too... How does it work on the demo page (https://react-grid-layout.github.io/react-grid-layout/examples/0-showcase.html)?

@timoisalive , I believe this was fixed in v1.4.0 through [this PR](https://github.com/react-grid-layout/react-grid-layout/pull/1917)

**Comment by timoisalive** [comment]
> @timoisalive , I believe this was fixed in v1.4.0 through [this PR](https://github.com/react-grid-layout/react-grid-layout/pull/1917)

Indeed it seems to be, thank you @sid2u! 🥳
