### ISSUE TITLE
Item is offset on drag start when other elements are present

### ISSUE THREAD

**Issue by rbarkhouse** [react-grid-layout/react-grid-layout#1520]
Stackblitz example: https://stackblitz.com/edit/react-lcwmxf

When I have other sibling elements next to my react-grid-layout, the draggable items are offset as soon as I click to start dragging.  In the example above, I have a div containing a bunch of buttons, and a ResponsiveGridLayout.  If you remove all of the buttons you'll see the drag works fine, the item doesn't shift on click.  The more buttons that are present, the bigger the gap when you start dragging.

What could be causing this?

**Comment by rbarkhouse** [comment]
I answered my own question after searching through issues a bit more.  I had forgotten to include the necessary CSS files mentioned in the Installation section.

https://github.com/react-grid-layout/react-grid-layout#installation

**Comment by esilva-fuze** [comment]
I'm experiencing something similar to this, in which when I click on an item (without moving my mouse) it instantly goes down-right. The further away I'm from the [0, 0] the worse it gets. Consequently, the item on [0, 0] does not trigger this behaviour (but it does move away from the cursor once I start dragging it around). 

I do have those CSS's imported, is there anything else that could explain this issue?

**Comment by mfnash** [comment]
> I'm experiencing something similar to this, in which when I click on an item (without moving my mouse) it instantly goes down-right. The further away I'm from the [0, 0] the worse it gets. Consequently, the item on [0, 0] does not trigger this behaviour (but it does move away from the cursor once I start dragging it around).
> 
> I do have those CSS's imported, is there anything else that could explain this issue?

same problem here. Is there any solution ?
