### ISSUE TITLE
Swap between 2 items

### ISSUE THREAD

**Issue by adamsense** [react-grid-layout/react-grid-layout#1525]
Hi,
Check this:
![drag item](https://user-images.githubusercontent.com/49365848/127731831-5d9d4ff4-c76d-4363-96c1-96fe39afc2f9.gif)

1. I want that Item "c" will move to the location of the draggable Item "b". Let say that all of the elements have the same size. Or I don't mind that they will be resized, just so they will fit the space of the current draggable item (some sort of a "Swap" feature).

2. How it is possible that Item "c" moved outside of the grid boundary? (I set autosize to 'false')

**Comment by jxzhou-anylink** [comment]
1. The attribute "compactType" default value is "vertical", change it to "horizontal".
2. Set attribute "isBounded" to "true"

**Comment by timurridjanovic** [comment]
@adamsense were you ever able to get this right?
