### ISSUE TITLE
Responsive grid layout doesn't respect layouts prop

### ISSUE THREAD

**Issue by quirinpa** [react-grid-layout/react-grid-layout#1528]
I'm trying to use react-grid-layout and save / load from localstorage, but in my case the some of the items in the layouts are dynamic and are generated from a prop "categories". It seems like the layouts that are returned by onLayoutChange do not correspond to the layouts i have as state. Here is the code:

```jsx
import {useEffect, useState, useMemo} from 'react'
import {useData} from '/lib/effects.js'
import {ErrorC, Layout} from '/components/common.js'
import {Loading} from "/components/Loading.js";
import user from '/lib/user.js'
import { Responsive, WidthProvider } from 'react-grid-layout'
import { Card, Col, Row } from 'react-bootstrap'
import Image from 'next/image'

const ResponsiveGridLayout = WidthProvider(Responsive);

function getFromLS(defaultValue) {
  let ret = defaultValue;

  if (typeof window === 'undefined')
    return ret;

  try {
    let val = JSON.parse(localStorage.getItem("homeLayouts"));
    if (val) {
        console.log("getFromLS", val);
      ret = val;
    }
  } catch (e) {
  }

  // console.log('getFromLS', defaultValue, ret);

  return ret;
}

function ErrorCard(props) {
    const { error } = props;

    return (
        <Card className="bg-danger text-white fh">
            <Card.Body className="d-flex align-items-center justify-content-center">
                { error.message }
            </Card.Body>
        </Card>
    );
}

function NumberCard(props) {
  const { className, number = "-", label } = props;

  return (
    <Card className={`${className} text-white text-center fh`}>
      <Card.Body className="d-flex align-items-center justify-content-center">
        <div>
          <div className="display-4">{number}</div>
          <div>{label}</div>
        </div>
      </Card.Body>
    </Card>
  );
}

function ProvidersNumberCard(props) {
  const { data, error } = useData('/api/getProvidersN');

  // if (error)
  //   return <ErrorCard error={error} />;

  if (error || !data)
    return <NumberCard className="bg-primary" label="Data Providers" />;

  const { providersN } = data;

  return <NumberCard className="bg-primary" number={providersN} label="Data Providers" />
}

function OfferingsNumberCard(props) {
  const { data, error } = useData('/api/getOfferingsN');

  // if (error)
  //   return <ErrorCard error={error} />;

  if (error || !data)
    return <NumberCard className="bg-secondary" label="Offerings Available" />;

  const { offeringsN } = data;

  return <NumberCard className="bg-secondary" number={offeringsN} label="Offerings Available" />;
}

function CategoryCardPure(props) {
  const { name, number = '-' } = props;

  return (
    <Card className="fh">
        <Card.Body className="d-flex align-items-center justify-content-between">
            { name }
            <span className="ml-3 h3 text-primary">{ number }</span>
        </Card.Body>
    </Card>
  );
}

function CategoryCard(props) {
  const { name } = props;
  const { data, error } = useData(`/api/getCategoryOfferingsN?category=${name}`);

  // if (error)
  //   return <ErrorCard error={error} />;

  if (error || !data)
    return <CategoryCardPure name={name} />;

  const { offeringsN } = data;

  return <CategoryCardPure name={name} number={offeringsN} />;
}

function HomePure(props) {
  const {
    categories = []
  } = props;

  const layoutA = {
    i: 'a', w: 5, h: 4, isResizable: false
  };

  const layoutB = {
    i: 'b', w: 6, h: 2, isResizable: false,
  };

  const layoutC = {
    i: 'c', w: 3, h: 2, isResizable: false,
  };

  const layoutD = {
    i: 'd', w: 3, h: 2, isResizable: false,
  };

  function getCategoriesLayout(y, ncols) {
    let res = [];
    let i, x;

    for (
      i = 0, x = 0;
      i < categories.length;
      i++
    ) {
      res.push({
        i: 'category' + i, w: 2, h: 1, isResizable: false,
        x, y
      });

      x += 2;
      if (x + 2 > ncols) {
        x = 0;
        y ++;
      }
    }

    return res;
  }

  const layouts = useMemo(() => ({
    lg: [
      { ...layoutA, x: 0, y: 0 },
      { ...layoutB, x: 5, y: 0 },
      { ...layoutC, x: 5, y: 2 },
      { ...layoutD, x: 8, y: 2 },
      ...getCategoriesLayout(4, 11),
    ],
    md: [
      { ...layoutA, x: 0, y: 0, w: 4 },
      { ...layoutB, x: 4, y: 0 },
      { ...layoutC, x: 4, y: 2 },
      { ...layoutD, x: 7, y: 2 },
      ...getCategoriesLayout(4, 10),
    ],
    sm: [
      { ...layoutA, x: 0, y: 0, w: 6 },
      { ...layoutB, x: 0, y: 4 },
      { ...layoutC, x: 0, y: 6 },
      { ...layoutD, x: 3, y: 6 },
      ...getCategoriesLayout(8, 6),
    ],
    xs: [
      { ...layoutA, x: 0, y: 0 },
      { ...layoutB, x: 0, y: 4 },
      { ...layoutC, x: 0, y: 6, w: 2 },
      { ...layoutD, x: 2, y: 6, w: 2 },
      ...getCategoriesLayout(8, 4),
    ],
  }), [categories]);;

  // console.log("RENDER", layouts);

  const [ _layouts, setLayouts ] = useState(getFromLS(layouts));

  useEffect(() => {
    // setLayouts(layouts);
    setLayouts(getFromLS(layouts));
  }, [layouts]);

  useEffect(() => {
    localStorage.setItem("homeLayouts", JSON.stringify(_layouts));
  }, [_layouts]);

  console.log("RENDER", layouts, _layouts);

  function onLayoutChange(layout, layouts) {
    setLayouts(layouts);
    console.log("onChange", layouts, categories);
    // if (categories.length)
    //   localStorage.setItem("homeLayouts", JSON.stringify(layouts));
  }

  const categoryEl = categories.map((category, idx) => (
      <div key={"category" + idx}>
          <CategoryCard name={category.category} />
      </div>
  ));

  return (<Layout>
    <div className="px-5">
      <ResponsiveGridLayout className="layout"
        breakpoints={{lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0}}
        cols={{lg: 11, md: 10, sm: 6, xs: 4, xxs: 3}}
        layouts={_layouts}
        rowHeight={100}
        onLayoutChange={onLayoutChange}
      >
        <Card key="a" className="welcome-card d-flex align-items-center justify-content-center">
          <Image src="/img/Web-ri_sep.png" layout="fill" objectFit="contain" className="p-3" />
        </Card>

        <Card key="b">
          <Card.Body>
            <Row className="py-3">
              <Col>
                <small className="text-muted">
                  USER
                </small>
                <h4>
                  { user.name }
                </h4>
              </Col>
              <Col>
                <small className="text-muted">
                  COMPANY
                </small>
                <h4>
                  { user.company }
                </h4>
              </Col>
            </Row>
            <Row className="py-3 bg-light">
              <Col>
                <small className="text-muted">
                  ROLE
                </small>
                <h4>
                  Data Provider
                </h4>
              </Col>
              <Col>
                <small className="text-muted">
                  DATA PROVIDER ID
                </small>
                <h4>
                  { user.providerId }
                </h4>
              </Col>
            </Row>
          </Card.Body>
        </Card>

        <div key="c">
          <ProvidersNumberCard />
        </div>

        <div key="d">
          <OfferingsNumberCard />
        </div>

        { categoryEl }
      </ResponsiveGridLayout>
    </div>
  </Layout>);
}

export default function Home() {
  const { data, error } = useData('/api/');

  if (error)
    return <ErrorC error={error} />;

  if (!data)
    return <HomePure />;

  return <HomePure { ...data } />;
}
```

Here is a minimal example using codesandbox:
https://codesandbox.io/s/react-bootstrap-demo-forked-52u0r?file=/src/index.js

Can you please help me out? Thanks.

**Comment by uthbees** [comment]
This seems to be a common problem - I have the same issue that there is no way to programmatically alter the layout, also see #1526, #1529.

**Comment by STRML** [comment]
I'm sorry but it's going to be very difficult to figure out what the bug is with such a long, non-runnable code example. Please reduce this to the minimum form possible and post it on codesandbox so someone can diagnose it, or perhaps you will be able to diagnose it yourself at that size.

**Comment by uthbees** [comment]
I've been working on a codesandbox [here](https://codesandbox.io/s/distracted-banzai-upfbb?file=/src/App.js), but I suspect that this error is the fault of the user of the library, not the library itself, as the layout prop sometimes works and sometimes doesn't, and because you actually have a functional example[here](https://react-grid-layout.github.io/react-grid-layout/examples/6-dynamic-add-remove.html).

I'll give an update once I find the time to look through the source for the example.

**Comment by uthbees** [comment]
After some experimentation, I found a way to get my code to work. I can't say for sure that @quirinpa, @mborecki, and @ishak-lm (from the mentioned issues) aren't experiencing a different issue, but I'm guessing we're all having essentially the same problem.

It seems like the issue has something to do with how states work in react, but I'm not knowledgeable enough about that to be able to pinpoint what's going on here. You can see my full testing code [here](https://codesandbox.io/s/distracted-banzai-upfbb?file=/src/App.js), but the important part is this:

```javascript
//This is the method I was using before, that doesn't work
let newLayouts = { ...layouts };
newLayouts.desktop.push(newViewDesktop);
newLayouts.mobile.push(newViewMobile);
setLayouts(newLayouts);
```
```javascript
//This method does work
setLayouts({
  desktop: [...layouts.desktop, newViewDesktop],
  mobile: [...layouts.mobile, newViewMobile]
});
```

Conclusion: while there may be room for improvement to make this more intuitive depending on what the problem actually is, my issue has been solved, and I'm guessing the others' issues can be solved on their side as well.

**Comment by sticky-web** [comment]
> After some experimentation, I found a way to get my code to work. I can't say for sure that @quirinpa, @mborecki, and @ishak-lm (from the mentioned issues) aren't experiencing a different issue, but I'm guessing we're all having essentially the same problem.
> 
> It seems like the issue has something to do with how states work in react, but I'm not knowledgeable enough about that to be able to pinpoint what's going on here. You can see my full testing code [here](https://codesandbox.io/s/distracted-banzai-upfbb?file=/src/App.js), but the important part is this:
> 
> ```js
> //This is the method I was using before, that doesn't work
> let newLayouts = { ...layouts };
> newLayouts.desktop.push(newViewDesktop);
> newLayouts.mobile.push(newViewMobile);
> setLayouts(newLayouts);
> ```
> 
> ```js
> //This method does work
> setLayouts({
>   desktop: [...layouts.desktop, newViewDesktop],
>   mobile: [...layouts.mobile, newViewMobile]
> });
> ```
> 
> Conclusion: while there may be room for improvement to make this more intuitive depending on what the problem actually is, my issue has been solved, and I'm guessing the others' issues can be solved on their side as well.

Thank you, I was running into a similar issue (layout items would reset to { w: 1, h: 1, static:false}) when providing the layout from an Akita store. Setting a local useState in the component rendering the grid, populating it from the store and then proving the layout from the local state fixed it.

**Comment by quirinpa** [comment]
First of all, thanks for your support. I don't think I am changing immutable state in that way @uthbees.. And I've logged the state and it seems correct. It really seems like the layouts prop doesn't update ResponsiveGridLayout's internal state somehow.. I agree @STRML that a minimal working example would be ideal. I will prepare one as soon as I can.

**Comment by quirinpa** [comment]
I'm having some trouble getting a minimal example to work. here's what i got so far:
https://codesandbox.io/s/react-bootstrap-demo-forked-52u0r?file=/src/App.js

**Comment by uthbees** [comment]
I've been looking at it for a while now, but I don't see any issue. It all seems to be working perfectly to me. That said, I'm sure you're seeing some sort of problem, so you may want to strip down the example more and/or elaborate on the specific issue more clearly.

**Comment by quirinpa** [comment]
I am logging _layouts state which at a certain point has 21 items for each breakpoint. When it does, the following "onChange" log occurs and does not reflect the value previously logged (the value of the state).

**Comment by ggbond2077** [comment]
i add a new item {w:5, h:5, ...}  to layout,  and  i'm sure the 'layout' props is update, but 'onLayoutChange' callback give a default item {w:1, h: 1, ...}. when i change to use 'data-grid' , it work fine.

here is the sandbox:  'onLayoutChange' callback layout not equal to 'props' layout;
https://codesandbox.io/s/react-bootstrap-demo-forked-czle3e?file=/src/App.js:1382-1388

**Comment by kauly** [comment]
Thank you @ggbond2077 , I was almost looking for another library. To clarify the prop `layouts` of the `ResponsiveGridLayout` must be equal to the current breakpoint and layout. Like so:

ts```
type TGridData = {
	layout: Layout[];
	cols: number;
	breakpoint: string;
};
const [gridData, setGridData] = useState<TGridData>(initialGridData);
<ResponsiveGridLayout layouts={{ [gridData.breakpoint]: gridData.layout }} />
```
