### ISSUE TITLE
Can't resize component

### ISSUE THREAD

**Issue by pedrobzz** [react-grid-layout/react-grid-layout#1532]
Ok, this might be a dumb question but i dont know how to make the components resizable, i've been trying for maybe 1 and a half hours without success. I tried to copy the same code from the readme and from the example and it works everything but resize. I've already tried to set `isResizable` to true, but no success

I'm using macOS with NextJS and Typescript, with react-grid-layout ^1.2.4

**Comment by akazwz** [comment]
U can import this :
`import 'react-grid-layout/css/styles.css'; 
import 'react-resizable/css/styles.css';`
It works for me,hope this can help u.

**Comment by akazwz** [comment]
> Ok, this might be a dumb question but i dont know how to make the components resizable, i've been trying for maybe 1 and a half hours without success. I tried to copy the same code from the readme and from the example and it works everything but resize. I've already tried to set `isResizable` to true, but no success
> 
> I'm using macOS with NextJS and Typescript, with react-grid-layout ^1.2.4



> Ok, this might be a dumb question but i dont know how to make the components resizable, i've been trying for maybe 1 and a half hours without success. I tried to copy the same code from the readme and from the example and it works everything but resize. I've already tried to set `isResizable` to true, but no success
> 
> I'm using macOS with NextJS and Typescript, with react-grid-layout ^1.2.4

U can import this :
import 'react-grid-layout/css/styles.css'; 
import 'react-resizable/css/styles.css';
It works for me,hope this can help u.

**Comment by akazwz** [comment]
U can import this :
import 'react-grid-layout/css/styles.css'; import 'react-resizable/css/styles.css';
It works for me,hope this can help u.

> Ok, this might be a dumb question but i dont know how to make the components resizable, i've been trying for maybe 1 and a half hours without success. I tried to copy the same code from the readme and from the example and it works everything but resize. I've already tried to set `isResizable` to true, but no success
> 
> I'm using macOS with NextJS and Typescript, with react-grid-layout ^1.2.4

U can import this :
`import 'react-grid-layout/css/styles.css'; `
`import 'react-resizable/css/styles.css';`
It works for me,hope this can help u.

**Comment by akazwz** [comment]
U can import this :
`import 'react-grid-layout/css/styles.css'; `
`import 'react-resizable/css/styles.css';`
It works for me,hope this can help u.
