### ISSUE TITLE
Drag from outside using React 17 w/ functional component very broken

### ISSUE THREAD

**Issue by cramatt** [react-grid-layout/react-grid-layout#1534]
Best summarized by this code sandbox: https://codesandbox.io/s/use-hooks-2jx6s?file=/src/GridLayout.js

I'm trying to use this library within a functional component using the drag from outside approach. The example is very minimal and demonstrates some issues I'm having. To see the same example in a classic React component switch the index.js code to use `ShowcaseLayout.js` instead 

- The drag and drop item maintains the id `__dropping-elem__` instead of the id being re-assigned as in the ShowcaseLayout example
- onLayoutChange is fired AGAIN after the drop with an empty array. This updates state to contain no items. 

Expected behavior is that both example work the same. Unless I'm missing something obvious in the setup??

**Comment by markwatabe** [comment]
I'm struggling with this second, empty firing of onLayoutChange as well.
