### ISSUE TITLE
Prevent resizing grid element outside of the layout

### ISSUE THREAD

**Issue by sandrig** [react-grid-layout/react-grid-layout#1538]
Hi everybody! When you resize a grid item, the layout height value increases and vertical scrolling appears.

I'm using properties:
isBounded: true,
preventCollision: true,
verticalCompact: false

I expected: When you change the height of an element so that it doesn't go beyond the layout and doesn't cause vertical scrolling.

[Demo](https://codesandbox.io/s/elated-liskov-5tbx7?file=/src/RG.js)

**Comment by yoobi** [comment]
Any news on this ? I'm also looking for this

**Comment by lovelyelfpop** [comment]
That's not possible, it will go beyond the layout when you drag elements to change their positions.
You can alert user when save, or prevent saving it to the backend

**Comment by yoobi** [comment]
Oooh I see, okay thank you, so instead of blocking the heigh/width I can just tell that he's putting the card out of my virtual border and not save the change. 
Thank you

**Comment by sandrig** [comment]
> That's not possible, it will go beyond the layout when you drag elements to change their positions.
> You can alert user when save, or prevent saving it to the backend

Thanks, but ideally, just constrain resizing similarly to isBounded

**Comment by John-Al** [comment]
Running into this aswell. Surely isBounded should prevent items resizing outside of RGL container?

**Comment by Develonaut** [comment]
Hello I am also looking for a solution to this issue.

**Comment by bruce-c-liu** [comment]
Please reopen this issue.
