### ISSUE TITLE
Demo links does not work.

### ISSUE THREAD

**Issue by velikayikci** [react-grid-layout/react-grid-layout#1545]
Hello,

Check the demo links.
https://github.com/react-grid-layout/react-grid-layout#demos

**Comment by Dongd0825** [comment]
![image](https://user-images.githubusercontent.com/24449585/131622815-03466215-8143-4aa1-9e20-0259ed7789c8.png)
I click the link, also cannot show me the demo

**Comment by nekw** [comment]
I encounter same issue.

**Comment by guicara** [comment]
The examples seem to be hosted on another domain (strml.github.io/react-grid-layout).

The following links are working well, but I don't know if they are up to date with the master branch.

1. [Showcase](https://strml.github.io/react-grid-layout/examples/0-showcase.html)
1. [Basic](https://strml.github.io/react-grid-layout/examples/1-basic.html)
1. [No Dragging/Resizing (Layout Only)](https://strml.github.io/react-grid-layout/examples/2-no-dragging.html)
1. [Messy Layout Autocorrect](https://strml.github.io/react-grid-layout/examples/3-messy.html)
1. [Layout Defined on Children](https://strml.github.io/react-grid-layout/examples/4-grid-property.html)
1. [Static Elements](https://strml.github.io/react-grid-layout/examples/5-static-elements.html)
1. [Adding/Removing Elements](https://strml.github.io/react-grid-layout/examples/6-dynamic-add-remove.html)
1. [Saving Layout to LocalStorage](https://strml.github.io/react-grid-layout/examples/7-localstorage.html)
1. [Saving a Responsive Layout to LocalStorage](https://strml.github.io/react-grid-layout/examples/8-localstorage-responsive.html)
1. [Minimum and Maximum Width/Height](https://strml.github.io/react-grid-layout/examples/9-min-max-wh.html)
1. [Dynamic Minimum and Maximum Width/Height](https://strml.github.io/react-grid-layout/examples/10-dynamic-min-max-wh.html)
1. [No Vertical Compacting (Free Movement)](https://strml.github.io/react-grid-layout/examples/11-no-vertical-compact.html)
1. [Prevent Collision](https://strml.github.io/react-grid-layout/examples/12-prevent-collision.html)
1. [Error Case](https://strml.github.io/react-grid-layout/examples/13-error-case.html)
1. [Toolbox](https://strml.github.io/react-grid-layout/examples/14-toolbox.html)
1. [Drag From Outside](https://strml.github.io/react-grid-layout/examples/15-drag-from-outside.html)
1. [Bounded Layout](https://strml.github.io/react-grid-layout/examples/16-bounded.html)
1. [Resizable Handles](https://strml.github.io/react-grid-layout/examples/17-resizable-handles.html)
1. [Scaled Containers](https://strml.github.io/react-grid-layout/examples/18-scale.html)
1. [Allow Overlap](https://strml.github.io/react-grid-layout/examples/19-allow-overlap.html)

**Comment by IvanCuradaFrustratedCoder** [comment]
13 - 20 is returns 404

**Comment by STRML** [comment]
Demo is fixed.
