### ISSUE TITLE
Error when using functional component, functionality still works

### ISSUE THREAD

**Issue by joegrenan** [react-grid-layout/react-grid-layout#1553]
When using functional components with react-grid-layout, I get the following error:
`Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

Do I have to convert the direct children of my grid to class style `React.Components`? Other than the error message, everything works just fine.

**Comment by ddolcimascolo** [comment]
Yeah, this is actually in [the docs](https://github.com/react-grid-layout/react-grid-layout#custom-child-components-and-draggable-handles)

I personally just wrapped my custom component in a div. Works like a charm

**Comment by joegrenan** [comment]
@ddolcimascolo that worked perfectly, thank you. What additional functionality does this enable that wasn't there previously?

**Comment by oosswwaalldd** [comment]
Could you guys please share an example code for this solution? I followed the documentation mentioned above but it is not working for me.

Here is the code:

--- PARENT ---
```
const widgets = [
  { i: 'a', x: 0, y: 0, w: 1, h: 2 },
  { i: 'b', x: 1, y: 0, w: 3, h: 3, minW: 2, maxH: 6, minH: 3 },
  { i: 'c', x: 4, y: 0, w: 1, h: 2 },
]
<GridLayout
  className="bg-gray-400"
  cols={12}
  rowHeight={50}
  width={window.innerWidth}
  draggableHandle=".handle"
  resizeHandles={['se', 'sw']}
  layout={widgets}
>
  {widgets.map(item => (
    <Widget key={item.i} id={item.i}>
      Test
    </Widget>
  ))}
</GridLayout>
```

--- CHILD ---
```
const Widget = (
  { style, className, onMouseDown, onMouseUp, onTouchEnd, children, ...props },
  ref,
) => {
  return (
    <div
      className={`bg-yellow-300 text-black ${className}`}
      style={style}
      ref={ref}
      onMouseDown={onMouseDown}
      onMouseUp={onMouseUp}
      onTouchEnd={onTouchEnd}
    >
      <HolderOutlined className="handle cursor-move" />
      {children}
    </div>
  )
}
```
