### ISSUE TITLE
Clicking a `grid-item`'s  `draggableHandle` doesn't trigger `onDragStop` when click is released

### ISSUE THREAD

**Issue by joegrenan** [react-grid-layout/react-grid-layout#1555]
Exactly as the title says. If you just click a `grid-items` `draggableHandle`, it won't trigger `onDragStop` because it's only a click, and not a drag. But it does in fact trigger `onDragStart`. So if you disable rendering while moving/resizing, for example, the rendering is disabled... and stays disabled.

**Comment by kanonirbrest** [comment]
same issue

**Comment by kanonirbrest** [comment]
onDragStop is not working at all

**Comment by wyhinton** [comment]
Anyone figure this out?

**Comment by glennholland** [comment]
+1

**Comment by chriswoodley** [comment]
I can confirm this behavior as well.

**Comment by woollsta** [comment]
If anyone is still stuck on this and waiting for a workaround, I found that  ```onDrag``` insead of ```onDragStart``` only fires on an actual drag, meaning using it in conjunction with ```onDragEnd``` will always work as expected. However as expected it does repeatedly fire while dragging and so might not be suitable for every problem, but for me where I'm just making sure some local ```isDragging``` state is correct, it works fine.
