### ISSUE TITLE
Grid Re-renders every time I add a new item or remove an item

### ISSUE THREAD

**Issue by shahrouritTZ** [react-grid-layout/react-grid-layout#1556]
I have implemented the grid layout displaying charts, with the data fetched from the api
The user has the ability to add/remove charts to and from the grid
but every time the user adds/removes a chart
The whole grid re-renders and the charts are re-rendered

I have tried to implement useMemo as stated in the documentation, but still having the same issue

#### Dashboards
``` js
export const Dashboards = () => {
  const ResponsiveGridLayout = WidthProvider(Responsive);
  const [data, setData] = useState({[]});

  useEffect(() => {
      const getCharts = async () => {
          let response = await fetchData();
          setData(response);
          /**
           * response is an array of chart objects
           * the chart object looks like this
           * {
           *    chartId,
           *    width,
           *    height,
           *    top,
           *    left,
           * }
           */
      };
      getCharts();
  }, []);


  /**
   * Drawer component which lists a nnumber of charts with a checkbox
   * A user can add/remove chart by checking the checkbox
   */
  const onDrawerClose = (toUpdate) => {
    //toUpdate {chartId: checked, chartId: checked}
    if (toUpdate) {
      let clone = [...data];
      for (let chartId in toUpdate) {
        let found = clone.find((c) => c.chartId === chartId);

        //Add chart
        if (!found && toUpdate[chartId]) {
          clone.push({
            chartId,
            width: 8,
            height: 4,
            top: 0,
            left: 0
          });
        }
        //Remove chart 
        else if (found && !toUpdate[chartId]) {
          clone = clone.filter((n) => n.chartId !== chartId);
        }
      }

      setData(clone);
    }
  };

  const children = React.useMemo(() => {
    return data.map((node, index) => (
      <div
        className="reactGridItem"
        key={`${node.chartId}`}
        data-grid={{
          y: node.top,
          x: node.left,
          w: node.width,
          h: node.height,
          minW: 2,
        }}
      >
        <DashboardNode
          key={`node-${node.chartId}`}
          chartId={node.chartId}
        />
      </div>
    ));
  }, [data]);

  const myGrid = React.useMemo(() => {
    return (
      <ResponsiveGridLayout
        breakpoints={{ lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0 }}
        cols={{ lg: 24, md: 20, sm: 12, xs: 8, xxs: 4 }}
      >
        {children}
      </ResponsiveGridLayout>
    );
  }, [children]);

  return (
    <div>
      <div>
        {myGrid}
      </div>
      <ChartsDrawer
        loadedNodes={data}
        onClose={onDrawerClose}
      />
    </div>
  );
};
```
#### DashboardNode
> Gets re-rendered every time a chart is added or removed
``` js
export const DashboardNode = memo(
  ({chartId}) => {
    const [data, setData] = useState(null);

    useEffect(() => {
        const getChartData = async () => {
            let response = await fetchChartData()
            setData(response);
        };
        getChartData();
    }, [chartId]);

    const renderChart = () => {
      //based on the response data, the chart displays different types of charts
    };

    return (
      <div>
        {renderChart()}
      </div>
    );
  }
);
```

**Comment by STRML** [comment]
Now, it's not unreasonable that the charts are rerendered - this is normal - but they should not be unmounted and remounted. We use this on https://www.bitmex.com/app with the embedded TradingView chart and it works without issue.

**Comment by shahrouritTZ** [comment]
Hi @STRML 
Thanks for the quick reply

Bitmex's implementation differs from what our goal is, they have a fixed number of charts which are always the same when the page loads, however in our case we start of with an empty dashboard, and the user has a list of charts which he can add/remove to and from the dashboard.

I agree, re-rendering the charts is reasonable, but it's not just re-rendering it with the data it already has, it recalls the api endpoint and fetches the data again for every chart on the dashboard and then renders it when adding/removing a chart.

I have looked a lot into it and from what I've read,  using the `key` prop in map is what React uses to decide what to re-render and what not to. But it doesn't seem to be the case here.

Am I missing something?

**Comment by ddolcimascolo** [comment]
I didn't go into your code details, but it looks like you have custom keys (your `chartId`) which is actually a good thing. You just have to tell the layout that it should use that to identify the grid children. Simply add `i: node.chartId` in your `data-grid` object. 

This is in [the docs](https://github.com/react-grid-layout/react-grid-layout#grid-layout-props) but I remember having a few troubles like this at the beginning of an implementation similar to yours... Hope this helps

David

**Comment by shahrouritTZ** [comment]
Hello David,

Unfortunately I have tried adding the `i: node.chartId` in the `data-grid` object, but the re-rendering and the re-calling of the endpoint still remains.

Thank you for your input, I really appreciate it

**Comment by PierrickI3** [comment]
I have the same issue. I use map() to add custom components in <ResponsiveReactGridLayout/> and this causes a re-render each time causing an issue since my custom component (`<ResultCard />`) is called multiple times.

Is there a way to not get a re-render to run? Or am I doing this the wrong way?

@ddolcimascolo Any tips on how you fixed this?

My code:

```
import React, {useEffect} from 'react';
import Grid from '@material-ui/core/Grid';
import {useDispatch, useSelector} from 'react-redux';
import {onGetConnectorsData, onGetSubscriptionsData} from '../../../../redux/actions';
import GridContainer from '@crema/core/GridContainer';
import InfoView from '@crema/core/InfoView';
import Box from '@material-ui/core/Box';
import AppAnimate from '../../../../@crema/core/AppAnimate';
import {WidthProvider, Responsive} from 'react-grid-layout';
import ResultCard from '../ResultCard';
import 'react-grid-layout/css/styles.css';
import 'react-resizable/css/styles.css';

const ResponsiveReactGridLayout = WidthProvider(Responsive);

//#region Local Storage

const getFromLS = (key) => {
  let ls = {};
  if (global.localStorage) {
    try {
      ls = JSON.parse(global.localStorage.getItem('rgl-8')) || {};
    } catch (e) {
      /*Ignore*/
    }
  }
  return ls[key];
};

const saveToLS = (key, value) => {
  if (global.localStorage) {
    global.localStorage.setItem(
      'rgl-8',
      JSON.stringify({
        [key]: value,
      }),
    );
  }
};

//#endregion

const ResultsView = () => {
  //#region Get Data

  const dispatch = useDispatch();

  useEffect(() => {
    dispatch(onGetConnectorsData());
    dispatch(onGetSubscriptionsData('1'));
  }, [dispatch]);

  const connectors = useSelector(({dashboard}) => dashboard.connectorsData);
  const subscriptions = useSelector(({dashboard}) => dashboard.subscriptionsData);
  
  useEffect(() => {
    if (connectors !== null) console.log('Connectors:', connectors);
  }, [connectors]);

  useEffect(() => {
    if (subscriptions !== null) console.log('Subscriptions:', subscriptions);
  }, [subscriptions]);

  //#endregion

  //#region Layout

  const originalLayouts = getFromLS('layouts') || {
    lg: [
      {i: 'a', x: 1, y: 0, w: 1, h: 1},
      {i: 'b', x: 0, y: 0, w: 1, h: 1},
      {i: 'c', x: 0, y: 0, w: 1, h: 1},
    ],
    md: [
      {i: 'a', x: 1, y: 0, w: 1, h: 1},
      {i: 'b', x: 0, y: 0, w: 1, h: 1},
      {i: 'c', x: 0, y: 0, w: 1, h: 1},
    ],
    sm: [
      {i: 'a', x: 1, y: 0, w: 1, h: 1},
      {i: 'b', x: 0, y: 0, w: 1, h: 1},
      {i: 'c', x: 0, y: 0, w: 1, h: 1},
    ],
    xs: [
      {i: 'a', x: 1, y: 0, w: 1, h: 1},
      {i: 'b', x: 0, y: 0, w: 1, h: 1},
      {i: 'c', x: 0, y: 0, w: 1, h: 1},
    ],
    xss: [
      {i: 'a', x: 1, y: 0, w: 1, h: 1},
      {i: 'b', x: 0, y: 0, w: 1, h: 1},
      {i: 'c', x: 0, y: 0, w: 1, h: 1},
    ],
  };
  const [layouts, setLayouts] = React.useState(JSON.parse(JSON.stringify(originalLayouts)));

  const onLayoutChange = (layout, layouts) => {
    // console.log('onLayoutChange');
    saveToLS('layouts', layouts);
    setLayouts({layouts});
  };

  //#endregion

  return (
    <>
      {connectors?.length > 0 && subscriptions?.length > 0 ? (
        <AppAnimate animation='transition.slideUpIn' delay={200}>
          <Box pt={{xl: 4}}>
            <GridContainer>
              <Grid item lg={12} md={12} xs={12}>
                <ResponsiveReactGridLayout className='layout' layout={layouts} rowHeight={120} cols={{lg: 4, md: 3, sm: 3, xs: 2, xxs: 1}} margin={[30, 30]} isResizable={false} onLayoutChange={(layout, layouts) => onLayoutChange(layout, layouts)}>
                  {subscriptions.map((subscription, i) => {
                    console.log('Adding card for subscription id:', subscription.id);
                    return (
                      <div className='grid-item' key={i} data-grid={{x: i, y: 0, w: 1, h: 1}}>
                        <ResultCard connector={connectors?.find((c) => c.id === subscription.connectorId)} subscription={subscription} />
                      </div>
                    );
                  })}
                </ResponsiveReactGridLayout>
              </Grid>
            </GridContainer>
          </Box>
        </AppAnimate>
      ) : (
        <div>Loading...</div>
      )}
      <InfoView />
    </>
  );
};

export default ResultsView;
```

**Comment by shahrouritTZ** [comment]
> @ddolcimascolo Any tips on how you fixed this?

@PierrickI3 as @ddolcimascolo  suggested

> Simply add `i: node.chartId` in your `data-grid` object.

in your case
`<div className='grid-item' key={subscription.id} data-grid={{i:subscription.id ,x: i, y: 0, w: 1, h: 1}}>`

Although it didn't work for me, I hope it does for you

**Comment by ddolcimascolo** [comment]
There might be some confusion here. 

When you add items there's a rerender and it's expected, because the layout is updated. The fact that the <RGL /> component rerenders is not to be confused with your child components un mounting and re mounting, which is not supposed to happen if you use stable keys...

Can you confirm what you're trying to avoid?

**Comment by PierrickI3** [comment]
Indeed @ddolcimascolo , adding `i: subscription.id` does not change anything in my case as @shahrouritTZ suggested.

@ddolcimascolo , I want to add a component for each subscription I have. However, when each new subscription is added, it triggers the `map()` all over again. 

When I run my code at the moment, I have a total of 4 subscriptions that should result in 4 `ResultsCard` that need to be added. However, in my case, `map()` is executed 3 times which triggers 12 `ResultCard`. 

By reading others who have experienced the same issue, I thought I was facing a re-render issue. 

Is there a way to have the grid only render its children once? Or did I design this the wrong way?

Thanks!

**Comment by PierrickI3** [comment]
Here is a sample of my console showing that each subscription id (e.g. `bfd7...`) is rendered 3 times.

![image](https://user-images.githubusercontent.com/7140338/132995506-6eb8f32e-6376-4e2b-894f-4412df578645.png)

**Comment by STRML** [comment]
As @ddolcimascolo correctly noted, I believe you are conflating the idea of rerendering with unmounting/remounting.

It is perfectly normal for child components to rerender often. Whenever the grid items are moved, they necessarily cause a render in order to pass new `style` props.

If you want your child components to only ever render once (this is unusual and probably not what you really want), set `shouldComponentUpdate` to return `false`, or for functional components, export `React.memo(MyComponent)` instead. See [React.memo docs](https://reactjs.org/docs/react-api.html#reactmemo).

**Comment by ddolcimascolo** [comment]
Yeah, thx @STRML for precising what I was trying to explain :)

@PierrickI3 For instance in your console log you can see that `connectors` changes from undefined to an array. This causes a rerender, thus triggering your console log in a useEffect, because you're using a hook to get `connectors` and when the value of that hook changes, React renders your component... Again this is just the way things work.

**Comment by PierrickI3** [comment]
Thank you guys. Appreciate the reply.

**Comment by shahrouritTZ** [comment]
> If you want your child components to only ever render once (this is unusual and probably not what you really want), set `shouldComponentUpdate` to return `false`, or for functional components, export `React.memo(MyComponent)` instead. See [React.memo docs](https://reactjs.org/docs/react-api.html#reactmemo).

I am actually using React.memo in my `DashboardNode` component, because each dashboard node is a chart and calls an endpoint to get the data for that chart, that is why I am trying to render it once, but with all that, it is still unmounting /mounting the `DashboardNode` component, and thus calling the endpoint multiple times for each chart

**Comment by PierrickI3** [comment]
Thanks again. I have managed to fix this by using `useSelector` in a better way.

**Comment by LikhithaSanga11** [comment]
@shahrouritTZ , I have the use case that you are using to add panels, when I am adding new panel if there is an empty space it is not filling and adding new panel at the bottom. I have any empty space I need to cover that empty space first. Is there any properties to add for this?

{i:field.alias,id:field.id,x:(i%2==0?0:1)*6,y:0,w:6,h:2,isResizable:isResizable,isDraggable:isDraggable}
<ResponsiveReactGridLayout
      margin={[5, 5]}
      onLayoutChange={layoutChange}
      onResizeStop={(layout, oldItem, newItem, placeholder, event, element) => {
        resizeFn(element);
      }}
      layouts={gridLayouts}
      measureBeforeMount={false}
    >
      {cards.map((el, index) => createElement(el, index))}
    </ResponsiveReactGridLayout>

**Comment by wenjichen0516** [comment]
@shahrouritTZ 
Did you figure it out eventually? I run into the same issue.
When ever adding/removing an item in the grid layout, all item will re-rendered and call the endpoint to fetch the data.
