### ISSUE TITLE
how to disable messy layout autocorrect

### ISSUE THREAD

**Issue by Remy-J** [react-grid-layout/react-grid-layout#1562]
Hello, I would like to know if it was possible to disable the automatic correction of the layout when loading it.

**Comment by AaryTrivedi** [comment]
I have the same question, how can we disable automatic correction??

**Comment by AaryTrivedi** [comment]
I'm sorry, but I found the solution. It was in the documentation. Just adding the link so it can help others.

Prop details from documentation:
// Compaction type.
compactType: ?('vertical' | 'horizontal' | null) = 'vertical';

or you could use 

verticalCompact: ?(true|false) [I do not know the default value here, can't find this in documentation]

Example: https://react-grid-layout.github.io/react-grid-layout/examples/11-no-vertical-compact.html.
