### ISSUE TITLE
the layoutChange function only trigger when I use the resize when the allowOverlap parameter is set to true

### ISSUE THREAD

**Issue by Remy-J** [react-grid-layout/react-grid-layout#1564]
Hi,
when the allowOverlap parameter is set to true the layoutChange function is only trigger when the elements are resized,
when it should be run when the elements are moved too.

https://codesandbox.io/s/react-grid-layout-forked-p0ugr

**Comment by Remy-J** [comment]
hello, does anyone have an answer?

**Comment by jiaicon** [comment]
I also encountered this problem, but I didn't expect a solution. I didn't use allowoverlap for the time being.

**Comment by Remy-J** [comment]
I managed to work around the problem by using the onDragStop
 thank you @jeddi
