### ISSUE TITLE
Drag and combine "allowOverlap" layout from outside to not "allowOverlap"

### ISSUE THREAD

**Issue by dengbupapapa** [react-grid-layout/react-grid-layout#1575]
Drag and combine "allowOverlap" layout from outside to not "allowOverlap"

**Comment by Vokabelsalat** [comment]
Still relevant. Would be interested in a solution, because allowOverlap isn't working together with drop from outside in a Responsive Layout.

**Comment by wangzongming** [comment]
Hello, I have the same problem. Have you solved it?
