### ISSUE TITLE
(Feature Request) Extend documentation for Custom Child Components

### ISSUE THREAD

**Issue by Ducki** [react-grid-layout/react-grid-layout#1576]
The documentation for custom child components only shows a minimal example, which doesn't work when dropped in.
It is unclear, how the reference forwarding needs to be worked out in the parent component.

It would be very helpful, if the examples section would contain a complete example showing this (obviously common) scenario.

**Comment by w3ichen** [comment]
Here's my attempt at using a custom component for the grid item

**Image of grid items**
![image](https://user-images.githubusercontent.com/57570491/154857211-9635a7e4-dcdc-47cf-af92-3066a40b7ca0.png)

**Parent component**
```
import React from "react";
import ReactGridLayout from "react-grid-layout";
import AppInput from "./AppInput";

const COLS = 10;
export default function InputsSection() {
  return (
    <ReactGridLayout className="layout" cols={COLS} rowHeight={70} width={1000}>
      {["one", "two", "three"].map((key) => (
        <AppInput key={key} />
      ))}
    </ReactGridLayout>
  );
}
```

**Child Component**
```
import { DragIndicator } from "@mui/icons-material";
import { IconButton } from "@mui/material";
import React, { forwardRef, ReactChild } from "react";
interface Props {
  children?: ReactChild | ReactChild[];
  onMouseDown?: (e: any) => void;
}

const AppInput = forwardRef(({ children, onMouseDown, ...rest }: Props, ref) => {
  return (
    <div {...rest}>
      <IconButton onMouseDown={onMouseDown} sx={{ cursor: "move !important" }}>
        <DragIndicator />
      </IconButton>
      HELLO
      {children}
    </div>
  );
});
export default AppInput;
```

In order for the custom component to work, you need three things:

1. `forwardRef` must be used to forward the ref
2. `...rest` must be passed to the element. It contains a number of attributes that `react-grid-layout` passes to the child
3. `{children}` must be used for the resize handle to show up
