### ISSUE TITLE
Layout with compact type null does not restore after collision.

### ISSUE THREAD

**Issue by arclogos132** [react-grid-layout/react-grid-layout#1577]
How can I make RGL work like the demo from the link below?

https://gridstackjs.com/demo/float.html

I would like to make the layout restore to how it was before the collision if the drag is stopped on an empty space.
This needs to be done white the layout's compact type has to be null.

Am I missing a property that would enable this feature or am I the only one who needs this?

**Comment by jledentu** [comment]
Please reopen this issue, I also encounter the issue: dragging an item leaves too many gaps in the layout.
