### ISSUE TITLE
how to get `onDragStart` dataTransfer data on `onDropDragOver`

### ISSUE THREAD

**Issue by luisiacc** [react-grid-layout/react-grid-layout#1579]
How to do this? I tried:
```jsx
const handleDragOver = (e) => {
    console.log({t: e.dataTransfer.getData("text"), d: e.dataTransfer.getData("text/plain")});
    return {w: 2, h: 5};
};

const DraggableContainer = (props) => (
    <div
        className="droppable-element btn btn-default"
        draggable
        unselectable="on"
        onDragStart={(e) => e.dataTransfer.setData("text/plain", "testing"))}>
        {props.children}
    </div>
);


```

But got an empty string when logging.

If I could get the `target` element that is been dropped over would be fine as well.

**Comment by Ducki** [comment]
I can confirm, that the dataTransfer object doesn't get exposed.
The culprit seems to be here, where DragEvent doesn't get included in the type declaration:
https://github.com/react-grid-layout/react-grid-layout/blob/master/lib/utils.js#L51

In its current form, the new onDropDragOver handler is pretty useless without access to the actual dragEvent stuff.

**Comment by ggbond2077** [comment]
[onDropDrag ](https://stackoverflow.com/questions/31915653/how-to-get-data-from-datatransfer-getdata-in-event-dragover-or-dragenter)

this problem seems cause by html5 design

**Comment by juny1zhang** [comment]
您好，我已收到您的邮件。我最近正在努力学习中-_-，无法及时回复你的邮件。我将在看到后，尽快给您回复。

**Comment by juny1zhang** [comment]
您好，我已收到您的邮件。我最近正在努力学习中-_-，无法及时回复你的邮件。我将在看到后，尽快给您回复。

**Comment by juny1zhang** [comment]
您好，我已收到您的邮件。我最近正在努力学习中-_-，无法及时回复你的邮件。我将在看到后，尽快给您回复。

**Comment by sayo96** [comment]
Is there any fix for this ?

**Comment by juny1zhang** [comment]
您好，我已收到您的邮件。我最近正在努力学习中-_-，无法及时回复你的邮件。我将在看到后，尽快给您回复。

**Comment by DmitryKaplyush** [comment]
I also encountered this problem

**Comment by juny1zhang** [comment]
您好，我已收到您的邮件。我最近正在努力学习中-_-，无法及时回复你的邮件。我将在看到后，尽快给您回复。
