### ISSUE TITLE
onLayoutChange is not called when allowOverlap is true

### ISSUE THREAD

**Issue by diragb** [react-grid-layout/react-grid-layout#1587]
as the title suggests, `onLayoutChange` is not called on layout changes when `allowOverlap` is set to true. here's a [codesandbox example](https://codesandbox.io/s/sharp-lehmann-n3f5k) that demonstrates the same.

**Comment by catusmagnus** [comment]
here's a workaround for now:
```tsx
import { useState } from 'react'
import GridLayout from 'react-grid-layout'
import isEqual from 'lodash/isEqual'

const [ oldLayout, updateLayout ] = useState([])

<GridLayout
  onDragStop={ (newLayout) => { if (!isEqual(oldLayout, newLayout)) updateLayout(newLayout) }}
></GridLayout>
```

**Comment by manuelnogueiramov** [comment]
This doesn't solve it if we're using resposive, as we don't know which breakpoint we're at... any updates on this issue?
