### ISSUE TITLE
Resize Handles - SE and SW resize handles display in the same position on a grid item

### ISSUE THREAD

**Issue by ByronDWall** [react-grid-layout/react-grid-layout#1588]
I have run into an interesting issue where declaring `resizeHandles: [ 'se', 'sw']` results in both `se` and `sw` being in the dom and attached to the grid item, but in the same place, as seen in this screen grab: 
https://user-images.githubusercontent.com/87667330/136794836-da38bcb2-4e7a-4961-8450-f5f4bd9ba936.mov

and reproduced in codesandbox here (see line 102 of `ShowcaseLayout.js`):
https://codesandbox.io/s/festive-moser-y9qjl

I'm not sure if it happens in other usecases (different combos of `resizeHandle` array values), would be happy to look into it further if need be, thanks!

**Comment by JayrajShah** [comment]
Hi @ByronDWall , I had a look in the codeSandbox. I guess I may have found a solution. You gotta import a CSS file in your index.js file provided in the package itself.
Try writing

import "react-resizable/css/styles.css"


Hope this works.

**Comment by ByronDWall** [comment]
> Hi @ByronDWall , I had a look in the codeSandbox. I guess I may have found a solution. You gotta import a CSS file in your index.js file provided in the package itself.

@JayrajShah interesting! I solved this by going with a design that only uses the `sw` resize handle, but this is also something I will look into if I run into a similar issue.  Thanks!
