### ISSUE TITLE
lower right arrow

### ISSUE THREAD

**Issue by linlwss** [react-grid-layout/react-grid-layout#1595]
How to hide the lower right arrow？
如何隐藏右下角箭头？

**Comment by smorovic** [comment]
Same problem, the arrow (anchor) shows up even with static: true.
Last version not affected is 0.17.1 and I had to stick with that one.

**Comment by STRML** [comment]
Hide it with css.

**Comment by smorovic** [comment]
I need it dynamically (on a global toggle), but I found another way: set resizeHandle based on toggle setting.
```
<PortletLayout
  resizeHandle={editMode ? undefined : <div />}`
  ...
>
```
where
```
import { Responsive, WidthProvider } from 'react-grid-layout';
const PortletLayout = WidthProvider(Responsive);
```
Limitation is it applies to all elements in the grid, but sufficient for my use case.
