### ISSUE TITLE
Can I remove the margin for the first and last grid item.

### ISSUE THREAD

**Issue by TrendAlan** [react-grid-layout/react-grid-layout#1596]
If I have 4 grid items in a row inside a parent div, and I set the margin to [20,0], and the space between each item with be 20px.
But the first item also has a 20px distance to the left of the parent div and the last item also has 20px distance to the right of the parent div.
How can I remove the 20 px margin for the first and last items?

**Comment by divpusher** [comment]
I have the same issue.

`margin={[20, 20]}`

![image](https://user-images.githubusercontent.com/31571016/142908858-16b9b0bb-0cb0-4430-9a75-b2786412c700.png)

**Comment by eneskabacaoglu** [comment]
@divpusher This should be because of the container padding.
Please try that : `containerPadding={[0, 0]}`

**Comment by divpusher** [comment]
Perfection, thank you!

**Comment by TrendAlan** [comment]
> Perfection, thank you!

Fixd, thank you
