### ISSUE TITLE
When using `InnerRef` prop, RGL doesn't work

### ISSUE THREAD

**Issue by cybaj** [react-grid-layout/react-grid-layout#1605]
As the title, when using ref for grid layout wrapper on grid layout prop, no responsives work.
if delete the prop, then responsives work.

RGL : 1.1.3
with WidthProvider HOC.

**Comment by cybaj** [comment]
My bad. There are mistakes in my code.

**Comment by lorenzobalzani** [comment]
Hi @cybaj, how were you able to solve the problem?

**Comment by rnascunha** [comment]
Hi, having same problem here. Anyone?
RGL: 1.4.4
Also reported here #1444
