### ISSUE TITLE
CompactType: Swap || Snake

### ISSUE THREAD

**Issue by alex254** [react-grid-layout/react-grid-layout#1612]
I guess this is more of a feature request. A simple swap of two items doesn't seem to be possible. Neither horizontal, vertical, or null compaction is the desired behavior, because it can leave blank spaces or it creates carousel like behavior: for instance a horizontal move with vertical compaction and vice versa. I am just looking for a simple swap :P. Or a another compaction type could be: SNAKE where a gap is filled by compacting horizontally and the new gap at the end of the row is filled by the first item in the next row andsoforth.

**Comment by eneskabacaoglu** [comment]
That would be nice and yes, that's more like a feature request. On the other hand,  I feel like this would create too much work to create.

**Comment by nanxiaobei** [comment]
really need this, like iOS home screen reordering of apps.
