### ISSUE TITLE
onLayoutChange is returning empty array on each reload

### ISSUE THREAD

**Issue by timmsedlaczek** [react-grid-layout/react-grid-layout#1615]
Hi everybody,

I'm facing an issue with saving layouts to the database in order to persist the sort order of the child elements in the grid.

Here's my code:

````
import React from 'react';
import CardNote from "./card-note";
import { Responsive, WidthProvider } from 'react-grid-layout'
import '../../../../node_modules/react-grid-layout/css/styles.css';
import '../../../../node_modules/react-resizable/css/styles.css';
import CollectionService from "services/collection.service";

const CardList = ({ collection, cards }) => {
    const ResponsiveGridLayout = WidthProvider(Responsive)

    const onLayoutChange = (layout, layouts) => {
            CollectionService.updateLayouts(collection._id,JSON.stringify(layouts));
    }

    return (
        <>
            {cards &&
            <ResponsiveGridLayout className="layout"
                                  breakpoints={{lg: 1200, md: 768, sm: 480}}
                                  cols={{lg: 3, md: 2, sm: 1}}
                                  isResizable={false}
                                  isBounded={true}
                                  useCSSTransforms={false}
                                  layouts={JSON.parse(collection.layouts)}
                                  onLayoutChange={(layout, layouts) =>
                                      onLayoutChange(layout, layouts)
                                  }
            >
                { cards.map((card) => (
                    {
                        'note': <div key={card._id} className="card cardText"><CardNote card={card} /></div>,
                    }[card.type]
                ))}
            </ResponsiveGridLayout>
            }
        </>
    );
};

export default CardList;


````

Issue is, that on every page load, the onLayoutChange function saves an empty layout into the database, so that the order of the elements is reset. 
In my logs I can see that when I'm dragging the elements within the grid, the database is successfully updated, e.g.  `{"lg":[{"w":1,"h":1,"x":1,"y":0,"i":"6199169b746166614ff45585","moved":false,"static":false}]}`. 
On page reload, the layouts from the database are loading correctly, but when onLayoutChange fires directly after load, the layouts returned by onLayoutChange function look like this, which of course resets the order:
`{"lg":[]}`

I've read somewhere, that passing the layouts via props can cause issues. Is this the case or am I doing something else wrong? 

Using the following condition in onLayoutChange function solves the issue (at least for desktop), but I think it's not a good solution.
`````
        if(layouts["lg"].length > 0){
            CollectionService.updateLayouts(collection._id,JSON.stringify(layouts));
        }
``````

Any help is very much appreciated.

**Comment by ddolcimascolo** [comment]
Hi @timmsedlaczek

Are you sure you're not rendering an empty array of cards? This is typical if you're using an async service to fetch the data...

The scenario would be
1. `cards` is empty, so RGL has no children and calls you back with an empty layout
2. `cards` become ready, so a rerender occurs and this time RGL has children and generates a fresh new layout

You're guarding against a falsy `cards` but not against an empty array.

Also I found #1583 #1529 that might be related

**Comment by timmsedlaczek** [comment]
@ddolcimascolo 
I though my check for cards in the return was checking for the array to be empty to. Your comment helped me solving the issue - thanks!

**Comment by ddolcimascolo** [comment]
Glad I could help 👍
