### ISSUE TITLE
how to make only the outside area of the box draggable?

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [react-grid-layout/react-grid-layout#1617]

**Comment by moromis** [comment]
@hp8wvvvgnj6asjm7 hi! I see you closed this, do you remember how you solved this? Thanks in advance.

**Comment by moromis** [comment]
Update for anyone who comes across this, here's the answer I found after searching more: https://github.com/react-grid-layout/react-grid-layout/issues/1094
