### ISSUE TITLE
Dynamically render react children as Grid Items

### ISSUE THREAD

**Issue by artivilla** [react-grid-layout/react-grid-layout#1621]
Went through quite a few issues here to find how items are dynamically rendered mapping children but wasn't able to modify my own case; attached is a sample codesandbox: https://codesandbox.io/s/elastic-carson-kp9s3?file=/src/App.js:840-850

It renders when I use only  `<GridLayout />` with child components.
It also renders when I only render the children using `<RandomizeLayout />` without `<GridLayout />`.

But when I use them in conjunction I don't get any useful errors. Any suggestions? I'd like to evolve this and then render the layout values dynamically (next steps) so rending the contents in this manner is a required case.

**Comment by Ducki** [comment]
Hey there!
It seems your're missing forwarding the ref to the child element: https://github.com/react-grid-layout/react-grid-layout#custom-child-components-and-draggable-handles

**Comment by hexwit** [comment]
I wrapped custom component content with forward ref like it was proposed in the documentation. I am able to drag it and move, but resizing functionality lost. It just doesn't show default resize handler.

```
const CustomGridItemComponent = React.forwardRef(({style, className, ...props}: any, ref:any) => {
    return (
        <div style={{backgroundColor: "blue", ...style}} {...props} className={className} ref={ref}>
            hello world
        </div>
    );
});

export default CustomGridItemComponent;
```

Could you suggest what is missing?

**Comment by flyingbirdhub** [comment]
> https://github.com/react-grid-layout/react-grid-layout#custom-child-components-and-draggable-handles

you can add {props.children} in your component, but i still stuck in a problem, that i cannot move it

**Comment by YangYmimi** [comment]
try: 

```
<div key={row.i} className="border-[1px] border-solid border-black">
  <CustomComponent domId={row.i} />
</div>
```
