### ISSUE TITLE
Is there a way to know when the initial layout is done?

### ISSUE THREAD

**Issue by shivijais** [react-grid-layout/react-grid-layout#1622]
Hi 
I am trying to implement a dashboard where each grid needs to perform some action only after the layout by react-grid-layout is done, so that each grid has a way to access its styles. I am passing the layout using {x,y,h,w} format.

**Comment by Ducki** [comment]
Please look at the [documentation for the react effect hooks](https://reactjs.org/docs/hooks-effect.html).
Use the useEffect hook, to do stuff after the component has rendered.
