### ISSUE TITLE
Grid behaviour for different compacttypes - loosing the elastasity

### ISSUE THREAD

**Issue by alon24** [react-grid-layout/react-grid-layout#1624]
I am trying to use the grid-layout, and move  - position widgets but am looking at issues:
1. compacType=horizontal - its possible for the user while just trying to drag one widget, to completly ruin the dashboard state, which is not good
![horizontal](https://user-images.githubusercontent.com/5415443/144086818-8d8c1ca9-f190-4f95-b0c1-2ae452c77d28.gif)

2. compacType=verticle - same but different method to ruin the dashboard, also cannot add a widget to a line with 3 widgets
y=1 if y=0 has 3 widgets in it
I would expect compacting for missing lines, this is hurting the user which wants to rearrange, and not have things just jump around
![vertical](https://user-images.githubusercontent.com/5415443/144087155-b651d3fc-7601-42a9-90ef-e7610d682f0a.gif)
i0

3.compactTytpe=null - users can just mess things up without even trying, just move around, no widget has the "elastsity" to return to previous location (which is somewhat present in "horizontal" and "vertical"

4. when in  "horizontal" and "vertical" - onstartdrag, and onstratresize, do not give me the old layout, but they give the layout, after some colision work has been done (so I cannot just replace this manually)

https://codesandbox.io/s/react-grid-layout-compacttype-lgt

**Comment by djmisterjon** [comment]
on my side i add little experimental hack
![image](https://user-images.githubusercontent.com/24865815/150613429-2beccd95-e8bb-4ead-af74-29806cbb3405.png)

the function look like this for now 
```ts
	public doTryRestorPositionIfPossible( restorLayouts:Layout[], changedLayouts: Layout[], refItem:Layout, actionMode:'resize'|'move', handleType:'nw'|'ne'|'sw'|'se'|'n'|'s'|'e'|'w' ) {
		// Look if can restor position of all layouts wihout collides with refItem
		// TODO: recursive in while loop when a restor performed
		changedLayouts.forEach( ( changedItem, i ) => {
			const restorRef = restorLayouts[i];

			if( changedItem.i === refItem.i ) {
				if( actionMode === 'resize' ) {// TODO: check if can restor position
					if( handleType.includes( 'w' ) ){
						const isChangedY = restorRef.y !== refItem.y;
						const isBackToXOrigin = refItem.x === restorRef.x;

						if( isChangedY && isBackToXOrigin ) 	refItem.y = restorRef.y;
					}
				}
			} else

			// If refItem is not collides with restorRef,asign restorRef to changedItem
			if( !this.isCollides( refItem, restorRef ) ) {
				changedItem.x = restorRef.x;
				changedItem.y = restorRef.y;
			}
		} );
	}
```

![rglrestordp](https://user-images.githubusercontent.com/24865815/150613958-7865cbb4-fe7a-4e0f-bbb2-950beed25dc5.gif)

But @STRML you probably have a better idea or solution to perform this, because i found the way very dirty and hacky !
I think the issue come from lack of exposing events from `~/react-grid-layout/lib/GridItem.jsx` where we should able to replace or hack the math algo !?

**Comment by jledentu** [comment]
@alon24 

> 3.compactTytpe=null - users can just mess things up without even trying, just move around, no widget has the "elastsity" to return to previous location (which is somewhat present in "horizontal" and "vertical"

FYI, here is a PR I made on vue-grid-layout to resolve the same issue: https://github.com/jbaysolutions/vue-grid-layout/pull/646#issuecomment-1035135074
