### ISSUE TITLE
Problems with unnecessary re-renders

### ISSUE THREAD

**Issue by LennonOliveira29** [react-grid-layout/react-grid-layout#1627]
I'm creating a graphics panel and when I add a new grid or resize existing graphics, the React update everything again.
I'm new to the lib, if anyone can help me.

Note: In the example I did in Codesandbox when resizing it doesn't render again, but when I add one more element it renders again. I think because the chart data is fixed

<img src="https://user-images.githubusercontent.com/89031566/144869770-b691cd23-f8ca-48e2-bbcc-5302dc062d25.gif" alt="Dashboard error" hspace="20"/>

My code

<br>
<a href="https://codesandbox.io/s/react-grid-charts-wmpq5" target="blank">CODESANDBOX</a>

**Comment by Ducki** [comment]
Well that's the way react works: if the properties or state changes (which it does in this case, because the layout of the grid changes), it re-renders it. Perhaps you could disable the fade animation, so that the re-render is not visible.

**Comment by cmocanu** [comment]
Use React.memo on the component inside and make sure the props stay the same.

**Comment by LennonOliveira29** [comment]
Thanks @Ducki!
I managed to memoize the internal component that renders the graphic and it worked.

**Comment by wenjichen0516** [comment]
@LennonOliveira29,
How did you solve the issue? Using memo doesn't work for my case.
