### ISSUE TITLE
Can you publish new version 1.3.1 to npm

### ISSUE THREAD

**Issue by alon24** [react-grid-layout/react-grid-layout#1628]
![image](https://user-images.githubusercontent.com/5415443/145060363-6f781e02-55b5-40b9-9960-f0b685731bb6.png)

**Comment by orhantuzuner** [comment]
I need this ->"Fix allowOverlap not firing onLayoutChange()"
Can you publish version 1.3.1 to npm.

**Comment by STRML** [comment]
I apologize for the oversight, this is now published.
