### ISSUE TITLE
How can a component adapt to height ？ 

### ISSUE THREAD

**Issue by Deja-vuuu** [react-grid-layout/react-grid-layout#1631]
Let's say I have three components vertically listed on the page,In the middle is a commodity component。It displays lists of different lengths depending on the user。

![image](https://user-images.githubusercontent.com/27748682/145966850-ebabb4f7-bb66-4a4f-bc45-71272d2d43b2.png)

**Comment by hornta** [comment]
This needs more explanation. What are you trying to do with react-grid-layout?
