### ISSUE TITLE
【bug】When I use onlayoutchange, onlayoutchange will not be triggered during dragging.

### ISSUE THREAD

**Issue by jiaicon** [react-grid-layout/react-grid-layout#1638]
Look!
This is what caused the problem.
![image](https://user-images.githubusercontent.com/34124517/147308553-0e0b8e39-6f43-4e1e-be0b-f176350b9f48.png)

**Comment by hornta** [comment]
What problem? What are you reffering to?

**Comment by livandrey** [comment]
When  `allowOverlap = true` and moving without collisions onLayoutChange will not be triggered

To fix this:
lib/ReactGridLayout.jsx:

in `onDragStart`:
`oldLayout: layout` -> `oldLayout: cloneLayout(layout)`

same in `onResizeStart`:
`oldLayout: this.state.layout` -> `oldLayout: cloneLayout(this.state.layout)`

**Comment by artemlaptev63** [comment]
> When `allowOverlap = true` and moving without collisions onLayoutChange will not be triggered
> 
> To fix this: lib/ReactGridLayout.jsx:
> 
> in `onDragStart`: `oldLayout: layout` -> `oldLayout: cloneLayout(layout)`
> 
> same in `onResizeStart`: `oldLayout: this.state.layout` -> `oldLayout: cloneLayout(this.state.layout)`

have the same issue, the solution did not help

**Comment by artemlaptev63** [comment]
> When `allowOverlap = true` and moving without collisions onLayoutChange will not be triggered
> 
> To fix this: lib/ReactGridLayout.jsx:
> 
> in `onDragStart`: `oldLayout: layout` -> `oldLayout: cloneLayout(layout)`
> 
> same in `onResizeStart`: `oldLayout: this.state.layout` -> `oldLayout: cloneLayout(this.state.layout)`

@livandrey have the same issue, the solution did not help

**Comment by R4DIC4L** [comment]
For anyone else trying this function, I had to specifically add allowOverlap={false} property, it is probably set on true by default.

**Comment by chandlervdw** [comment]
You can add the same `ItemCallback` to `onLayoutChange`, `onDragStop` and `onResizeStop` in order to update the layout on drag/resize when `allowOverlap` is true.
