### ISSUE TITLE
Replace usage of transform: translate to avoid Chrome blurry text bug

### ISSUE THREAD

**Issue by cmocanu** [react-grid-layout/react-grid-layout#1642]
Because of the use of `transform: translate` to set the position of the grid elements, in some cases, depending on the content of the items, the text becomes blurry on Chrome because of a rendering bug. Discussed before in #125

I tried to get a repro in codesandbox but I can't seem to be able to it. I managed to get it "working" in devtools so here's a video. There are some workarounds on the web but I couldn't get any of them to work in the product I'm working on at the moment. Is there any way you could use something else instead of `translate` to set the positions of the items? Why not `left` and `top`?

https://user-images.githubusercontent.com/854740/148463934-a4859754-fefb-4b80-8920-23d432278922.mov

**Comment by STRML** [comment]
Left and top work differently and they aren't gpu accelerated, so it
affects performance. Sorry but we aren't going to support left/top.
