### ISSUE TITLE
dragged from outside and allowOverlap=true

### ISSUE THREAD

**Issue by qqjiandj123** [react-grid-layout/react-grid-layout#1649]
If dragged from outside into react-gird-layout, it will trigger reordering, when I set compactType=null, allowOverlap=true, isDroppable=true

**Comment by qqjiandj123** [comment]
I have already set preventCollision=true

**Comment by qqjiandj123** [comment]
Hi Bro can you help me to vertify this problem? @ @torkelo @bryantsai @betalb @ericgibb

**Comment by qqjiandj123** [comment]
<GridLayout
        className="layout"
        cols={48}
        useCSSTransforms={true}
        isBounded={false}
        allowOverlap={true}
        preventCollision={true}
        compactType={null}
      >
        {this.renderGrid(layout)}
      </GridLayout>

**Comment by qqjiandj123** [comment]
`<GridLayout
        className="layout"
        cols={48}
        useCSSTransforms={true}
        isBounded={false}
        allowOverlap={true}
        preventCollision={true}
        compactType={null}
      >
        {this.renderGrid(layout)}
      </GridLayout>`

**Comment by SunriseWiLL** [comment]
cause by the function **compactItem** did not consider the compactType={null} condition:
```
    if (compactH) {
      resolveCompactionCollision(fullLayout, l, collides.x + collides.w, "x");
    } else {
      resolveCompactionCollision(fullLayout, l, collides.y + collides.h, "y");
    }
```
