### ISSUE TITLE
Define the top element on overlapping 

### ISSUE THREAD

**Issue by HannaRestoGuru** [react-grid-layout/react-grid-layout#1650]
Is there a way to define which of overlapped elements should go on top of others?

**Comment by dmitriifrlv** [comment]
@HannaRestoGuru Have you figured out the way to define the top overlapped element?

**Comment by HannaRestoGuru** [comment]
@dmitriifrlv Yes, but it's not related to library. Grid items in my project have timestamps and duration, so based on this data I calculate whether item overlaps other item.
