### ISSUE TITLE
Draw grid on layout background

### ISSUE THREAD

**Issue by lcsjunior** [react-grid-layout/react-grid-layout#1651]
RGL have a non-hardcoded way to draw grid on layout background? CSS?

For example:
![image](https://user-images.githubusercontent.com/8947621/150162014-03e6d5b5-a1bc-42bd-8558-124ccea1d3fe.png)
![image](https://user-images.githubusercontent.com/8947621/150162248-a99ca19e-c57c-4e80-a5f6-42c5b96dfbb5.png)

**Comment by STRML** [comment]
No - sorry.
