### ISSUE TITLE
There's a mortgage agreement in the tarball pulled via NPM

### ISSUE THREAD

**Issue by brettimus** [react-grid-layout/react-grid-layout#1654]
Hey!

When you pull the package via npm `npm i react-grid-layout`, there is a file in the root called `foo.html`, the contents of which appear to be a mortgage agreement in Massachusetts. 

Steps to reproduce

1. `npm i react-grid-layout`
2. `cat node_modules/react-grid-layout/foo.html`

Just thought you should know!

**Comment by STRML** [comment]
Well, that's pretty weird - thanks! 

Published `1.3.2` which excludes some other files too for a smaller package.
