### ISSUE TITLE
Resizing a tile over the bottom edge of the layout does not trigger a height increase of the dashboard

### ISSUE THREAD

**Issue by lehnerchristian** [react-grid-layout/react-grid-layout#1657]
When I increase the height of a tile and move the cursor to the bottom edge of my dashboard the height only increases a little bit in Chromium based browsers and then stops.
While I can sometimes reproduce this in Firefox it works way more reliably for me. The only way I can achieve this in Chrome is that I resize a tile until the dashboard increases a little bit, stop resizing, scroll down and then start resizing again.

Here's a Codesanbox link with a little example:
https://codesandbox.io/s/chrome-rgl-scrolling-issue-hsr45?file=/src/App.js

I can also reproduce the same behavior in the simple demo example: https://react-grid-layout.github.io/react-grid-layout/examples/1-basic.html

Chrome (Sandbox example):
![Peek 2022-01-28 09-16](https://user-images.githubusercontent.com/1711080/151513036-2115b117-2a27-41aa-8fe0-3aabe5a3db27.gif)

Firefox (Sandbox example):
![Peek 2022-01-28 09-20](https://user-images.githubusercontent.com/1711080/151513096-6a890f1b-1a35-4f9c-9e59-ceaae86abf80.gif)

Chrome (Simple demo example):
![Peek 2022-01-28 09-26](https://user-images.githubusercontent.com/1711080/151513151-0f089fce-66e2-4faf-95f1-3164794addea.gif)

**Comment by fengbozhi** [comment]
I also encountered the same problem

**Comment by OFouda** [comment]
also running into this issue. any chance for an update here?

**Comment by raymar** [comment]
I also have the same issue...anyone made a progress here?

**Comment by raymar** [comment]
I figured it out...basically you just need to make sure, that the scroll is going down while resizing ;)

**Comment by lehnerchristian** [comment]
Hi @raymar ! Can you go into a little bit more detail how you solved it? Did you simply use `window.scrollBy(x, y)`  in the `onResize` or `onResizeStart` callback?
I'm sure this will also help others having the same issue :slightly_smiling_face:

**Comment by Junghoon-P** [comment]
> Hi @raymar ! Can you go into a little bit more detail how you solved it? Did you simply use `window.scrollBy(x, y)` in the `onResize` or `onResizeStart` callback? I'm sure this will also help others having the same issue 🙂

Hi @lehnerchristian . I recently had the same problem. I solved the problem a while ago. To share, use `onResize`. When `onResize` is working, just add a `window size` and `ref` to the component being resized to compare the height value of that component and hang a `scrollBy event`.
