### ISSUE TITLE
Nested Grids don't work. Unable to drag elements within a nested grid.

### ISSUE THREAD

**Issue by willh33** [react-grid-layout/react-grid-layout#1658]
I have a sub-grid within a grid and I am unable to drag elements that are in that sub-grid. I'm also unable to resize the elements horizontally

Here is the example: https://codesandbox.io/s/damp-currying-40xso?file=/src/ShowcaseLayout.js

**Comment by linus-amg** [comment]
@willh33 one way to accomplish this is to add `onDragStart={(a, b, c, d, event) => event.stopPropagation()}` to the `sub-grid`, doing that the parent will not receive the `by-default-propagated-drag-event` and wont move anymore. Great success!
