### ISSUE TITLE
Prevent dragStart event getting fired when click event happens

### ISSUE THREAD

**Issue by kishok** [react-grid-layout/react-grid-layout#1664]
**Issue**:
    when i click the actions in grid Item it automatically trigger the dragStart event and preventing the click functionality getting  called sometimes. 

**Expectation**:
Need the PR fix #1411  mentioned here / any alternatives. please merge it the stable branch and release it. Because this is majorly impact the usability of react-grid-layout in desktops and touch devices (ex. iPad). 

> Note: we use this library in production that really affect the user experience.  

**Environment**:
"react-grid-layout": "^1.3.0"

**Comment by luisiacc** [comment]
I have the exact same problem.

**Comment by sbecka** [comment]
We are also experiencing issues as described about above when users are using our app on an iPad. Users cannot click on any buttons inside react-grid-layout items but instead think the user it dragging the item the whole time. We also see this happening sometimes within HubSpot's dashboard items. Some items that can be clicked are being registered as dragging events. Are there any recommended solutions to distinguish between clicking and dragging events on buttons/links inside react-grid-layout items on an iPad?

**Comment by TheBranchDriftCatalyst** [comment]
Trying to get around this as well.

**Comment by asinfdev** [comment]
Same issue. Click events inside the item are not working, because the grid activates drag mode on click.

**Comment by rylm** [comment]
I have the same issue.

**Comment by asinfdev** [comment]
I got round the problem by setting the draggableHandle & draggableCancel props to the elements within the item. I defined the header area as draggableHandle, where the user can then drag and drop. The actual content area was provided with the class from draggableCancel.

```
draggableHandle='.dragHandle'
draggableCancel='.notDraggable'
```

**Comment by aleksandr-sidorov** [comment]
Please check the documentation - [Grid Layout Props](https://github.com/react-grid-layout/react-grid-layout?tab=readme-ov-file#grid-layout-props)
```
 // A CSS selector for tags that will not be draggable.
// For example: draggableCancel:'.MyNonDraggableAreaClassName'
// If you forget the leading . it will not work.
// .react-resizable-handle" is always prepended to this value.
draggableCancel: ?string = '',
```

So you can add a `className={'MyNonDraggableAreaClassName'}` to any element of the gid item and use any `onClick` handlers without being interrupted by the RGL.
