### ISSUE TITLE
AutoSize not working on initial ResponsiveReactGridLayout render

### ISSUE THREAD

**Issue by duhmojo** [react-grid-layout/react-grid-layout#1667]
Hi. I'm not sure if I'm doing something wrong but it seems like ResponsiveReactGridLayout autoSize doesn't fire initially, or not after the initial rendering. In the attached gif I show reloading the page, the grid width is fully sized based on the widget layout but its not resized.

When I resize the browser window the grid will auto resize, but when I reload the page, same story.

![autoSize](https://user-images.githubusercontent.com/1214395/154363268-377f5a9a-aad9-4cef-accc-403216f32f09.gif)

My usage is as follows. The problem exists with or without the onBreapointChange bit that I had to add to force pre-render on breakpoint changes related to another issue. 

I played with the layout change callback and they don't fire on initial render. Any tips would be great. Thanks.

```
<ResponsiveReactGridLayout
            autoSize={true}
            cols={4}
            breakpoints={{lg: 1200, md: 996, sm: 768}}
            cols={{lg: 4, md: 2, sm: 1}}
            useCSSTransforms
            isDraggable={false}
            isResizable={false}
            compactType={null}
            rowHeight={150}
            key={bp} // necessary to force breakpoint to reassess layout
            onBreakpointChange={setBp} // necessary to force breakpoint to reassess layout
        >
```

**Comment by duhmojo** [comment]
I tried firing the resize dispatch event to see if firing resize but it could be that its not mounted yet? (the mounted variable from https://github.com/react-grid-layout/react-grid-layout/blob/master/lib/components/WidthProvider.jsx)

```
  React.useEffect(() => {
    window.dispatchEvent(new Event('resize')); 
  }, []);
```

**Comment by DBids35** [comment]
I'm having the same issue

**Comment by jrothschild33** [comment]
Someone help pls? Same issue！The boxes inside the react-grid-layout spilled over the screen when refreshing the browser. It can't get back to normal unless manually resize the window.

**Comment by jrothschild33** [comment]
> I tried firing the resize dispatch event to see if firing resize but it could be that its not mounted yet? (the mounted variable from https://github.com/react-grid-layout/react-grid-layout/blob/master/lib/components/WidthProvider.jsx)
> 
> ```
>   React.useEffect(() => {
>     window.dispatchEvent(new Event('resize')); 
>   }, []);
> ```

have you solve the problem？

**Comment by duhmojo** [comment]
This should be reopened.
