### ISSUE TITLE
Implicit dependency on react-resizable

### ISSUE THREAD

**Issue by nrakochy** [react-grid-layout/react-grid-layout#1668]
Hi there, 

Thanks for the great library. I am just trying it out and running into an issue with the set-up. [In the README](https://github.com/react-grid-layout/react-grid-layout#installation), there is an expectation to import from `react-resizable`

```js
Include the following stylesheets in your application:
/node_modules/react-grid-layout/css/styles.css
/node_modules/react-resizable/css/styles.css
``` 

However, this is a dependency of `react-grid-layout` rather than a `peerDependency`. I am working in a project that checks `no-implicit-dependencies` linting, and thus, alas, fails to build. Any recommendations? 

[Here's a similar issue](https://github.com/react-grid-layout/react-grid-layout/issues/1408) but did not find this one mentioned so far as I can see.

**Comment by STRML** [comment]
You have a few options. You could simply add `react-resizable` as a dependency, or you could copy the styles out of the package into your project and import them directly.

**Comment by nrakochy** [comment]
Thanks for the note. Using the CSS styles works as expected. I considered the declared dependency route, but this runs the risk of getting out of date. Would you consider a PR to make this a `peerDependency`? Not sure the downstream implications

**Comment by STRML** [comment]
I think that may have some unintended consequences. Peer dependencies are best used for plug-ins for the peer library. 

Importing css via a loader isn't exactly a universal use case either. I'm not sure what the state of the art is for doing this right, these days, but this has worked fairly well so far.

**Comment by nrakochy** [comment]
Sounds good, appreciate the feedback 👍
