### ISSUE TITLE
Visual bug on drag

### ISSUE THREAD

**Issue by s4d-prince** [react-grid-layout/react-grid-layout#1678]
When I try to drag any element, it transforms to the right side by ~50%, but in the sandbox it works pretty well.

Screenshot: 
![image](https://user-images.githubusercontent.com/70597469/155852475-163f0440-092f-47e2-b505-f9452fed02df.png)

Link to sandbox: https://codesandbox.io/s/grid-layout-with-react-noihr6
Link to my repo: https://github.com/s4d-prince/dnd

**Comment by lorenamelor** [comment]
Same problem, here.

**Comment by janvarsa** [comment]
Same issue here. The item being clicked on jumps to the right of the cursor by the amount of margin there is on the parent container.

**Comment by gabemanfroi** [comment]
I'm facing pretty much the same issue here... I have a Sidebar with a width of 104px, and to the right of it I have the area where is supposed to be my grid layout content, as you can see in the image below. 
![image](https://user-images.githubusercontent.com/32476134/163241906-66bd65cf-cef0-460b-972f-4adbcfd8555c.png)

It starts being transformed with a translate(10px, 10px), when I start the drag event the translate X value is increased to 114px, 10px initially added to 104, which I'm interpreting as being the width of the sidebar. The image below illustrates this:
![image](https://user-images.githubusercontent.com/32476134/163242190-9911ba6c-828d-423a-811b-08419e1dc51e.png)

**Comment by lhotamir** [comment]
@gabemanfroi Where did you import the file? I am facing the same issue.
