### ISSUE TITLE
Spaces unwanted between items, even with  margin [0,0]

### ISSUE THREAD

**Issue by rarc41** [react-grid-layout/react-grid-layout#1693]
### Describe the bug

I'm using  a responsiveGridLayout, and passing margin [0,0] as prop, it is suposed that not shoul be any space between items, but when applied zoom or change the the dimensions of the screen, i can see a litle space between some items,  like this:

![image](https://user-images.githubusercontent.com/69741658/158437873-3ef731bb-2126-4559-9b0c-1d2bca814184.png)

![image](https://user-images.githubusercontent.com/69741658/158438103-ae272f3a-23b6-4c82-a155-5a57cc5a2bd3.png)

### Your Example Website or App

https://codesandbox.io/s/condescending-snowflake-j6f3d1?file=/ShowcaseLayout-bugspaces.js

### Steps to Reproduce the Bug or Issue

1. go tto the link [CodeSandbox-bug]( https://codesandbox.io/s/condescending-snowflake-j6f3d1?file=/Sh) and pass margin=[0,0]
 as prop on the ResponsiveGridLayout 
2. click open on new window to check on full screen
3.  look for the spaces between items, (almost always appear near to the center of the screen, and if zoom is applied appear and other sections of the screen) the most visibles are the vertical spaces

### Expected behavior

As a user, I expected that not show any space between  the elements 

### react-grid-layout library version

1.2.5

### Operating System Version

Linux

### Browser

Chrome

### Screenshots or Videos

![2022-03-15_12-57](https://user-images.githubusercontent.com/69741658/158441777-e7a5ea0f-53d3-4abb-b14f-aba5a9473d35.png)  brakpoint lg, zoom 100%

![2022-03-15_13-00](https://user-images.githubusercontent.com/69741658/158442332-0cd2cd46-090f-4f88-a926-246a8c401ced.png) brakpoint: md,  zoom 110%

**Comment by ThomasChan** [comment]
I think it is the function `calcGridItemPosition`'s bug, and i made a little change for my own project like:
<img width="1848" alt="截屏2022-03-24 上午11 39 43" src="https://user-images.githubusercontent.com/5715335/159837595-9c2de0ef-3da5-45b6-b8eb-aa8afa93c18a.png">

@rarc41 you can try it.

I don't know maybe should i make a pull request of it?
