### ISSUE TITLE
Breaking down design in allowOverlap mode

### ISSUE THREAD

**Issue by alpfreda** [react-grid-layout/react-grid-layout#1695]
### Describe the bug

When you select a text with the mouse and drag it somewhere, the whole design breaking down.

this problem happens in `allowOverlap` mode.

video: 
https://user-images.githubusercontent.com/69018109/158947660-48565f21-ccc0-4a02-9802-29c829ba6a9e.mp4

İ solved my problem with this css code but it's not a good idea 

```
.no-select {
  user-select: none;
  -moz-user-select: none;
  -webkit-user-select: none;
}
```

thanks

### Steps to Reproduce the Bug or Issue

select a text with the mouse and drag it somewhere

### Expected behavior

design breaking down

### react-grid-layout library version

1.3.4

### Browser

Chrome

**Comment by alpfreda** [comment]
any help?

**Comment by chaehyeon01** [comment]
I'm facing the same problem. Somebody help me!
