### ISSUE TITLE
Rendered method called for already component on react grid layout which results into re-render for already added component

### ISSUE THREAD

**Issue by bawatrader** [react-grid-layout/react-grid-layout#1708]
### Describe the bug

Created a ResponsiveGridLayout
Added multiple components on layout (say 5)
On adding component 6, react grid layout is again rendering already added 5 component (which is causing state to reset)

Is there a way to avoid rendering for already added component on grid layou

 

### Your Example Website or App

github repo

### Steps to Reproduce the Bug or Issue

Created a ResponsiveGridLayout
Added multiple components on layout (say 5)
On adding component 6, react grid layout is again rendering already added 5 component (which is causing state to reset)

 

### Expected behavior

Was expecting to call render only for newly added compoennt

### react-grid-layout library version

1.3.0

### Operating System Version

Windows 10

### Browser

Chrome

**Comment by bawatrader** [comment]
Managed to avoid re-render with the help of userCallback and useMemo hooks

Wrapped component under parent container and ensured parent is not getting re-render with the help of memoization

**Comment by SamuelLin95** [comment]
May I know how you solved it ? I've tried using useMemo hook like this but the grid is re-rendering everytime a new component is added. 
![image](https://user-images.githubusercontent.com/53039899/183372473-e39f0b13-e06b-45e4-a13a-650f3dadb86b.png)
