### ISSUE TITLE
Components occasionally freeze when select elements are interacted with.

### ISSUE THREAD

**Issue by glass-waves** [react-grid-layout/react-grid-layout#1710]
### Describe the bug

I just updated the dependencies in my project, including React => 18.0.0 and react-grid-layout => 1.3.4. 

Everything seems to be working as expected, except occasionally, when interacting with Select elements in my grid layout components, the component turns the color of the placeholder(green) and becomes frozen. This is remedied by grabbing another component and moving it. The code is quite complex, so I will include a screenshot for now, but can provide code examples if necessary. To reiterate, this only started happening upon updating.

### Your Example Website or App

private app

### Steps to Reproduce the Bug or Issue

1. Interact with a select element inside of a grid layout item. 

### Expected behavior

That the component does not freeze after interacting with a select element. 

### react-grid-layout library version

1.3.4

### Operating System Version

macOs 11.4

### Browser

Other (add additonal context)

### Additional context

Brave browser. This happens on both windows and MacOs. It also happens in our local dev environment as well as in Production. 

### Screenshots or Videos

<img width="1356" alt="Screen Shot 2022-04-18 at 11 03 13 AM" src="https://user-images.githubusercontent.com/46694497/163853925-c5ccc945-264c-4aa7-9c10-994020d36046.png">

**Comment by glass-waves** [comment]
Downgraded to React 17.0.2 and it fixed this issue. I assume this is just a compatibility issue with React 18. Hope there is support for React 18 soon!

**Comment by deeptha-code-breaker** [comment]
Is there a fix with React 18 yet?

**Comment by ShreyasRP** [comment]
Facing the same issue here with React 18. Please update when there is a fix for this issue.
