### ISSUE TITLE
Grid width doesnt take up the full space provided until window resizes when using React-Bootstrap tabs

### ISSUE THREAD

**Issue by DireDiamond** [react-grid-layout/react-grid-layout#1712]
### Describe the bug

The title says it all. I have an autogenerated layout thing going, turning an array into tabs each with their own content grid, but the grids act weird, in the sense that they take up only like 60% of the provided screen space, until a window resize even is triggered by any means, be it actually resizing or opening the f12 console.

I am using react-bootstrap to create tabs and tab panes if that makes any difference.

Interestingly, if the tab is set as active by default this issue does not occur. also interestingly, every grid keeps its normal size between tab switches, until I refresh the page.

### Your Example Website or App

Node, React, React-Bootstrap

### Steps to Reproduce the Bug or Issue

1. create a vertical tab system in react bootstrap
2. put a grid inside each tab
3. not profit

### Expected behavior

I expected the width to take up the whole screen normally not to have to resize my window for the grid to work properly

### react-grid-layout library version

1.3.4

### Operating System Version

- OS: Windows 10

### Browser

Chrome

### Screenshots or Videos

https://user-images.githubusercontent.com/14033324/164271699-3c907572-9f4a-4512-bab8-6d64fa001273.mp4

**Comment by Aspyryan** [comment]
Any progress? Got the same problem

**Comment by DireDiamond** [comment]
> Any progress? Got the same problem

Yeah i managed to fix it by simulating a slightly delayed window resize event when onSelect is called by the Nav that is operating the tabs. But i still have no idea why this is happening or why a resize event fixes it.

**Comment by Aspyryan** [comment]
Alright thanks will test that out tomorrow!

**Comment by DireDiamond** [comment]
There is the side effect of it jittering every time you reload the generation, but this is how I am doing it currently:

**Comment by Aspyryan** [comment]
Well I just figured it out... It was because somehow the main tag having a display of flex braking it. I don't think this behaviour should be intended?

**Comment by DireDiamond** [comment]
Most of my containers are display flexes as well, but the resize even still works... Hmm.
Also it does not matter if responsive layout is used or RGL with my testing.
It deffinitely does not seem like intended behaviour

**Comment by ObaidAshiq** [comment]
u can use widthProvider HOC
import { WidthProvider, Responsive } from "react-grid-layout";
const ResponsiveReactGridLayout = WidthProvider(Responsive);
See the example of responsive stored in local storage
