### ISSUE TITLE
In some cases `resizing` class is not removed from GridItem element after `onResizeStop` event

### ISSUE THREAD

**Issue by serkononenko** [react-grid-layout/react-grid-layout#1714]
### Describe the bug

In some cases `resizing` class is not removed from GridItem element after `onResizeStop` event

### Your Example Website or App

https://react-grid-layout.github.io/react-grid-layout/examples/1-basic.html

### Steps to Reproduce the Bug or Issue

1. Go to https://react-grid-layout.github.io/react-grid-layout/examples/1-basic.html
2. Start resize some grid item and than return it to initial state
3. See in devtools `resizing` class is not removed after resize stop event

### Expected behavior

`resizing` class is removed after resize stop event

### react-grid-layout library version

1.3.4

### Operating System Version

Windows

### Browser

Chrome

### Screenshots or Videos

![err](https://user-images.githubusercontent.com/18212010/164424942-9eb076b2-f928-4bbe-b703-fdd91e04518b.jpg)

https://user-images.githubusercontent.com/18212010/164425918-74580d0e-514e-447d-b9cc-1aa8c4b5e53d.mp4

**Comment by Thebarda** [comment]
It's 2 years too late but I managed to find a workaround.

Create a state that will manage which item is being resized. It can be a local or a global state depending on your use case.
 
Create 2 function like so:
```
  const startResize = useCallback(layout, oldItem, newItem) => { // You can also use oldItem
    setIsResizingItem(newItem);
    // or setIsResizing(newItem.i);
  }, []);

  const stopResize = useCallback(() => {
    setIsResizingItem(null);
  }, []);
```

Then, put them in your ReactGridLayout component
```
onResizeStart={startResize}
onResizeStop={stopResize}
```

On your items, consume the aforementioned state to check if the current item is resizing:
```
const isResizing = useMemo(
  () => equals(id, isResizingItem.i),
  [isResizingItem, id]
);
```

Finally, sanitize the className provided by React Grid Layout:
```
const sanitizedReactGridLayoutClassName = useMemo(
  () => (isResizing ? className : className?.replace(' resizing ', '')),
  [className, isResizing]
);
```
