### ISSUE TITLE
Unable to set column height to 100 vh

### ISSUE THREAD

**Issue by ninjaKris** [react-grid-layout/react-grid-layout#1715]
### Describe the bug

There is currently no way to initially set a column's height to 100% or 100vh like so:
```
layout: [
      { i: "a", grid: { x: 0, y: 0, w: 1, h: '100vh' } }
    ]
```
Can this be supported?

### Your Example Website or App

n/a

### Steps to Reproduce the Bug or Issue

1. Implement Grid
2. Try and set the initial layout 
3. Swap between different monitors
4. Columns aren't taking up the full height

### Expected behavior

As a user I would expect to be able to initially set a grid's child to be full height or a screen's percentage, but I am unable to.

### react-grid-layout library version

6.10.3

### Operating System Version

Linux

### Browser

Chrome

**Comment by dariovillalta** [comment]
layout item value h can only be a number,  use a library like @react-hook/window-size to get a numerical value of the screen size, which you will be able to pass to the value h of the layout item
