### ISSUE TITLE
Layout is not auto aligned responsively 

### ISSUE THREAD

**Issue by Shank78** [react-grid-layout/react-grid-layout#1718]
### Describe the bug

Hi Team,

I tried this below example from react grid layout demo 8. Its not auto aligned based on different screen sizes.  Its always aligning right side of window. 
Kindly find the screen shot 

[Demo 8 - Responsive with LocalStorage](https://react-grid-layout.github.io/react-grid-layout/examples/8-localstorage-responsive.html)

This is how its displaying in desktop View 
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/94745370/166727049-698e9ee7-db06-4850-992c-c1aef4724a08.png">

This is how its displaying in  tablet view / small size monitor
<img width="662" alt="image" src="https://user-images.githubusercontent.com/94745370/166727195-93da036d-5135-4460-ab94-a89cdf36b38f.png">

Is there any way to auto align the items responsively?

Expected output is automatically align the items to small size screens
<img width="662" alt="image" src="https://user-images.githubusercontent.com/94745370/166727358-a09040e2-f2a4-4d9a-a1f5-1120f01515f2.png">

Thanks in advance

### React Grid Layout Source

https://react-grid-layout.github.io/react-grid-layout/examples/8-localstorage-responsive.html

### Steps to Reproduce the Bug or Issue

1. Go to this url with desktop [React grid layout Demo 8](https://react-grid-layout.github.io/react-grid-layout/examples/8-localstorage-responsive.html)
2. Go to this url with mobile [React grid layout Demo 8](https://react-grid-layout.github.io/react-grid-layout/examples/8-localstorage-responsive.html)

You can see responsiveness.

### Expected behavior

As a user, I expected to auto align properly in different set of screens and mobiles /tablets.. 

Here I just tried the same size and with for each items if we increase the width and height of the item it will give bad user experience. Kindly find the screens hot below

I just Increased the width and height screen shot for desktop
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/94745370/166724346-5472e677-fb67-40f0-86b1-186a71e7dc4c.png">

This is how it's displaying in the tablets and small size of screens
<img width="661" alt="image" src="https://user-images.githubusercontent.com/94745370/166724543-283da2e1-d2f8-40fb-90f9-70be125e9958.png">

### react-grid-layout library version

1.3.4

### Operating System Version

windows

### Browser

Chrome

**Comment by ebrahimm2020** [comment]
I have the same issue. and it can improve the user experience too much as described here

**Comment by selcukfatihsevinc** [comment]
Same here 🙋‍♂️

**Comment by khanzzirfan** [comment]
Same issue facing here. Any suggestion why its doing would be really appreciated.
