### ISSUE TITLE
data-grid props ignored in custom child components

### ISSUE THREAD

**Issue by binaryartifex** [react-grid-layout/react-grid-layout#1722]
### Describe the bug

My intent was to hardcode the values of the 'w' & 'h' keys in the data-grid related properties. At present these values only seem to work when they are set within the parent component. The widgets im building are being built with respect to particular height and weight ratios and should not be able to be altered. It would be great to be able to isolate certain data-grid properties within the child components themselves.

### Your Example Website or App

https://codesandbox.io/s/icy-river-dotq6i?file=/src/dashboard/dashboard.tsx

### Steps to Reproduce the Bug or Issue

1. Create new component using the default ResponsiveGridLayout example in the documentation
2. Create custom child as per documentation recommendation and manually set data-grid props along with a 'w' and 'h' set to 2
3. Add an inline div child to ResponsiveGridLayout with a 'w' and 'h' set to 1 for comparison
4. Note that both components have the same dimensions.

### Expected behavior

The ResponsiveGridLayout component won't override the data-grid properties set on child widgets. Either that or they are ignored entirely.

### react-grid-layout library version

1.3.4

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by WolfyUK** [comment]
@binaryartifex Do you remember if you found a solution to this issue?
