### ISSUE TITLE
Moving elements not working if mouse/touch events are not passed to custom React component

### ISSUE THREAD

**Issue by zrwsk** [react-grid-layout/react-grid-layout#1750]
### Describe the bug

What I noticed is that providing `style`, `className` and `ref` for custom react elements (as it's mentioned in docs) is not enough. To have grid fully operational it is necessary to pass also other props provided by `react-grid-layout` which are `onMouseDown`, `onMouseUp` and `onTouchEnd`.

I'm opening PR to update it in docs.

### Your Example Website or App

https://codesandbox.io/s/jolly-hawking-s9rerb?file=/src/ShowcaseLayout.js:419-489

### Steps to Reproduce the Bug or Issue

CodeSandbox example - doesn't work. Uncomment lines 13-15 to make it work.

### Expected behavior

docs updated

### react-grid-layout library version

1.3.4

### Operating System Version

all

### Browser

Chrome

**Comment by STRML** [comment]
Thanks!
