### ISSUE TITLE
Make react-grid-layout work on react native

### ISSUE THREAD

**Issue by infinium360** [react-grid-layout/react-grid-layout#1765]
### Describe the bug

I would be interested by a version of react-grid-layout which work on both reactjs than reactt native

### Your Example Website or App

none

### Steps to Reproduce the Bug or Issue

none

### Expected behavior

none

### react-grid-layout library version

all

### Operating System Version

all

### Browser

Other (add additonal context)

### Additional context

nothing

### Screenshots or Videos

nothing

**Comment by STRML** [comment]
Sorry, no plans to do this. I don't have the time. I'd review a PR.
