### ISSUE TITLE
using remote layout data doesn't work

### ISSUE THREAD

**Issue by CaptainJon** [react-grid-layout/react-grid-layout#1768]
### Describe the bug

when i try to set the layout property with local data, it works, however when i try to get the layout array data from remote server, it won't work. 

### Your Example Website or App

no for now

### Steps to Reproduce the Bug or Issue

set initial layout property with an empty array, then get remote layout data from my server, it won't work anymore

### Expected behavior

layout works when i use remote layout data

### react-grid-layout library version

latest version

### Operating System Version

windows 10

### Browser

Chrome

**Comment by STRML** [comment]
This is impossible for anyone other than you to debug and does not point to an issue in RGL. Please try debugging your own program.
