### ISSUE TITLE
RGL component re-rendered upon change in react state 

### ISSUE THREAD

**Issue by arslantoor** [react-grid-layout/react-grid-layout#1805]
### Describe the bug

i am iterating  over RGL component in useEffect via api call, Actually we are creating a dynamic custom dashboard, and we are saving user operation like daragStop, Resize stop and RGL give us the list of all(x,y,w,h) widget on dragStop, and resizeStop, which is working fine,and inside the widget we are displaying data tables, charts, e.g line chart , but when we are trying to apply filters into the datatables, and we have some features inside datatable like he can drag datatable columns, but when user does so our whole widget get drag able, and we unable to drag the column of datatable, so we just want to make the dragable feature just over the head of the widget rather than all over the widget.

### Your Example Website or App

https://qa-daggerfe.mltitans.com/

### Steps to Reproduce the Bug or Issue

Signup to the application
After login you will be redirected to default dashboard
There would be a sidebar menu , upon click on datatable icon, a widget will be created , in the dashboard and you can create multiple widget upto 10
now try to edit the dashboard name at the top left of the inner dashboard area excluding header and sidebar menu
you will experience re-render of the widgets

### Expected behavior

this issue as whole for every one

### react-grid-layout library version

 "react-grid-layout": "^1.3.4",

### Operating System Version

ubuntu 20.04

### Browser

Chrome

### Additional context

e

**Comment by arslantoor** [comment]
bug with application

**Comment by mikle7** [comment]
Experiencing similar issues, did you ever end up fixing this?

Looks like we're building similar functionality projects for very different things, would love to pair on some RGL issues so i'm not alone.

Feel free to email me or message on discord
michael@thehybridminds.com
Discord: Mikle#2018

**Comment by hootan-rocky** [comment]
If you're using the `ResponsiveReactGridLayout` the problem is caused by It's value changing on every render 

```ts
const ResponsiveReactGridLayout = useMemo(()=>WidthProvider(Responsive), [])
```

This would probably stop the layout from re-rendering on state change.

**Comment by michaelBWoodside** [comment]
> If you're using the `ResponsiveReactGridLayout` the problem is caused by It's value changing on every render
> 
> ```ts
> const ResponsiveReactGridLayout = useMemo(()=>WidthProvider(Responsive), [])
> ```
> 
> This would probably stop the layout from re-rendering on state change.

You just saved me from weeks long of playing around to get this working 😂

**Comment by devunolop** [comment]
@hootan-rocky you are life saver 👯

**Comment by vasyaqwe** [comment]
> If you're using the `ResponsiveReactGridLayout` the problem is caused by It's value changing on every render
> 
> ```ts
> const ResponsiveReactGridLayout = useMemo(()=>WidthProvider(Responsive), [])
> ```
> 
> This would probably stop the layout from re-rendering on state change.

Hey just wanna say thank you. I was banging my head against the wall, couldn't prevent rerenders. And this one line fixed everything. Props to you!

**Comment by STRML** [comment]
Thanks, this is a really helpful change to the README.
