### ISSUE TITLE
Docs: custom child component does not show use of children

### ISSUE THREAD

**Issue by nissimscialom** [react-grid-layout/react-grid-layout#1816]
### Describe the bug

Children prop must be rendered in child component to use the resizable handle

### Your Example Website or App

personal project

### Steps to Reproduce the Bug or Issue

not rendering the children means you don't get the resizable handle in the child component

### Expected behavior

doc example should mention it

### react-grid-layout library version

1.3.4

### Operating System Version

Windows

### Browser

Chrome

**Comment by Mbistami** [comment]
I doubt the library still have any support but yeah I've run into the same issue...

**Comment by nissimscialom** [comment]
I made a PR, we'll see if they merge it. At least other people will have a better time finding the solution

**Comment by STRML** [comment]
Thanks!
