### ISSUE TITLE
When using pnpm, there are problems in introducing dependency。

### ISSUE THREAD

**Issue by KilianShen** [react-grid-layout/react-grid-layout#1821]
<img width="1166" alt="Snipaste_2023-01-04_16-06-49" src="https://user-images.githubusercontent.com/86402559/210510569-ecc0ca64-8927-4ff5-84b7-9d54f2a09833.png">
### Describe the bug

By default, pnpm uses symlinks to add only the direct dependencies of the project into the root of the modules directory. So when introduced react-resizable ，it will look like this：
// import "/node_modules/react-resizable/css/styles.css";
import "/node_modules/.pnpm/react-resizable@3.0.4_biqbaboplfbrettd7655fr4n2y/node_modules/react-resizable/css/styles.css";
But the link will change, so this is unreasonable.It is hoped that the required dependencies can be merged or explained in its peerDependencies.
[pnpm](https://pnpm.io/motivation)

### Your Example Website or App

none

### Steps to Reproduce the Bug or Issue

use react-grid-layout

### Expected behavior

It is a fixed path when introducing dependency.

### react-grid-layout library version

1.3.4

### Operating System Version

Windows

### Browser

Chrome

**Comment by agarwalvishal** [comment]
I've been facing the same issue with pnpm due to its non-flat directory structure unlike npm. What would be the correct way to include the react-resizable css file?

**Comment by ferretwithaberet** [comment]
> I've been facing the same issue with pnpm due to its non-flat directory structure unlike npm. What would be the correct way to include the react-resizable css file?

I fixed this by adding `public-hoist-pattern[]=react-resizable` to my `.npmrc` file, this will hoist the `react-resizable` package to the main `node_modules/` folder.
