### ISSUE TITLE
IsResizable and IsDraggable on ResponsiveGridLayout does not work when changing state

### ISSUE THREAD

**Issue by melihcoban** [react-grid-layout/react-grid-layout#1896]
### Describe the bug

I have a state called editMode where I allow user to edit the dashboard. I have the following ResponsiveGridLayout setup:

      <ResponsiveGridLayout
        isDraggable={editMode}
        isResizable={editMode}
        className="layout"
        layouts={{ lg: layoutProps }}
        breakpoints={{ lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0 }}
        margin={[10, 10]}
        cols={{ lg: 12, md: 10, sm: 8, xs: 6, xxs: 4 }}
      >
        {items.map(x => x)}
      </ResponsiveGridLayout>

I am using the ResponsiveGridLayout with useMemo hook shown in the documentation.

const ResponsiveGridLayout = useMemo(() => WidthProvider(Responsive), []);

However, when I set the editMode dashboard items do not become resizable or redraggable. If I put the items as a dependency in the useMemo it does work but whole grid refreshes that way.

const ResponsiveGridLayout = useMemo(() => WidthProvider(Responsive), [editMode]);

### Your Example Website or App

Private application therefore I cannot share.

### Steps to Reproduce the Bug or Issue

1. Add isDraggable and isResizable properties to the GridLayout with a state.
2. Change the state
3. Resizable and Draggable properties do not change and keep their initial value.

### Expected behavior

As a user, I expect resizable and redraggable properties change when I set them with a state, but they do not do so.

### react-grid-layout library version

1.3.2

### Operating System Version

Windows

### Browser

Edge

**Comment by alight122** [comment]
You could try this way.

**Comment by alight122** [comment]
You could try this way.

**Comment by alight122** [comment]
Same question. but you could try this way.`const ResponsiveGridLayout = useMemo(() => WidthProvider(Responsive), [state]);`

**Comment by alight122** [comment]
Same question. but you could try this way.`const ResponsiveGridLayout = useMemo(() => WidthProvider(Responsive), [state]);`

**Comment by melihcoban** [comment]
> Same question. but you could try this way.`const ResponsiveGridLayout = useMemo(() => WidthProvider(Responsive), [state]);`

I edited my initial comment as I already tried this but didn't write it correctly. `  const ResponsiveGridLayout = useMemo(() => WidthProvider(Responsive), []);` This makes whole grid to re-position and re-render again. Do you have any other idea on how to fix it?

**Comment by apedretti** [comment]
How are you triggering the state change (dragging, resizing)? Is it an external button or an event (e.g. clicking something) inside the children?

**Comment by melihcoban** [comment]
@apedretti 
![image](https://github.com/react-grid-layout/react-grid-layout/assets/38351761/0c98854e-efd0-4fbd-a16b-b21239b8dc5f)
It is an external button on the same page.

`const ResponsiveGridLayout = useMemo(() => WidthProvider(Responsive), [editMode]);`

This is the method where I change the state:

`  const handleEdit = (event: React.MouseEvent) => {
    event.preventDefault();
    setEditMode(true);
  };`

This is the responsive grid layout:
`<ResponsiveGridLayout
        isDraggable={editMode}
        isResizable={editMode}
        className="layout"
        onLayoutChange={x => setLayout(x)}
        layouts={{lg: layout}}
        breakpoints={{lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0}}
        margin={[10, 10]}
        cols={{lg: 12, md: 10, sm: 8, xs: 6, xxs: 4}}
      >
        {items.map(x => x)}
      </ResponsiveGridLayout>`

**Comment by apedretti** [comment]
Sorry for the late reply; I was hoping you told me the event was being triggered from the inside as I believe I discovered an interesting dynamic (you can't enable and drag on the same click).

But back to your issue, here's a working sample: https://codesandbox.io/s/fast-tdd-5x5ckc

Note that in your declaration: `const ResponsiveGridLayout = useMemo(() => WidthProvider(Responsive), [editMode]);` The function you have inside useMemo doesn't make use of `editMode`, so you don't need to include the dependency (it'd still work if you do, just adding unnecessary re-renderings).

Your initial code seems to be working so I'm not sure what could be wrong on your app. In any case, here's a way to solve it: Take the working sample I linked above, paste it on your application, and start modifying it until you get to the modification that breaks it.

**Comment by melihcoban** [comment]
Thanks for the reply! My code was not working without adding editMode to dependency array in useMemo. I checked your working sample and figured out that the problem was mapping the items without key inside the responsive layout. I already had keys in the array I am mapping so I thought nothing of it.

`{items.map(x => x)}`

Changing the above fixed the actual issue. Thanks for the example again.

```
<ResponsiveGridLayout
        isDraggable={editMode}
        isResizable={editMode}
        className="layout"
        onLayoutChange={x => setLayout(x)}
        layouts={{lg: layout}}
        breakpoints={{lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0}}
        margin={[10, 10]}
        cols={{lg: 12, md: 10, sm: 8, xs: 6, xxs: 4}}
      >
        {items.map((item) => (
          <DashboardItem key={item.id}>
            {item.chart}
          </DashboardItem>
        ))}
      </ResponsiveGridLayout>
```

**Comment by dkozar** [comment]
I have the same problem with `GridLayout`. The fix proposed here doesn't work for me.

So, `editMode` is the state, being toggled with the button. It's being fed to `GridLayout`:

```tsx
<GridLayout
  layout={layout}
  isDraggable={editMode}
  isResizable={editMode}
>
  {children}
</GridLayout>
```

However, toggling editMode doesn't make the resize handles appear/disappear, nor the widget becomes draggable.
**ONLY AFTER I RESIZE THE SCREEN A BIT this happens.**

I even tried to rebuild the layout every time the editMode changes, and changing the static and resizeHandles properties of layout item. However, still the same:

```ts
export const useLayout = (widgets: Widget[], editMode: boolean) =>
  useMemo(
    () =>
      widgets.map((widget: Widget) => {
        const { x = 0, y = 0, w = 1, h = 1 } = widget.layout || {};

        return {
          i: widget.id,
          x,
          y,
          w,
          h,
          static: !editMode,
          resizeHandles: editMode ? ["se"] : undefined,
        };
      }),
    [editMode, widgets]
  );

```

Additionally, if I switch the edit mode off, and the resize handles are still there, if I drag the handle, the app crashes with:

![2023-09-13_12-17-44](https://github.com/react-grid-layout/react-grid-layout/assets/1078403/1978cd79-0149-4fd4-b1c6-d6044c3a9e87)


Is there any other way to "force update", without the screen resize?

I use the version `1.3.4`.

**Comment by dkozar** [comment]
Related issue: https://github.com/react-grid-layout/react-grid-layout/issues/1936#issuecomment-1717816229

Demo: https://codesandbox.io/s/musing-bas-txnszm?file=/src/ShowcaseLayout.js

![2023-09-13_16-03-05](https://github.com/react-grid-layout/react-grid-layout/assets/1078403/44235c3e-8c24-42a6-bc81-e97f03231d60)

**Comment by melihcoban** [comment]
I do not believe this is a related issue as I do not need screen to be resized. I believe you might need to map the objects inside layout, not generate them before.

**Comment by dkozar** [comment]
> I do not believe this is a related issue as I do not need screen to be resized. I believe you might need to map the objects inside layout, not generate them before.

Well, that's not a solution for me, since the children have been built outside, and are passed in from the parent.

GridLayout is just one of the layouts: there is no real need to re-render the children, as the duty of layout is just to inject those `style` and `className` to its direct children.

**Comment by dkozar** [comment]
I found a workaround! :)

In order to trigger re-rendering when the `editMode` is toggled, I'm wrapping the whole thing in a `div`:

```tsx
let content = <GridLayout...

if (editMode) {
    content = <div>{content}</div>;
}

return content;
```

**Comment by melihcoban** [comment]
Glad to hear that, I am marking this issue as closed.

**Comment by dkozar** [comment]
> Glad to hear that, I am marking this issue as closed.

Yes, the workaround works for us, but is highly inefficient. Un/mounting the whole hierarchy of very complex widgets leads to browser slowdown (switching edit mode takes a second or two). We would really prefer a "native" solution.
