### ISSUE TITLE
npm run build error: Makefile:29: *** multiple target patterns.  Stop.

### ISSUE THREAD

**Issue by lorenzobalzani** [react-grid-layout/react-grid-layout#1902]
### Describe the bug

I experienced the error `Makefile:29: *** multiple target patterns.  Stop.`  when running `npm run build`.

### Your Example Website or App

NO SITE

### Steps to Reproduce the Bug or Issue

Run npm run build inside the root folder.

### Expected behavior

Npm should run the build command successfully.

### react-grid-layout library version

1.3.4

### Operating System Version

macOS

### Browser

Chrome

**Comment by lorenzobalzani** [comment]
@STRML

**Comment by STRML** [comment]
Looks like npm@9 removed `npm bin`. Fixing..
