### ISSUE TITLE
CSS sidebar collapse animation doesn't make grid resize

### ISSUE THREAD

**Issue by YairLevi** [react-grid-layout/react-grid-layout#1909]
### Describe the bug

I have a sidebar that collapses using tailwind. When clicking a button, it shrinks or expands.
When I resize the entire app window, the grid does actually resizes its columns and items in accordance to the new width.
But, when the sidebar collapses, it doesn't detect the change in the with the grid container's width.
How can I fix this?

Sidebar:
```tsx
return (
    <div
      className={`${open ? 'min-w-[14rem] w-56' : 'min-w-[4rem] w-16'} 
      group duration-200 bg-[#0f0f11]  [&_*]:text-[#ceced0] h-screen px-2 py-2 flex flex-col relative group`}>
      <div className="h-full [&>*]:my-2">
        <SidebarItem text="Calendar" open={open} icon={faCalendarDays}/>
        <SidebarItem text="Notes" open={open} icon={faNoteSticky}/>
      </div>
//rest is irrelevant
```

Grid:
```tsx
<ResponsiveGridLayout
            className="h-full w-full min-w-[49rem]"
            breakpoints={{lg: 1200}}
            width={500}
            preventCollision={true}
            cols={{'lg': 7}}
            rowHeight={rowHeightInPixels * 0.4}
            onLayoutChange={onLayoutChange}
            resizeHandles={['n', 's']}
            maxRows={24 * 4}
            compactType={null}
            isBounded={true}
            margin={[0, 0]}
          >
          // ...
```

### Your Example Website or App

private.

### Steps to Reproduce the Bug or Issue

.

### Expected behavior

Grid is supposed to extend width not only when resize window, but also when size of other elements change, and there's more room for the grid to take (width wise).

### react-grid-layout library version

v1.3.4

### Operating System Version

Windows 10

### Browser

Chrome

**Comment by mosh-tudor** [comment]
@YairLevi 
Try `window.dispatchEvent(new Event('resize'));` when you expand/collapse sidebar.

**Comment by YairLevi** [comment]
> @YairLevi Try `window.dispatchEvent(new Event('resize'));` when you expand/collapse sidebar.

Hey, thanks for the answer, it worked.
I would add for others viewing this at some point in time:
If the collapse of the sidebar has some animation, use:
```ts
setTimeout(() => window.dispatchEvent(new Event("resize")), <animation_duration>)
```
Because apparently the grid resizes at the moment the event is triggered, and doesn't wait for the animation to end.
Thanks again, @mosh-tudor

**Comment by YairLevi** [comment]
> @YairLevi Try `window.dispatchEvent(new Event('resize'));` when you expand/collapse sidebar.

Hey, thanks for the answer, it worked.
I would add for others viewing this at some point in time:
If the collapse of the sidebar has some animation, use:
```ts
setTimeout(() => window.dispatchEvent(new Event("resize")), <animation_duration>)
```
Because apparently the grid resizes at the moment the event is triggered, and doesn't wait for the animation to end.
Thanks again, @mosh-tudor
