### ISSUE TITLE
preventCollision not taking effect while resizing items

### ISSUE THREAD

**Issue by jonashirata99** [react-grid-layout/react-grid-layout#1933]
### Describe the bug

After 1.4.0 version, preventCollision appears to be being ignored when resizing items.

### Your Example Website or App

https://codesandbox.io/s/elated-napier-gr5lgl

### Steps to Reproduce the Bug or Issue

1. Change Compaction Type to No Compaction
2. Use resize handle in horizontal (element itself will be pushed down until find some free space)
3. Use resize handle in vertical (elements bellow will be pushed)

### Expected behavior

When resizing with preventCollision, I expect the element to just fill the free space when available without moving out of place and not pushing the other elements, exactly the same way as in version 1.3.4

### react-grid-layout library version

1.4.1

### Operating System Version

Linux

### Browser

Chrome

**Comment by xams-creator** [comment]
same problem.
after set the `preventCollision` attribute, it seems a little strange to resize the grid item

**Comment by dseif** [comment]
I wonder if this was caused by the work we did here https://github.com/react-grid-layout/react-grid-layout/pull/1917

I can take a look after work to see if I can lend a hand fixing.

**Comment by dseif** [comment]
It does look look like #1917  caused this issue. I'm working on a fix now, will keep you posted.
