### ISSUE TITLE
Label rendered with animation

### ISSUE THREAD

**Issue by vehere-ccuMaksym** [react-grid-layout/react-grid-layout#1946]
### Describe the bug

After update to 1.4.0 the animation (slide from right to left) appeared during the label render.

Here is my layout props: 
```
const gridProps = {
    allowOverlap: true,
    cols: 1,
    compactType: null,
    isBounded: true,
    isDraggable: false,
    isResizable: false,
    margin: [0, 0],
    maxRows: pageConfig.endTime - pageConfig.startTime,
    preventCollision: true,
    resizeHandles: ['s'],
    rowHeight: 40 / pageConfig.partsNumber,
    useCSSTransforms: false,
  };

```
### Your Example Website or App

https://staging.bookey.ltd/en/room/64ef91222e216d4443d4fd54

### Steps to Reproduce the Bug or Issue

1. Click on any date in Calendar.

### Expected behavior

I want to have some option to disable this animation.

### react-grid-layout library version

1.4.2

### Operating System Version

windows

### Browser

Chrome

### Additional context

You can check how the 1.3.4 version behaves here https://bookey.ltd/en/room/5ee27e4f62dabf0012c41501

### Screenshots or Videos

![slide](https://github.com/react-grid-layout/react-grid-layout/assets/15338501/1edf74e1-1749-4300-955c-8fc44c56482b)

**Comment by xams-creator** [comment]
in 1.3.4 
```
.react-grid-item {
    transition: all .2s ease;
    transition-property: left,top;
}
```
in 1.4.x
```
.react-grid-item {
    transition: all .2s ease;
    transition-property: left,top,width,height;
}
```

**Comment by xams-creator** [comment]
> 在1.3.4中
> 
> ```
> .react-grid-item {
>     transition: all .2s ease;
>     transition-property: left,top;
> }
> ```
> 
> 在 1.4.x 中
> 
> ```
> .react-grid-item {
>     transition: all .2s ease;
>     transition-property: left,top,width,height;
> }
> ```
Maybe you can add className.
