### ISSUE TITLE
Double animation on first render

### ISSUE THREAD

**Issue by Arkellys** [react-grid-layout/react-grid-layout#1951]
### Describe the bug

I updated my version of `react-grid-layout` from `1.3.4` to `1.4.1` and now I notice that on layout containing several "complex" components  the initial animation is weird, as if played twice.

I don't have the problem on the previous version, and it also doesn't appear when `StrictMode` is disabled.

I'm aware that `StrictMode` is only for dev, but it also exists to show potential problems. Something on `v1.4.0` or `v1.4.1` introduced this issue.

### Your Example Website or App

I tried to reproduce the issue on CodeSandbox but it would be too much code to have the same components as I have inside my layout (it's mostly Slate editors). I also tried with heavy components such as Mui's tables, but it just freeze the UI instead of showing the animation. The CodeSanbox below is a base but doesn't show the issue as the blocks only contain text.

https://codesandbox.io/s/ff95g8

### Steps to Reproduce the Bug or Issue

Try using complex components inside a layout.

### Expected behavior

I expect to see the initial animation only once.

### react-grid-layout library version

1.4.1

### Operating System Version

Windows 10

### Browser

Other (add additonal context)

### Additional context

Electron 26 (chromium)

### Screenshots or Videos

With `StrictMode`:

https://github.com/react-grid-layout/react-grid-layout/assets/32762018/9aa0905d-f003-4fbf-842c-0e1822851946

Without `StrictMode` (or with version `1.3.4`):

https://github.com/react-grid-layout/react-grid-layout/assets/32762018/56174613-8f44-4ee0-a813-f2ae23857f24

**Comment by Arkellys** [comment]
I tested commit by commit and managed to pinpoint the problem was introduced with `resizeObserver` on commit https://github.com/react-grid-layout/react-grid-layout/commit/2d72f8b3327febd1eff9a3535ce5b2183a37a143.

**Comment by Arkellys** [comment]
Here is what I gatherer with logs:

With the previous system using the `resize` event:
```shell
Mount (first) -> setState -> Unmount -> Mount (strict) -> setState
```

With the new system using the `resizeObserver`:

```shell
Mount (first) -> Unmount -> Mount (strict) -> setState
```

If I manually trigger a `setState` on first mount on the `resizeObserver` version it fixes the issue. Triggering an extra render doesn't seem clever, but could this missing rerender messes up with the CSS transitions somehow?

@currents-jantu any insightson this since you made this change?

**Comment by currents-jantu** [comment]
Didn't noticed it during tests since I'm not using StrictMode, let me check.

**Comment by Arkellys** [comment]
@currents-jantu I tried to replace [`resize-observer-polyfill`](https://github.com/que-etc/resize-observer-polyfill) with [`@juggle/resize-observer`](https://github.com/juggle/resize-observer) and it fixes the issue!

The flow stays the same, I don't see a `setState` on the first render, but no weird animation either. This library also seems more up-to-date, with its last update dating back to 2022, whereas the other library was last updated in 2018.

The only change to the code, apart from installing the library, is this:

```diff
- import ResizeObserver from 'resize-observer-polyfill';
+ import { ResizeObserver } from '@juggle/resize-observer';
```

What do you think? Could you test this please? I have not managed to start `react-grid-layout` in dev, I can only test it using a yarn portal on my app. Thanks.

**Comment by ddolcimascolo** [comment]
Hi all, @Arkellys

À polyfill will return the native implementation if it's there, so replacing the polyfill by another one should not matter. Are you testing in a browser that's not supporting ResizeObserver? The support seems pretty wide: https://caniuse.com/resizeobserver

David

**Comment by Arkellys** [comment]
Hello @ddolcimascolo 👋

I'm testing on the latest version of Electron, which is on Chromium 118, so the `ResizeObserver` is supported. But replacing the library does fix the issue, I tried 3 times to be sure. I really can't explain why.

https://github.com/react-grid-layout/react-grid-layout/assets/32762018/a436a0c9-147c-4443-b6db-ff5397a276a5

**Comment by ddolcimascolo** [comment]
Thx for the double check. I don't quite get it either...

**Comment by Arkellys** [comment]
@ddolcimascolo I found the difference, I tested with the native `ResizeObserver` without any polyfill library and I get the bug with it. On `@juggle/resize-observer`'s  README it's mentioned that:

> This will use the [ponyfilled](https://github.com/sindresorhus/ponyfill) version of **ResizeObserver**, even if the browser supports **ResizeObserver** natively.

So the problem is not because of the library, but because of native `ResizeObserver` itself (the why is still a mystery). I don't know what's the best course of action is in this case... I would certainly be happy if we could replace the polyfill library with the ponyfill one, since it works the same and fixes the issue. But I can also understand why it's better to use the native API.

@STRML if you're still around, any thoughts on this?

**Comment by STRML** [comment]
Yes - this probably has something to do with this:

<img width="862" alt="image" src="https://github.com/react-grid-layout/react-grid-layout/assets/1197375/e66f0fac-51d4-46d0-8620-c3ded0354118">

See https://react.dev/reference/react/StrictMode

Now, as for how we get around it - I'll investigate.

**Comment by STRML** [comment]
I'm inclined to think this is an issue with your implementation. I can't reproduce it in `make dev` even though we use `<React.StrictMode>` there. And your codesandbox is inconclusive. Can you provide a working reproduction?

**Comment by Arkellys** [comment]
@STRML Yes, the `ScrictMode` makes the component re-render after first mount. But it was not a problem with the `resize` event, and it's not a problem either with the ponyfill, but it is with the native `ResizeObserver` when the `setState` is not triggered on first mount.

I will try to see what I can do on the CodeSandbox this week end, hopefully I will be able to reproduce the bug. Otherwise I will have to use the ponyfill on my code to override the native API. At least If it's only a problem in dev, it's not catastrophic.

**Comment by Arkellys** [comment]
Okay, so after trying for hours to find where the problem might come from and trying to reproduce it on CodeSandbox, I think I will just give up. 

My layout have a lot of nested components, Portal, Transitions, map... I was not able to pinpoint if there is a faulty component or line of code in particular because it's not the case. I tried to comment out parts of the code component by component and function by function, and the more I comment, the less the problem is visible, regardless of what I remove. For a moment, I also thought the problem had randomly disappeared, but it turns out that I had my console closed and the bug is more visible when it's open. I just can't reproduce this level of complexity on CodeSandbox.

I can confirm that in prod the bug is not here at all (because no `StrictMode`), so I think I will just close this issue and use the ponyfilled `ResizeObserver` when in dev for my own comfort.

```js
if (isInDevelopment) {
  global.ResizeObserver = (await import("@juggle/resize-observer")).ResizeObserver;
}
```

Thank you all for taking a look at this.
