### ISSUE TITLE
Displacement bug after migrate to Vite (from CRA)

### ISSUE THREAD

**Issue by rever96** [react-grid-layout/react-grid-layout#1958]
### Describe the bug

I had the project working. than I had to change to vite for typescript 5 problems with cra. migration successful but a bug on displacement appeared.
the translation of grid element is tiny. heres the screen of what I see now.
<img width="1440" alt="Screenshot 2023-10-24 alle 07 10 48" src="https://github.com/react-grid-layout/react-grid-layout/assets/19595534/70482a38-744b-451a-9e82-0240e5322dc1">
<img width="1440" alt="Screenshot 2023-10-24 alle 07 11 11" src="https://github.com/react-grid-layout/react-grid-layout/assets/19595534/616c49bf-d0bf-4c9a-a4b9-60fc18c63ef1">

### Your Example Website or App

https://codesandbox.io/p/sandbox/objective-bas-h5plxv?file=%2Fsrc%2FApp.tsx%3A15%2C94

### Steps to Reproduce the Bug or Issue

code:
```
const ReactGridLayout = WidthProvider(RGL);

[...]

return (
    <ReactGridLayout
      layout={layout}
      // onBreakpointChange={this.onBreakpointChange}
      onLayoutChange={handleLayoutChange}
      useCSSTransforms={true}
      measureBeforeMount={true}
      compactType={null}
      preventCollision={true}
      cols={24}
      // width={4000}
      // cols={{ lg: 12, md: 12, sm: 6, xs: 4, xxs: 2 }}
      rowHeight={34}
      isDraggable={editable}
      isResizable={editable}
      transformScale={zoomValue}
      style={{
        // transform: `scale(${zoomValue})`,
        transformOrigin: 'top left',
        scale: `${zoomValue}`,
        width: `calc(${1600 / zoomValue}px - ${150 / zoomValue}px - ${0.25 / zoomValue}rem)`,
        backgroundColor: 'gray.50',
        overflow: 'auto',
      }}
    >
      {layout.map((box, index) => {
        return (
          // <AnimalBox variant='box' ref={(el: HTMLDivElement | null) => { refs.current[index] = el }} key={box.i} />

          <Box
            ref={(el: HTMLDivElement | null) => {
              refs.current[index] = el;
            }}
            key={box.i}
            // data-grid={box}
          >
            <AnimalBox
              id={box.id}
              title={box.name}
              hideContent={editable}
              animalBookings={animalBookings.filter((animalBooking) => animalBooking.box === box.id)}
              freeBox={freeBoxs.find((freeBox) => freeBox.box === box.id)}
            />
          </Box>
        );
      })}
    </ReactGridLayout>
  );
```

### Expected behavior

it should work like before the migration

### react-grid-layout library version

1.4.2

### Operating System Version

macOS sonoma 14.0

### Browser

Chrome

**Comment by rever96** [comment]
at first frame when loading it place correctly than its translation goes close to 0:

https://github.com/react-grid-layout/react-grid-layout/assets/19595534/4e21d77f-c2a0-469d-abaf-af8672d1eb08

**Comment by rever96** [comment]
I found that the property `measureBeforeMount` was true, before was working, now turning it false solve the problem

**Comment by gybber-dev** [comment]
I'm migrating to Vite too. But the error is related with new version of react-grid-layout. It was updated to 1.5.0 in my case after `npm i` command.
I returned to 1.3.4. And now it's working.
