### ISSUE TITLE
Have errors in utils.js && ReactGridLayout.js

### ISSUE THREAD

**Issue by devMo3** [react-grid-layout/react-grid-layout#1993]
### Describe the bug

When I try to build my project, I've errors in ./node_modules/react-grid-layout/build/utils.js 199:74 and ./node_modules/react-grid-layout/build/ReactGridLayout.js 360:28

A couple of days ago I also build my project and there were no errors

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

1. yarn
2. yarn build
have erorrs

### Expected behavior

Project successfully builded

### react-grid-layout library version

1.4.4

### Operating System Version

Windows

### Browser

Chrome

### Additional context

My package.json file

{
  "name": "app",
  "version": "1.0.0",
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "keywords": [],
  "author": "",
  "devDependencies": {
    "@babel/core": "^7.4.4",
    "@babel/plugin-proposal-class-properties": "^7.4.4",
    "@babel/plugin-proposal-decorators": "^7.4.4",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/plugin-transform-runtime": "^7.4.4",
    "@babel/preset-env": "^7.4.4",
    "@babel/preset-react": "^7.0.0",
    "@babel/register": "^7.4.4",
    "@babel/runtime": "^7.4.4",
    "@babel/runtime-corejs2": "^7.4.4",
    "@hot-loader/react-dom": "^16.8.6",
    "@import-meta-env/cli": "^0.2.2",
    "@import-meta-env/unplugin": "^0.2.1",
    "antd": "~4.5.0",
    "autoprefixer": "^9.5.1",
    "autoscroll-react": "^3.2.0",
    "axios": "^0.18.0",
    "babel-eslint": "^10.0.1",
    "babel-loader": "^8.0.5",
    "babel-plugin-import": "^1.11.0",
    "babel-plugin-module-resolver": "^3.2.0",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
    "babel-polyfill": "^6.26.0",
    "cache-loader": "^3.0.1",
    "clean-webpack-plugin": "^2.0.1",
    "core-js": "^3.0.1",
    "cross-env": "^5.1.1",
    "css-loader": "^2.1.1",
    "cypress": "^3.3.1",
    "eslint": "^5.16.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-config-prettier": "^4.2.0",
    "eslint-import-resolver-babel-module": "^5.1.0",
    "eslint-plugin-import": "^2.17.2",
    "eslint-plugin-jsx-a11y": "^6.1.2",
    "eslint-plugin-prettier": "^3.0.1",
    "eslint-plugin-react": "^7.13.0",
    "file-loader": "^3.0.1",
    "file-saver": "^2.0.1",
    "friendly-errors-webpack-plugin": "^1.7.0",
    "html-webpack-plugin": "^3.2.0",
    "less": "^3.9.0",
    "less-loader": "^5.0.0",
    "lodash": "^4.17.11",
    "node-sass": "^4.12.0",
    "postcss": "^7.0.14",
    "postcss-assets": "^5.0.0",
    "postcss-css-variables": "^0.12.0",
    "postcss-cssnext": "^3.1.0",
    "postcss-fixes": "^2.0.1",
    "postcss-import": "^12.0.1",
    "postcss-loader": "^3.0.0",
    "postcss-modules": "^1.4.1",
    "postcss-nested": "^4.1.2",
    "postcss-reporter": "^6.0.1",
    "postcss-scss": "^2.0.0",
    "postcss-svgo": "^4.0.2",
    "postcss-url": "^8.0.0",
    "precss": "^4.0.0",
    "prettier": "^1.17.0",
    "react-addons-css-transition-group": "^15.6.2",
    "react-app-polyfill": "^1.0.0",
    "react-hot-loader": "^4.8.4",
    "react-loadable": "^5.5.0",
    "react-mentions": "^3.0.0",
    "react-player": "^2.6.1",
    "react-router-redux": "^4.0.8",
    "redux-thunk": "^2.2.0",
    "sass-loader": "^7.1.0",
    "sockjs-client": "^1.3.0",
    "speed-measure-webpack-plugin": "^1.3.1",
    "stompjs": "^2.3.3",
    "style-loader": "^0.23.1",
    "svg-inline-loader": "^0.8.0",
    "svg-inline-react": "^3.1.0",
    "terser-webpack-plugin": "^1.2.3",
    "thread-loader": "^2.1.2",
    "uglifyjs-webpack-plugin": "^2.1.2",
    "url-loader": "^1.1.2",
    "webpack": "^4.30.0",
    "webpack-cli": "^3.3.1",
    "webpack-dev-server": "^3.3.1"
  },
  "dependencies": {
    "@ant-design/compatible": "^1.0.2",
    "@babel/polyfill": "^7.4.4",
    "chart.js": "^2.8.0",
    "connected-react-router": "~6.4.0",
    "dotenv": "^16.0.3",
    "emoji-replace": "^1.0.1",
    "history": "^4.9.0",
    "immutability-helper": "^3.1.1",
    "lamejs": "github:zhuker/lamejs",
    "prop-types": "^15.7.2",
    "ramda": "^0.26.1",
    "react": "^16.13.1",
    "react-beautiful-dnd": "^13.1.0",
    "react-chartjs-2": "^2.7.6",
    "react-dnd": "^14.0.1",
    "react-dnd-html5-backend": "^14.0.0",
    "react-dom": "^16.13.1",
    "react-grid-layout": "^1.2.5",
    "react-redux": "^7.0.3",
    "react-router": "^5.0.0",
    "react-router-dom": "^5.0.0",
    "react-rte": "^0.16.3",
    "react-scripts": "2.1.8",
    "redux": "^4.0.1",
    "redux-logger": "^3.0.6"
  },
  "description": ""
}

### Screenshots or Videos

![img1](https://github.com/react-grid-layout/react-grid-layout/assets/152269248/ad641345-ce8b-4816-b07e-f01b28b98781)
![img2](https://github.com/react-grid-layout/react-grid-layout/assets/152269248/5169f150-fece-4441-8293-85dccc42f508)

**Comment by devMo3** [comment]
I fixed it by changing the version "react-grid-layout": "1.4.2",

**Comment by devMo3** [comment]
done

**Comment by zhoudaxia2016** [comment]
This issue should be reopened?

**Comment by sweco-selumm** [comment]
"react-grid-layout": "1.4.2", worked for me too.
