### ISSUE TITLE
Grid elements lag behind the cursor and move very slowly in React 18

### ISSUE THREAD

**Issue by MaratBR** [react-grid-layout/react-grid-layout#2056]
### Describe the bug

Elements displayed in grid layout lag behind the cursor (i.e. do not follow the cursor) and move very slowly sometimes. This only happens in React 18.

We (I am writing on behalf of my team here) noticed this in production in our website. Some users noticed that when an element displayed in a grid layout is dragging, sometimes it starts to lag behind the cursor and move slower than the cursor itself.

For example the user grabs the element and moves 500px to the right. Element instead moves only 300px. The issue becomes more apparent the more complicated the element is (i.e. more HTML inside) or if you hover over other elements while dragging it. For example we have a tooltip that appears when you hover over some of the elements in a grid. If you grab one of them very quickly, it starts to lag behind the cursor by about 50-200px and then if you hover your cursor over another element and tooltip appears the distance between the element that is being dragged and the cursor starts changing as though react-grid-layout does not register mousemove events.

We tried to make a minimal example, but if you simplify the UI the issue goes  away... unless you use CPU slowdown.

So, this is a minimal example (in case if the link won't work or something):

```jsx
import ReactGridLayout, { WidthProvider } from "react-grid-layout";

const ResponsiveReactGridLayout = WidthProvider(ReactGridLayout);

const layout = [
  {
    i: "1",
    x: 0,
    y: 0,
    w: 2,
    h: 1,
  },
];

export default function Test() {
  const cols = 12;
  const rows = 6;
  const rowHeight = 50;
  const colWidth= 60;

  return (
      <ResponsiveReactGridLayout
        onLayoutChange={(l) => {
          console.log("layout changed");
        }}
        style={{
          border: "1px solid red",
          position: "relative",
        }}
        width={cols * colWidth}
        rowHeight={rowHeight}
        cols={12}
        layout={layout}
      >
        {layout.map((x, i) => (
          <div
            style={{
              background: "lightgray",
              border: "1px solid gray",
            }}
            key={i}
          >
            {x.i}
          </div>
        ))}
      </ResponsiveReactGridLayout>
  );
}
```

On my PC (13600K) it can only be reproduced on 20x CPU slowdown, but with a more complicated example we have in production it also can be reproduced with 4x/6x slowdown or on low-end machines (and even on a PC with Ryzen 3600G without any slowdown).

Issue can be reproduced using any of the examples you have (I used "Basic" example), but only if React 18 is installed.

### Your Example Website or App

https://codesandbox.io/p/devbox/react-grid-layout-weird-bug-8fqgdm

### Steps to Reproduce the Bug or Issue

1. Make React 18 app.
2. Copy any of the examples.
3. Enable CPU slowdown 20x (or use low-end device).
4. Drag a block.

### Expected behavior

Dragging is slow on 20x slowdown, but element follows the cursor (like it does in the example with React 17).

### react-grid-layout library version

1.4.4 and 1.3.4

### Operating System Version

Windows, MacOS

### Browser

Chrome

### Additional context

React: 18.2.0
Link to an example: https://codesandbox.io/p/devbox/react-grid-layout-weird-bug-8fqgdm
Link to the same example, but with React 17: https://codesandbox.io/p/devbox/react-grid-layout-weird-bug-forked-s2wrj5
react-draggable version: 4.4.6

Can also be reproduced in Safari.

**Comment by MaratBR** [comment]
Okay, well I am blind and did not see that React 18 is not listed as supported in the README. My apologies. However, does anyone still know if it's possible to still use react-grid-layout with React 18? Some sort of workaround.

**Comment by MaratBR** [comment]
It seems like there is already an issue #1829 for React 18 support, but it's pretty old, so I don't think closing this in favor of that one makes sense.

**Comment by MaxMusing** [comment]
See this PR for the fix: https://github.com/react-grid-layout/react-grid-layout/pull/2043

You can patch in the changes as a workaround until that's merged.
