### ISSUE TITLE
Autoscroll still not working properly in Chrome

### ISSUE THREAD

**Issue by ugoQ** [react-grid-layout/react-grid-layout#2080]
As stated here by @arunkumaralagesan in closed issue #1347:
> Hi, i am using RGL `"react-grid-layout": "^1.4.4"`, and i don't have `user-select: none;` in any of my css files.
> The above scroll behavior is not working as expected in "Chrome". Even [this example](https://github.com/react-grid-layout/react-grid-layout/issues/532#issuecomment-309756717) is not working as expected in chrome. Any fix for this?

_Originally posted by @arunkumaralagesan in https://github.com/react-grid-layout/react-grid-layout/issues/1347#issuecomment-2237208674_

**Comment by ugoQ** [comment]
Self closing this issue: a static footer in my page seems to have been the culprit here.

However I'm still seeing some edge cases where the scroll is not triggered in Chrome.

**Comment by arunkumaralagesan** [comment]
Hi, can you please share more info around how you fixed. Still facing the issue

**Comment by ugoQ** [comment]
Hi
I just `display: none` the fixed footer at the bottom of my page when the drag start, so the scrollable container takes 100% of the page:
![image](https://github.com/user-attachments/assets/b81bf607-4589-4136-b5d0-09d8b7107dc3)

**Comment by dalalRohit** [comment]
My issue was I wrapped the drag-handle icon with our custom UI `<Button/>` component. This prevented the drag-drop event from propagating to the respective handler of the library. 

That's why screen was not scrolling.

Hope this helps someone.

**Comment by sdasswift** [comment]
> My issue was I wrapped the drag-handle icon with our custom UI `<Button/>` component. This prevented the drag-drop event from propagating to the respective handler of the library.
> 
> That's why screen was not scrolling.
> 
> Hope this helps someone.

This helped, thank you!

**Comment by QuentinGrange** [comment]
Using a `<div/>` insteand of `<Button/>` was the solution for me ty !

> My issue was I wrapped the drag-handle icon with our custom UI `<Button/>` component. This prevented the drag-drop event from propagating to the respective handler of the library.
> 
> That's why screen was not scrolling.
> 
> Hope this helps someone.
