### ISSUE TITLE
Is there any method to get the sequence/order of the elements after drag??

### ISSUE THREAD

**Issue by ArifShaikh2611** [react-grid-layout/react-grid-layout#888]
Hi,
 I am trying to make my dashboard user editable i.e user can set the layout of the dashboard component. Is there any way to get the data of the components on onLayoutChange or onDragStop callbacks. I have tried  assigning the data to components in generateLayout method, but the data is not received in onLayoutChange method. Can anyone help me with this?

**Comment by cheriejw** [comment]
I was actually able to resolve this issue by saving the ordering in the `onLayoutChange` via code below:
```
const newOrder = map((lo) => { // using Ramda map, but could be done with forEach as well.
      return {
        i: lo.i,
        order: (lo.y)*(COL_SIZES[currentBreakpoint])+lo.x // Turning 2D to 1D
      }
    },layout).sort(function(a,b) { // Sorting by 1D order
      return a.order > b.order ? 1 : -1;
    });
```

Then I have a function for my `layouts` that changes the `i` value to the ordered `i` value. It was a little complicated, but someone in #462 said that you could just sort and pass back into ReactGridComponent, so you could use the above to sort and see if that works. 

My current issue is trying to get it to stay ordered AND the have the size of the tile persist.

**Comment by jedlikowski** [comment]
If anyone comes across this issue, I have been using this code to convert 2D layout to 1D order. It assumes that layout items have maxH  = 1, meaning that they can only be 1 row high. After sorting the layout array, I then map it to the actual objects I am sorting. I would be more performant to use a map/dictionary for `widgetButtons` instead of an array, but I have max 4 elements there so it's not a big deal.


```javascript
const newButtons = layout
            // sort layout items in the new order
            .sort((a, b) => {
                // same row, compare X
                if (a.y === b.y) {
                    return a.x - b.x;
                }

                // different row, compare Y
                return a.y - b.y;
            })
            // find button for each item
            .map((item) => {
                const button = widgetButtons.find((btn) => {
                    return btn.value === item.i;
                });
                return button;
            });
```
