### ISSUE TITLE
Grid content overlaps grid boundaries

### ISSUE THREAD

**Issue by gavinbelson** [react-grid-layout/react-grid-layout#893]
Auto-sizing the grid to the content does not seem to work.

If text is too long inside an element, it will overlap outside the element. Example:

[https://codesandbox.io/s/nw042q6lo0](
https://codesandbox.io/s/nw042q6lo0)

Is there a way to have the grid elements expand based on the contents?

**Comment by lovelyelfpop** [comment]
row height must be specified, so you can't make grid layout items auto height

**Comment by cpeker** [comment]
@lovelyelfpop 
In this example, when we define rowHeight={30} for instance, it still does not have auto height.
Is there a way to make grid content as auto height?

![resim](https://user-images.githubusercontent.com/14092775/52622570-2ff72980-2ebb-11e9-900b-561ee156e818.png)

When we try to delete "h" property, it throws an error.
How can we get height dynamically?

Thanks
