### ISSUE TITLE
tile size is not maintained on window resize

### ISSUE THREAD

**Issue by vprabhu81** [react-grid-layout/react-grid-layout#894]
Hi,
I was playing around the examples provided and found an issue for which I would need some help.

The example I am referring to is 
https://strml.github.io/react-grid-layout/examples/6-dynamic-add-remove.html

Here, if we resize the tiles to whatever sizes the user sets it to and then resize the window to the least possible size and then reset it back to 100% the tile is reset to its default size. 

Not sure if this is a bug or if there is a workaround around this,

**Comment by niklasp** [comment]
i am not a dev of this project, but i guess if you would save the resized elements dimensions, it would be the way you want it. check this demo: https://strml.github.io/react-grid-layout/examples/3-messy.html

**Comment by RainGrid** [comment]
@vprabhu81 yes, you need to save the layout, you lost it after the breakpoint

**Comment by CWSites** [comment]
@STRML, I believe this can be closed.
